### ISSUE TITLE
Add a way to move all windows to a specific desktop

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#10]
I'm thinking a menu item in the system tray icon that says "Gather All Windows". 

Opinions?

**Comment by mzomparelli** [comment]
@Kinmarui, what do you think of this feature? Also, I made the changes as you requested. I hope this eliminates your need to use multiple programs.

**Comment by mzomparelli** [comment]
I should point out that the green download buttons on the readme will always give you the most recent build even if that build hasn't been released. That download button gives you the pre-release v1.0.5.

**Comment by mzomparelli** [comment]
Anyone know how to get all the visible window handles from every desktop?

**Comment by Kinmarui** [comment]
Have you seen this http://stackoverflow.com/a/1032959/1678568 ?

**Comment by mzomparelli** [comment]
I have not seen this. Thanks! It looks like exactly what I need.

**Comment by mzomparelli** [comment]
Thanks @Kinmarui , this is now a working feature!
