### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by M3Rocket** [mzomparelli/zVirtualDesktop#101]
zVD v1.0.67 always hovers between 8% to 10% CPU usage on my setup. And I have a very fast i7-6700K at 4GHz and 32Gb of RAM running Windows 10 Pro Creators (v1703). I was using MoveToDesktop before, and have to move back since I have tried but can't seem to lower the zVD CPU usage. 

I have tried quiting and restarting zVD, and that would reset the CPU usage. But after a few minutes of just using my computer, it goes back up to the 8% to 10% range. Very annoying.

**Comment by mzomparelli** [comment]
I published a slightly modified version about an hour ago. The code that was removed a few hours ago was testing another approach for getting all windows for the DesktopView. It was not finished or used at all just some setup and it could have been that causing the high CPU. I'm going to put that code back in and test it out. You can try getting a new version of 1.0.67 using the main download link. Let me know if this solves your issue.

https://zomp.co/files.aspx?id=zvd

**Comment by mzomparelli** [comment]
I'm not able to reproduce the high CPU with or without that code so I'm not sure downloading that version would help.

None of the changes I made to 1.0.67 should be causing this. Is it possible that the issue existed before 1.0.67?

**Comment by mzomparelli** [comment]
Try turning off the mouse hook ----- Settings->More Settings

**Comment by M3Rocket** [comment]
Been using the new version you posted here for a few hours, and it seems like the CPU usage problem is fixed. At least so far... Will be keeping tabs on this.

**Comment by mzomparelli** [comment]
I'm glad to hear that. Thanks for letting me know.
