### ISSUE TITLE
Desktop Overlay Feedback & Discussion

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#102]
I have released a new 1.0.67 binary that includes a desktop overlay when switching desktops. Using this thread or Trello, we can discuss the overlay.

In future release I would like to add the ability to configure the overlay. This would include the following:

-Text color
-Text Font
-Text Size
-Duration of overlay
-Screen position

To download the version that has the overlay simply use the link on the main page which is the same as the following:
https://zomp.co/files.aspx?id=zvd

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow Overlay to be configurable](https://trello.com/c/GmvoYFi3/20-allow-overlay-to-be-configurable)

**Comment by nicolasdejong** [comment]
While I know that for some this is a very interesting feature, for me this is not required. Therefore I would like the option to switch if off, either by an explicit switch, or implicitly when the title is empty. Now it shows 'Desktop N', even if no title is set.

**Comment by mzomparelli** [comment]
Ok, one of the features is going to be disabling it completely. Thanks for the feedback.
