### ISSUE TITLE
Multiple monitors desktop view problem

### ISSUE THREAD

**Issue by jjhidalgar** [mzomparelli/zVirtualDesktop#109]
In case no one tried, using desktop view in a secondary monitor will trigger desktop view with the main monitor´s resolution, failing to fit in the screen and spanding to the next monitor.

https://i.imgur.com/ajwhN8W.png

**Comment by mzomparelli** [comment]
I figured this was an issue. I only use monitors of the same size so I never noticed. I'll correct this issue.

**Comment by mzomparelli** [comment]
I don't feel like adjusting the resolutions on my monitors. That's pure laziness lol. This new version will use the screen for which your mouse is located just like how the DesktopView window pops up. Please try this out and let me know if it resolves the issue. I plan on putting in a better fix, but this should work for now.

https://zomp.co/files.aspx?id=zvd

**Comment by mzomparelli** [comment]
I should point out that the new 1.0.68 breaks the desktop timers. I was working on that when I fixed this bug. I forgot about it until after I published.

**Comment by jjhidalgar** [comment]
I'll try today in a few hours

**Comment by jjhidalgar** [comment]
@mzomparelli It works.
