### ISSUE TITLE
Where are the settings stored?

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#11]
If you're looking for the settings file, it is stored in `IsolatedStorage`.

Search through the subfolders within the below folder and you should find a file named `zVirtualDesktop.bin`

`C:\Users\[username]\AppData\Local\IsolatedStorage`

Warning: It's not pretty, but it works. Also, because it is a binary file you can't modify directly in notepad. You can see the text though if you are interested in seeing it. Like I said, it's messy and you can't modify it. I'm working on another way to implement the settings.

**Comment by oywino** [comment]
Well, it doesn't seem to store settings at all on my PC. 
If I exit zVD and then restart it, all the wallpapers are forgotten. The same happens when I reboot.
I hope it's me doing something wrong, cause this isn't very practical....

**Comment by mzomparelli** [comment]
It has to run from the same location everytime otherwise it looks like a different app I guess and it creates a different IsolatedStorage path. I assume you see this effect if you always unzipped it to run it. Did you put it in startup folder? Just type "startup" in the address bar of Explorer and it will take you there.

The main reason I have this as a single executable is so that it can run directly from the startup folder. I should probably document the installation.

**Comment by mzomparelli** [comment]
Search through the folder I mentioned above and see how many zVirtualDesktop.bin files you have.

**Comment by mzomparelli** [comment]
I opened issue #14 for redesigning the settings. It's open to suggestions.
