### ISSUE TITLE
Switching desktops activates or causes Auto-Hide Taskbar to remain on screen - Software Conflict - Directory Opus

### ISSUE THREAD

**Issue by M3Rocket** [mzomparelli/zVirtualDesktop#110]
There is an option in Windows to Auto-Hide the Taskbar. When I use zVD to switch desktops using the direct shortcut (Ctrl-WIN-2 for instance) or when I activate the "Round Robin" feature, the taskbar always auto-shows and I have to find the application that is activating it to auto-hide it again. Whereas if I use the Windows keys to change desktops (Ctrl-WIN-Left and -Right) without Round Robin option, the taskbar stays hidden. 

This is really annoying since I have to click through various programs till I find the one that is keeping the taskbar on the screen instead of auto-hiding. I believe this has something to do with how various programs get window focus when switching to the desktop it's in.

To be clear, the only way to prevent this is to not use zVD to choose the desktop. Meaning using the native windows method to switch with round-robin disabled.

**Comment by mzomparelli** [comment]
I just tried to reproduce your issue, but I was unsuccessful. The Taskbar remained hidden as I cycled through desktops and only reappeared when I moved my mouse to the bottom where the taskbar would be.

I did manage to get the Taskbar to popup when selecting a thumbnail in DesktopView. I use code to focus the window in that case, but there is no such focus code when switching desktops using hotkeys.

Are you using v1.0.68?

**Comment by mzomparelli** [comment]
When I use the Move with Follow hotkey it does make the Taskbar popup, but then it disappears as quickly as it came.

**Comment by M3Rocket** [comment]
I am able to reproduce it by simply turning on and off the Round Robin feature. I think it's related to that. 

May also be related to certain applications? I have seen this with Chrome, Teamviewer, Directory Opus.

**Comment by mzomparelli** [comment]
I use TeamViewer and Chrome and have Round Robin enabled. Let me look into the Directory Opus application.

**Comment by mzomparelli** [comment]
Wow, Directory Opus looks pretty sweet. I don't want to download it on my dev machine until I know for sure it is not the culprit. I'm loading it into virtual machine now. I'll report back soon.

**Comment by mzomparelli** [comment]
I'm unable reproduce this issue in a fresh virtual machine with only Chrome, zVD, and Directory Opus.

Any other programs that you think might be contributing to this issue? Is it possible that you have a hotkey in Directory Opus that is interfering? I'm testing it now. DirectoryOpus has a lot of hotkeys and it's likely it is using a keyboard hook. If Directory Opus is executed before zVD then it has first dibs on the hotkeys and can choose to not send them through to the next hook which could be zVD.

**Comment by mzomparelli** [comment]
Yep, that's what it is! If you open zVD before Directory Opus you can avoid this issue. There's nothing I can do about this. You're letting Directory Opus start the hook first and it seems to want to handle hotkeys and still send them through. In all actuality, Directory Opus should not pass the hotkey down the chain if it handles it. What should be happening is that zVD should not be seeing that you pressed a hotkey that is setup in Directory Opus. zVD works this way. If you had the same hotkey setup in both apps and zVD was executed first then zVD would handle the hotkey and Directory Opus would never see that the hotkey was pressed.

**Comment by mzomparelli** [comment]
So to sum this up....

If you want to avoid this issue then:
1.) Disable Directory Opus from automatically starting up.
2.) When booting, start zVD then you can load Directory Opus.
3.) All is  great again!!

There are other ways to ensure one program is started before another, but if you can deal with this then you're good.
