### ISSUE TITLE
Crash in desktop view on cursor key

### ISSUE THREAD

**Issue by nicolasdejong** [mzomparelli/zVirtualDesktop#111]
When in desktop view and pressing cursor (right) multiple times, results in this:

![image](https://user-images.githubusercontent.com/12181216/31276966-dff902ba-aa9e-11e7-90f8-48f449590a12.png)

I could not reproduce this when opening the desktop view using the mouse (click on tray icon) but only via my shortcut (win + alt + enter)... oh, just tried again. It happens after pressing enter, followed by the cursor keys. My shortcut just happens to have an enter in there.

Not particularly important, since I don't think that screen has even keyboard support, but so you know.

**Comment by mzomparelli** [comment]
Thanks for the info. This should be easy to fix.

**Comment by mzomparelli** [comment]
I published a new 1.0.68 that fixes this bug. You can grab or wait for version 1.0.69. I'm fixing the wallpaper issue before I release 1.0.69.
