### ISSUE TITLE
Make size and opacity of desktop name overlay adjustable

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#116]
Like the title says. I like the feature, but it's too big for my tastes.

Keep up the good work!

**Comment by mzomparelli** [comment]
It is kind of big. I will make it adjustable.

**Comment by mzomparelli** [comment]
I've made some changes that resize it to fit the chosen font sizes. It did break the opacity part, but I'm working on that. You can test this by downloading from the main page.

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Overlay Enhancements](https://trello.com/c/TdUNcfq8/38-overlay-enhancements)

**Comment by mzomparelli** [comment]
I think this is done. Are you happy with the options you have? I do need more work with the overlay. Feel free to open another overlay specific issue :)
