### ISSUE TITLE
Report Window

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#117]
Hi, first things first; Congrats on the excellent progress with zVD!
It has become the single most important App in my bag-of-trix :)
Just a small request: Can you make the Report Window remember its last size and position?

**Comment by mzomparelli** [comment]
Thanks for the great feedback. I'm glad to hear about someone using the timers. This is an experimental feature and any feedback is welcome.

I will make it so the Window Report remembers it's window state.

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remember Last Window Settings](https://trello.com/c/J213LK9w/36-remember-last-window-settings)

**Comment by mzomparelli** [comment]
It's not perfect yet, but you can start using the window state saving feature now.

https://zomp.co/files.aspx?id=zvd

**Comment by mzomparelli** [comment]
version 1.0.70 has been released.
