### ISSUE TITLE
Desktop switch Animation problem

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#119]
If I check the "Show Desktop switch Animation", I notice that I have to scroll my mouse wheel several "steps" in order to actually trigger a desktop switch. Sometime just on extra turn does the trick. other times I need to do 3-4 extra turns on the mouse wheel to get zVD to jump into action.
I also noticed that after the first mouse-wheel turn, focus is moved away from my active window, but that seems to be all that happens (I haven't been able to figure out where the focus goes).

Also, I must admit that I didn't know what kind of "animations" to expect.  :-)

**Comment by mzomparelli** [comment]
What is your hotkey for this? I just tested with CTRL+MOUSE_TASKBAR_SCROLL and it worked every time with a single scroll.

**Comment by oywino** [comment]
Sorry, I don't understand your question. I didn't know that there was a special hotkey combination required for "Desktop switch Animation"

**Comment by mzomparelli** [comment]
No, there isn't. I'm asking for the hotkey you have setup that navigates desktop via mouse scroll. I tested and was not able to reproduce so I was asking for your setup because what I tested may be different.

**Comment by oywino** [comment]
CTRL+WIN+MOUSE-ANYWHERE-SCROLL-UP  and CTRL+WIN+MOUSE-ANYWHERE-SCROLL-DOWN

**Comment by mzomparelli** [comment]
I just tested with the same hotkey you have setup and I cannot reproduce the issue. Does this issue persist for you after rebooting your computer?

**Comment by oywino** [comment]
I'll let you know as soon as I've had the chance to reboot. Right now there's too much going on to close up.
Observe though that deselcting "Show Desktop switch Animation" fixed it and brought me back to safe grounds.

**Comment by mzomparelli** [comment]
This issue is related to what users are experiencing in this issue 
https://github.com/mzomparelli/zVirtualDesktop/issues/114

**Comment by mzomparelli** [comment]
We figured out that you don't want this feature and turning it off resolves your issues. I think this can be closed now. I will continue to look into this bug and report my findings in the other thread.
