### ISSUE TITLE
What's the difference between a pinned app and pinned window?

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#12]
As the title says - I fail to understand the difference.
I tried both, and what it did was to spread the current active window/App across all desktops.
I assume there must be a logical difference, but I couldn't figure it out.

**Comment by mzomparelli** [comment]
An easy way to imagine this is if you use pin window on a chrome browser window, only that window will be visible on all desktops. Any other chrome windows would stay on a single desktop. If you were to pin application on a chrome window then all chrome windows would show up on all desktops. This includes new chrome windows.

**Comment by mnsc** [comment]
This should be on the readme. Great functionality but I didn't get how it worked, especially this difference, at first.

**Comment by mzomparelli** [comment]
Thanks for the feedback. I will update the readme.

**Comment by mzomparelli** [comment]
I added this to the readme.
