### ISSUE TITLE
Window bar flashing rapidly 5-10 times 

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#120]
Hi, I thought I'd report a new issue while it's still appearing:
After installing AeroRainbow (a utility that matches the color of the active window's menu bar to each zVD wallpaper), I noticed that the bar of the active window flashes rapidly 5-10 times every time I move to another desktop. (This happens of course only on the arrival desktop).
AeroRainbow only does it's thing (color matching) on the active window. All other (inactive) windows have the default uncolored (white) menu bar.  So, if focus is taken away from the active window (i.e. if I click on the desktop itself) before I change desktop, then this annoying flickering is invisible (flickering between white and white)
This problem does not appear if I use the regular Windows desktop switching. Only with zVD.
It may well be an AeroRainbow bug, but I was hoping you could fix this. It looks like zVD flips focus on/off on the active window, and AeroRainbow tries desperately to keep up....?
I really like the feature offered by AeroRainbow. It is incredibly aesthetically unappealing when the color of the window bar is totally incompatible with the dominant color of the current wallpaper.  Aesthetics means a lot to me.  :)

**Comment by mzomparelli** [comment]
I understand what you are referring to and yes I am changing focus in order to deal with another bug. I'll install AeroRainbow so I can try and solve this problem.

**Comment by oywino** [comment]
Excellent! You're my man! :)

**Comment by mzomparelli** [comment]
I see what you mean. It is AeroRainbow that appears to be figuring out which color to use. It's locking up my explorer for a minute too. I don't think I can do anything about this and you'll have to report it to those guys that created AeroRainbow.

**Comment by oywino** [comment]
This looks like a potential entry into a ping-pong game.  I'm not ready for that :)
I think I'll just live with things as they are.  The advantages outweighs the trouble.....
Thanks for trying :)

**Comment by mzomparelli** [comment]
The taskbar flashed for me when zVD was not running. I kind of like the program too so let me do more testing and I'll try figure a way to work with Winaero on it.

**Comment by oywino** [comment]
That's strange - I never noticed the Window Title Bar (I'm **not** referring to the Taskbar) flashing unless when AeroRainbow was running concurrently with zVD.
I thought perhaps if you would consider applying such a feature natively to zVD, it could make AeroRainbow superfluous altogether.....

**Comment by mzomparelli** [comment]
Send me a screenshot of the configuration you are using with AeroRainbow. I'll see what I can do about performing the same functionality while I'm testing more.

**Comment by oywino** [comment]
Here is the screen dump https://i.imgur.com/kGUSWQ4.jpg
And the AeroRainbow INI file contains the following:
[general]
updates=1
instance=1
interval=100
trayicon=1
WindowIconColor=0
ColorCalcMode=1
ColorIntensity=37
win10taskbar=0
ColorMode=2

**Comment by mzomparelli** [comment]
Continued here...
https://github.com/mzomparelli/zVirtualDesktop/issues/165
