### ISSUE TITLE
list of features/functions (or main functions)

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [mzomparelli/zVirtualDesktop#122]
a short list based on the responses and what i understand:

**you can have mutiple copies of a software/app across mutiple virtual desktops**

* 'If you use the desktop version of OneNote then you can have multiple instances open at once and have them on different desktops'

**you can stick/pin a software/app so the same windows shows up across mutiple virtual desktops**

* Alternatively, you could just pin your OneNote window so that it is visible on any desktop you are on.

**dunno**

* you possibly can go from the last desktop (say it was the 10th desktop) to the first desktop --
 without having to go all the way left -- you can just go from the 10th desktop to the 1st by going right

* something something about round robin... this is possibly a bird (tho does not look like one) -- https://imgur.com/a/cebp5

---

eventually you want a clean list so you can just link it to anyone -- without having to say anything else

im likely going to go to mac eventually tho im not sure how im going to get used to the extra step and what seems to be less good/simple in mac's way of switching 'windows' and 'desktops'... i dunno been wanting a new os entirely, but it ain't gonna happen anytime soon until AR and VR gets more progressed

https://www.desktopneo.com

* https://vimeo.com/67076984

* https://vimeo.com/115154289

**Comment by mzomparelli** [comment]
I like Windows 10, but if they went with an interface like desktopneo then I would have to stop using it. I like having a mouse and keyboard.

Even though I love my iPhone, I can't stand Apple's desktop OS. Probably a lot to do with having used Windows for so long and being accustomed to it.

**Comment by mzomparelli** [comment]
The term round-robin can be visualized as a circle. Desktops would occupy equal space around the circle. Essentially, going one direction could get to the same destination as going the other direction. So being on desktop "5" and there is no 6 so going the direction of where 6 would be would take you to the beginning, "1".

**Comment by mzomparelli** [comment]
@SolveAllProblemsRightNow I have a problem for you to solve...how do I replace the default TaskView icon with one that is an icon like zVD system tray?
