### ISSUE TITLE
Use color for wallpaper

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#123]
Testing this out guys. Let me know what you think.

Use RGB or HTML hex code.

![image](https://user-images.githubusercontent.com/10564234/32703320-a980c0aa-c7b9-11e7-9adc-0e3d7b9b1459.png)

https://zomp.co/files.aspx?id=zvd

**Comment by mzomparelli** [comment]
A good program for finding colors

http://www.blacksunsoftware.com/colormania.html

**Comment by nicolasdejong** [comment]
I like the idea, but while this is ok for developer who dream in hex, for the average user this is probably too difficult. I'd suggest a matrix of rectangles for each desktop that show either a color or an image, and when clicked upon, the bottom part of the panel should provide configuration options for that desktop with a pill-button to switch between image and color. When the 'type' is color, provide a dialog find a nice color. When the 'type' is image, provide a browser button to browse for an image.

The coming two days I'm really busy, but after that I'll build a mockup using web-tech (which is my specialty), as an example.

**Comment by mzomparelli** [comment]
I like your idea. I was just going to prompt the use if they wanted a color or image when they pressed the browse button. Your idea is much better.

**Comment by mzomparelli** [comment]
Calling this resolved, but expect changes for the better in the future.
