### ISSUE TITLE
Does it bother you that I'm implementing features that have no relevance to virtual desktops?

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#127]
Being able to create any hotkey enables a lot of cool stuff. I'm adding stuff that helps me with my day job and this way I don't have to run multiple apps. I feel like I'm doing a good job bringing in these additional features, but would like to know if it bothers anyone. Please let me know how you feel about these two features  being part of zVirtualDesktop:

-Window Timers
-ClipboardEx

**Comment by nicolasdejong** [comment]
As long as that stuff can be switched off, I see no problems with it.

Then again, this application is 'window management' related. If you start adding features to it that have no relation with it whatsoever, it will dilute the story it tells: what am I downloading and installing?

**Comment by fluffynuts** [comment]
same as @nicolasdejong - as long as I can turn off the stuff I don't want (and there's no impact on performance or desktop functionality by doing so), it's all good. For instance, personally, I _really_ don't want window timers -- but I don't have to have them enabled (:
