### ISSUE TITLE
Maintain focus on moved Apps

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#13]
When I move&follow an App/Window, I must always re-focus (click inside it) in order to continue working with it. Like if I am typing in Word and decide to move&follow it to another desktop. Then typing away as usual does nothing. I have to clik first to re-activate focus. Then I can type again.
Can it be fixed so that focus also follows the windows/App?

**Comment by mzomparelli** [comment]
This is fixed v1.0.6. I'll publish it very soon.
