### ISSUE TITLE
Global window titlebar menu for window actions

### ISSUE THREAD

**Issue by fluffynuts** [mzomparelli/zVirtualDesktop#130]
One of the features I miss from VirtuaWin and *nix desktops is the menu I can get from middle-clicking a window's titlebar. From this menu, I can move windows to another desktop, pin them, or keep them above others.

Personally, I find this more convenient than the desktop view or hotkeys that I have to remember.

This could be implemented by hooking into the window icon menu or as a separate menu raised with, eg, middle-click on the titlebar -- I'm not fussy about where it happens. It's just a common feature I'm used to from other environments.

**Comment by mzomparelli** [comment]
I like this idea. When I implement it I will do so as a hotkey action. Middle click was recently added as a hotkey option so it could work exactly as you describe.

I think I want to do this as my own menu instead of having to hook into and add to the window context menu. In doing so, I would implement as a dark gray menu like the new menus in Windows 10 and like the zVD system tray menu.

All the functionality is there. I just need the menu.

**Comment by fluffynuts** [comment]
I don't know if it conflicts with the existing hotkey behavior, but I'd specifically want middle-click to bring this menu up _only_ when I'm middle-clicking the title-bar. I use middle-click to interact with application content (most especially links in browsers) so it would be quite frustrating to have to pick one or the other. Would it be possible to constrain the hook to operate only on the title-bar, please?

**Comment by mzomparelli** [comment]
Yep, I should be able to do that. The hotkey would be something like `MOUSE-WINDOWCAPTION-MIDDLE-CLICK` and would only apply to the foreground window.

Would work like this - https://github.com/mzomparelli/zVirtualDesktop/issues/80 - in reference to the Volume control part

**Comment by mzomparelli** [comment]
Halfway there...I've implemented more mouse key options. Here is the full list.

MOUSE-TASKBAR-SCROLL-DOWN
MOUSE-TASKBAR-SCROLL-UP
MOUSE-ANYWHERE-SCROLL-DOWN
MOUSE-ANYWHERE-SCROLL-UP
**MOUSE-FOREGROUND-CAPTION-SCROLL-DOWN
MOUSE-FOREGROUND-CAPTION-SCROLL-UP**
MOUSE-ANYWHERE-LEFT-CLICK
MOUSE-ANYWHERE-RIGHT-CLICK
MOUSE-ANYWHERE-MIDDLE-CLICK
MOUSE-TASKBAR-LEFT-CLICK
MOUSE-TASKBAR-RIGHT-CLICK
MOUSE-TASKBAR-MIDDLE-CLICK
**MOUSE-FOREGROUND-CAPTION-LEFT-CLICK
MOUSE-FOREGROUND-CAPTION-RIGHT-CLICK
MOUSE-FOREGROUND-CAPTION-MIDDLE-CLICK**

**Comment by mzomparelli** [comment]
My `Window` class makes things like this really easy and clean.

```
if (Window.Taskbar().IsMouseOver() || 
    Window.Taskbar2().IsMouseOver())
    {
          if (mouseEventExtArgs.Button == MouseButtons.Left)
          {
                keyCombination = keyCombination + "+MOUSE-TASKBAR-LEFT-CLICK";
          }
          else if (mouseEventExtArgs.Button == MouseButtons.Right)
          {
                 keyCombination = keyCombination + "+MOUSE-TASKBAR-RIGHT-CLICK";
          }
          else if (mouseEventExtArgs.Button == MouseButtons.Middle)
          {
                 keyCombination = keyCombination + "+MOUSE-TASKBAR-MIDDLE-CLICK";
           }
     }

if (Window.ForegroundWindow().IsMouseOverCaptionBar() && 
    Window.Taskbar().IsForegroundWindow == false && 
    Window.Taskbar2().IsForegroundWindow == false)
    {
           if (mouseEventExtArgs.Button == MouseButtons.Left)
           {
                 keyCombination2 = keyCombination2 + "+MOUSE-FOREGROUND-CAPTION-LEFT-CLICK";
           }
           else if (mouseEventExtArgs.Button == MouseButtons.Right)
           {
                 keyCombination2 = keyCombination2 + "+MOUSE-FOREGROUND-CAPTION-RIGHT-CLICK";
           }
           else if (mouseEventExtArgs.Button == MouseButtons.Middle)
           {
                 keyCombination2 = keyCombination2 + "+MOUSE-FOREGROUND-CAPTION-MIDDLE-CLICK";
           }
     }
```

EDIT: made it cleaner :)

**Comment by mzomparelli** [comment]
Almost there... we now have a menu. Unfortunately, the menu items are not functional yet. Just testing.

![image](https://user-images.githubusercontent.com/10564234/33032786-e89f5240-cde7-11e7-886f-e360e8569936.png)

**Comment by mzomparelli** [comment]
It's now fully functional...

![image](https://user-images.githubusercontent.com/10564234/33034582-e4e3e570-cded-11e7-9ae2-ed86a9736752.png)

**Comment by mzomparelli** [comment]
This is how you'd want to set it up

![image](https://user-images.githubusercontent.com/10564234/33035462-bd57598a-cdf0-11e7-9abf-d15ebfc2b2b2.png)

**Comment by fluffynuts** [comment]
Cool, but...

I set up my hotkeys as per your image above -- and I'm not getting the menu. I've saved the hotkey and "Applied" settings, but no go.

Also some suggestions, from having worked through this:

1) Please order the "Hotkey Action" drop-down on the dialog -- it was a bit of a mission to find "Show Window Menu"
2) I'd like to boldly propose that this becomes one of the default hotkeys. Middle-click on a window caption doesn't usually do something else and this is quite a popular interaction with other desktop environments.

**Comment by mzomparelli** [comment]
make sure you have the mouse hook enabled. Hotkeys using a mouse key will not work unless the mouse hook is on.

![image](https://user-images.githubusercontent.com/10564234/33072281-7028cb3c-ce84-11e7-92f3-c15d6939436b.png)

**Comment by mzomparelli** [comment]
As far as defaulting the key. I actually prefer a standard hotkey to bring up the menu. I use WIN+Z and the menu pops up where my mouse is. Another reason I shouldn't default a hotkey that uses a mouse key is that it requires the mouse hook be on and the mouse hook give some users mouse lag.

**Comment by mzomparelli** [comment]
If I sort the hotkey action list alphabetically then alike functions may not be next to each other. Maybe sort in Excel and show me how you would like to see the hotkey action list.

**Comment by fluffynuts** [comment]
I didn't even realise that the functions were grouped. I'd suggest either just a plain alphabetical sorting (which makes it easy to scan for a known function) or having the drop-down group functions, with some kind of group header, and within those groups, have the functions sorted alphabetically. Kind of like an html `optgroup`: [https://www.w3schools.com/TAGs/tryit.asp?filename=tryhtml_optgroup](https://www.w3schools.com/TAGs/tryit.asp?filename=tryhtml_optgroup)

Personally, I'd prefer the plain alphabetical sorting, but I understand that you have a plan with grouping -- so it would be clearer as a user who doesn't know about these groups if they were made visible to the user.

**Comment by mzomparelli** [comment]
Grouping is something I want to add tot he list, but that's more difficult in WinForms than it is in WPF or HTML. I do agree that it needs to be organized better. Maybe I'll make two dropdowns. One to select a group and another for the action.

Did you get the menu to pop up after enabling the mouse hook? If so, do you like it?

**Comment by fluffynuts** [comment]
Sorry, haven't had a chance to check this and I'm @ home now, in a sane environment (gentoo). I'll update tomorrow ^_^

**Comment by fluffynuts** [comment]
Aha, enabling the mouse hook sorted this out (: Thanks for the useful menu!

**Comment by fluffynuts** [comment]
Just a note: this interaction can be a little fiddly in browsers, particularly FireFox, where the "window titlebar area" is not at all explicit, with tabs running all the way to the top of the window (Chrome leaves a little space when not maximised, but suffers a similar fate when maximised). There's a "magic area" near the top of a tab which causes the middle-click-on-titlebar mouse hook to fire, and there's a part of the tab which doesn't cause this to fire, making the browser take the middle-click (and close the tab).

It would be very nice for the user if there was a way to inspect this at your side and only invoke the middle-click hook when not over a tab. It won't be at all trivial though, I expect.

**Comment by mzomparelli** [comment]
what does middle-click do for a browser tab? I'm trying to understand why you need this...couldn't you just right or left click on a browser tab?

Try setting up the menu to show for a regular hotkey like WIN+Z. It will then show the menu at your mouse location.

EDIT: I see that the middle click is causing the tab to be closed for you because the hit zone does not cover the full height of the tab. This can be tricky to solve since each window is different.

**Comment by fluffynuts** [comment]
Middle click is a fairly universal "close tab" binding, even in apps like ConEmu, for example. I use it to close tabs (: just that browsers these days tend to try to shove their tabs into the title-bar. So the middle click binding you've provided works fine, just that I wish i could still close tabs with a middle click (which I can if I hit the very bottom of a tab) 
I like this way to close because the close buttons on tabs can be hard to hit. 
Still, as I said above, I don't think this is easy to accomplish - it just would be nice to have. You really don't have to do anything about it (:

Perhaps I'll end up using a key binding for the menu like you do. Or perhaps I'll just retrain myself to close tabs one of the other ways (:

**Comment by mzomparelli** [comment]
You could set your hotkey to WIN+Caption-Middle-Click that way the middle click still works. 

EDIT: I didn't know that middle click closes tabs. The hotkey in chrome says CTRL+W, but I just tested and middle click closes Chrome tab too.

**Comment by fluffynuts** [comment]
Yeah, it's a very common "close tab" binding, in pretty-much every app that I know that has tabs.

Bear in mind that the reason I want something like zVD is to provide a "close as possible unified experience" across my different machines. I use some variant of Linux at home (was Debian for around 16 years, now Gentoo for around a year and a bit), and Windows at work. I try to make the environments as unjarring to move between as possible. Which makes me think -- I should see how right mouse-button works (considering that there's the icon RMB menu), since that's what KDE uses. I've been used to middle-mouse-button on windows because that's what VirtuaWin provided, but you've provided a way that I can actually unify _better_. So I'll give that a go tomorrow when I'm back at work (:

Thanks for the time you've spent on the feature (and all the others). I still wish the code was open-sourced so (a) I could learn and (b) I could contribute.

**Comment by fluffynuts** [comment]
btw, the middle-click-to-close-tabs function is something that I would sorely miss because gesture addons for FF and Chrome can't interfere with certain tab types (eg, on FF, gestures can't work on about:addons or on the mozilla addons page, for security reasons). This is why I've trained myself to use the middle mouse button to close tabs -- otherwise I normally do a "down/right" gesture (:

**Comment by mzomparelli** [comment]
@fluffynuts I've been working on this more and I've corrected some bugs. You might want to force an update.

**Comment by fluffynuts** [comment]
I've forced an update -- anything in particular I should notice?

**Comment by fluffynuts** [comment]
Hi, me again (:

Please could you disable this for fullscreen apps, or at least for fullscreen RDP -- I'm getting the overlay menu when remoted in to a work machine where I have no zVD. It's very confusing (:

**Comment by mzomparelli** [comment]
Yes, I should be able to prevent it for certain apps or full screen.

A few things that changed:
-When the menu is brought up it use the Window underneath the cursor even if that window is not focused
-Different menu when over desktop or Taskbar
-Add some additional menu items
