### ISSUE TITLE
Settings suggestion: show wallpapers

### ISSUE THREAD

**Issue by nicolasdejong** [mzomparelli/zVirtualDesktop#134]
In the now closed #123 (Color for Wallpaper) I promised a mockup of a suggestion of how the wallpapers configuration could look like.  A bit later than I hoped (12 days...) before I had some time left to spend on this, so here:

![image](https://user-images.githubusercontent.com/12181216/33222402-2c86f1d0-d157-11e7-943f-f6a26395a4e0.png)

Suggestion is to show the wallpapers (and tray icons as well) so it is easier to spot what image or color is the current setting. That is easier for non-dev users (and for devs as well ;-).

The mockup is a bit interactive and can be found here:

https://rutilo.nl/experiments/zVirtualDesktopSettings.html

While working on this I figured I might as well have a few more suggestions on the settings. If you don't use any of it that's fine. Just food for thought:

https://rutilo.nl/experiments/zVirtualDesktopSettingsAlt.html

Virtual desktops is the main reason to run this app, so I put its configuration on top.
I ordered the settings from most used to less used, generally (although location of 'hotkeys' is debatable)
"DesktopViews" was renamed to "Desktops List"
"Icon Theme" was renamed to "Tray"
The desktop names are now set in the 'Desktops" tab.

**Comment by mzomparelli** [comment]
This is really good in both the design and the mockup. What are you using to build these mockups?

I really like this and I'll try to get as close as I can to it.

**Comment by nicolasdejong** [comment]
It's plain html, css and javascript. I'm playing a bit with building simple apps without libraries like Angular or Aurelia. Turns out the current browser API is powerful enough to do these apps without too much effort. Glad you like it.

**Comment by mzomparelli** [comment]
Can I get your reasoning why desktop 1 is lower left instead of upper left? I know this matches the NumPad, but isn't it more intuitive for 1 to be in the upper left?

**Comment by nicolasdejong** [comment]
Yes, you have a point there. My mental model of the virtual desktops is in this order because I always use the numpad to switch to that desktop. The tray icon I use reflects that (numpad - white). Others might find that order confusing, so top-to-bottom might be more intuitive for them.

**Comment by mzomparelli** [comment]
I noticed that the Numpad tray icons display badly for me on my resolution. Are you having this issue too?
I plan on fixing this at some point. I just need to create one more size for those icons.

My display resolution:
2560x1080

![image](https://user-images.githubusercontent.com/10564234/33223011-7bd21fc0-d121-11e7-85eb-8252b9cea78e.png)

**Comment by nicolasdejong** [comment]
Didn’t notice that. They’re pretty small for me anyway at 4096x2160. By the way, one of them did’t work for me so I left it black.

**Comment by mzomparelli** [comment]
It would be ideal for zVD icon to be in place of Task View icon just right of the start menu.

The "Round" icons are black and difficult to see. I'm going to remove that icon set.

**Comment by mzomparelli** [comment]
I'm about done with this. Just putting in some final tweaks.

![image](https://user-images.githubusercontent.com/10564234/33226136-3af1fc70-d14c-11e7-8579-157461134f82.png)

**Comment by mzomparelli** [comment]
@nicolasdejong Force an update and let me know what you think.

**Comment by nicolasdejong** [comment]
Awesome! That is a very quick implementation. I tried it and it works beautifully. Only thing I noticed that the desktop settings are stored after selecting a different desktop in the 'Desktops' tab. So I had to remember to do that before pressing 'Apply' or 'OK'.

This is so much better:

![image](https://user-images.githubusercontent.com/12181216/33233663-b7bbe770-d219-11e7-9e81-c3b43ef512d6.png)

Great work, thanks!

Oh, I tried how the 'name' would show by testing the overlay (that's where the name should show, right?) and it crashed in Overlay.Draw(Graphics g) on an 'emSize' value of 0 which apparently is not allowed for a font (Font..ctor(FontFamily family, Single emSize, FontStyle style). Perhaps my settings data is old.

**Comment by mzomparelli** [comment]
Thanks! I'll force the active desktop settings to save when clicking apply or OK.

As for the crash with the overlay, can you confirm that you don't have any blanks for zeros for any of the settings on the overlay tab?

![image](https://user-images.githubusercontent.com/10564234/33233752-abe1581a-d1e0-11e7-9deb-91ea4e64d9f0.png)

**Comment by nicolasdejong** [comment]
Hmm, can't reproduce it anymore. I just removed a lot of text because I now understand what happened. Some values were 0 but I changed them and then pressed 'Test the overlay' again. Now I found that I have to press 'Apply' or 'OK' first before the settings go into effect. Perhaps the 'test' button should use the current values instead of the applied settings.

**Comment by mzomparelli** [comment]
For now I will just have it save the settings. The overlay needs work and I keep putting it off. Maybe you can get me focused on it again with your awesome mock-ups :)

**Comment by nicolasdejong** [comment]
Hehe, who knows :-)

**Comment by mzomparelli** [comment]
I'm glad you like it and I'm very happy with the mock-ups you provided. I'm going to be implementing your design of the Tray icon selection as well. Thank you and keep the good ideas coming.
