### ISSUE TITLE
Lot's of good stuff

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#135]
I just updated to 1.0.71 and i am amazed at how much goodies you come up with :)
As usual - I just have to give some feedback:
1. Using the wallpaper as column background in Desktop View doesn't come out very well. The wallpaper is so dramatically distorted - it looks awful. How about snipping a column "somewhere" from the wallpaper that can be displayed without distortion (perhaps from the center of the wallpaper)?
2 I couldn't get the ClipboardEx Paste to work. I cloned a single word from Notepad to ClipboardEx 1 and it showed up both in the regular clipboard as well as in clipboardEx 1. Then I added a shortcut Alt+Ctrl+F1 to paste it back, but nothing gets pasted back into notepad.... But the shortcut is displayed on the left edge of ClipboardEx 1 so it is obviously registered....   A bug, or my usual fingertrouble?

**Comment by mzomparelli** [comment]
I'll see what I can do about the wallpaper display in DesktopView.

As far as the clipboard issue goes. I just tested with your key combinations and it worked. Keep in mind that pasting occurs to the foreground window. If you are still having issues then please post a screenshot of your ClipboardEx tab. Remove any personal stuff from your ClipboardEx before you create the screenshot.

EDIT:

**ClipboardEx functions:**

**-ClipboardEx Copy:** Copies the selected text or file directly into the specified ClipboardEx container
**-ClipboardEx Paste:** Pastes the contents of the specified ClipboardEx container into the current foreground window
**-ClipboardEx Clone:** Clones the Windows Clipboard to the specified ClipboardEx container.

**Comment by nicolasdejong** [comment]
Regarding the walloaper in the Desktops View, perhaps a nice creative solution is to show the part of the wallpaper the desktop represents like a see-through. So desktop 1 has x-offset 0, desktop 2 has x-offset 1x width/10, desktop 3 has x-offset 2x width/10, etc.

**Comment by oywino** [comment]
This a windows snip of my ClipboardEx (I changed the hotkeys just to rule out any potential conflicts).
Pasting the word "Test" into Notepad doesn't work.
[https://i.imgur.com/x9WwjiP.jpg](url)

**Comment by oywino** [comment]
This a windows snip of my ClipboardEx (I changed the hotkeys just to rule out any potential conflicts).
Pasting the word "Test" into Notepad doesn't work.
https://i.imgur.com/x9WwjiP.jpg

(Sorry - I didn't mean to close this - Don't know how to un-close)

**Comment by mzomparelli** [comment]
Looks like ALT can't be used by itself as a modifier. I'll look into that. Try adding another modifier to your paste key combination and let me know if that helps.

**Comment by mzomparelli** [comment]
For the wallpaper distortion issue https://github.com/mzomparelli/zVirtualDesktop/issues/136

Just separating so easier for me to manage.

**Comment by oywino** [comment]
I appears any combination containing Alt will fail. Any combination I've tried without Alt, works.

**Comment by mzomparelli** [comment]
Thanks for the feedback. I'll investigate the issue with the ALT key.
