### ISSUE TITLE
No more default backgrounds

### ISSUE THREAD

**Issue by buchmiller** [mzomparelli/zVirtualDesktop#137]
This was added in the 1.0.71 update. In the Desktop->Settings tab, I clicked on a few rectangles and they started turning grey. When I went to those desktops, the background had changed to a grey color. There is no way to undo this change and go back to using the default background image. If I try to change it using the built-in Windows 10 Settings->Background, it reverts back as soon as I change desktops. There should be an option to opt out of using custom backgrounds in zVirtualDesktop.

Side note: Those squares are numbered in telephone layout instead of number pad layout. Not important - just an observation.

**Comment by mzomparelli** [comment]
Thanks for thee feedback. I will correct this bug tonight.

As far as the numbering...I think it's more intuitive to go top to bottom, left to right.

**Comment by mzomparelli** [comment]
This is fixed. You can force an update using the button on the "More Settings" tab.

**Comment by buchmiller** [comment]
When I clicked the Force Update button, the loading bar stalled at 0 progress, then a popup appeared saying "The specified executable is not a valid application for this OS platform." Now I can't launch the program at all. :(

**Comment by buchmiller** [comment]
I also cannot access your website to download the program, but that could be a company firewall issue.

**Comment by mzomparelli** [comment]
Sorry, I just changed my ISP. Try again in a few minutes. Should be up soon.

**Comment by mzomparelli** [comment]
zomp.co is back up. You can force the update now.

**Comment by mzomparelli** [comment]
I'm having ISP issues so my site is down again. It sucks when people can't do the job they are paid for.

**Comment by buchmiller** [comment]
Okay, now that my DNS has resolved the site, I was able to download the newest version. My computer gave me trouble over the fact that it had an unknown publisher, but I was able to load it as Administrator. We'll see if that causes problems on startup.
The issue is fixed though, I can now use the Windows set desktop background.
