### ISSUE TITLE
Crashes if number of virtual desktops are > 9

### ISSUE THREAD

**Issue by dsp0105** [mzomparelli/zVirtualDesktop#138]
Crashes if number of virtual desktops are > 9

**Comment by mzomparelli** [comment]
What action were you performing before it crashed? Can you find the stack trace in you Windows Events?

**Comment by mzomparelli** [comment]
I have identified this crash as a result of the changes I did with the wallpapers. I should have this fixed tonight, but I can't publish updates until my server is back online. However, I will publish the update to my Dropbox where it can be downloaded using the main download link on the main GitHub page.

Below is the stack trace you would have seen in Windows Event Viewer for this crash.

```
Application: zVirtualDesktop.exe Framework Version: v4.0.30319 Description: 

The process was terminated due to an unhandled exception. 
Exception Info: System.ArgumentOutOfRangeException at 

System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource) at 
System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, 
PublicKeyToken=b77a5c561934e089]].get_Item(Int32) at 
zVirtualDesktop.frmMain.SetWallpaper(Int32) at 
zVirtualDesktop.Program+<>c__DisplayClass46_0.<VirtualDesktop_CurrentChanged3>b__0() at 
System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at 
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at 
System.Threading.ThreadHelper.ThreadStart()
```

**Comment by mzomparelli** [comment]
This is fixed. The updated exe can be grabbed from the following link;

https://www.dropbox.com/s/vsjs8ov69xjbcvy/zVirtualDesktop.zip?dl=1

**Comment by dsp0105** [comment]
Wow amazing customer service :)  Sorry I was swamped with work and didnt have this window open to notice the comments from you and get back earlier.

Read your story/blog, inspiring and I can relate totally!  Also it hit me hard, since I was carrying the nagging feeling of guilt of not donating before. 

Regarding why > 9 desktops, I agree I will be using 5-6 desktops every day in my work flow but I will have issues from previous week which might need attention sometimes, hence I keep them in separate desktops (may be 4 more desktops). 
I use Virtual desktops for fast context switching from one issue to other issue I am debugging, since all the windows, files, etc are open and I can concentrate on the real work.

Thanks for the awesome app!

**Comment by mzomparelli** [comment]
Thanks for the feedback! I hope you continue to use it. I'll do my best to make sure you have a great experience with zVirtualDesktop.

I want to point out that desktop backgrounds don't work past desktop 9, but other parts will handle it just fine. DesktopView can display more than 9, but things start to get tight. Too many desktops may actually cause DesktopView to crash the program, but I only see people doing that to test the limitation. Also, hotkeys can work for desktops > 9 when using the next and previous. It wouldn't be difficult to have the hotkey desktop number drop down to go beyond desktop 9 so I might do that. I just don't think people are regularly going over 9 desktops.

**Comment by dsp0105** [comment]
I dont use desktop backgrounds, I keep it as blue color (aka classic theme) to get maximum performance instead of eye candy. Also i like the clarity offered by plain background.

Agree with your limitation of hotkeys for > 9 dekstops, thats is an acceptable limitation. I dont use hotkeys usually, since i dont remember which desktop number corresponds to which work task I had opened in it, hence I switch to desktop view and then  select that dekstop. 
For common preassigned desktops like say desktop 1 is for general mail etc, then I do use hotkeys.

Agree with you regarding people will actively use <9 desktops, but would have inactive ones which they might want to bring back if needed, so how about this approach?

1. Have set number of desktops (say 4) to be displayed in the desktop view 
and 
2 . the rest of them hidden/minimized in a sidebar

That will offer the user the flexibility of having an active set of desktops and an inactive set of desktops.

Use case:
1. If user in on a laptop - then active he might want to reduce to 4 and inactive ones to 3
2. if user connected the laptop to a big monitor - the he might want to increase the active ones to 7 and make inactive ones to 0

Thanks for your fast feedback!

**Comment by mzomparelli** [comment]
Another great idea from you! I like the idea of being able to tell zVD which desktops to show in DesktopView. How do you envision setting that? Is it simply a setting where you type the maximum number to be displayed in DesktopView?

**Comment by dsp0105** [comment]
Thanks, they come from depths of frustrations :D 

I think for first cut, we can have number of active desktops = 4. 

This is also due to limitation of zVD where we can not change the order of desktops.  
I meant, lets say Desktop1 (General mail), Desktop(Issue1 debug). Then that order is fixed, I cant move Desktop 2 to Desktop1 position i.e., Desktop 1( Issue1 debug), Desktop2 (General mail)

For later, I think it would be useful to have a minimized sidebar which will contain inactive desktops.
The user can drag an active desktop into that sidebar to make that desktop inactive and vice-versa.
User can also move the desktop around in the desktop view - if that is not a hard task to do from development point of view.

**Comment by mzomparelli** [comment]
I think I'm seeing it!

The side bar can look like Window's default taskview (just the bottom row part) maybe displayed vertically in Desktop View. From there you could drag a desktop square into the larger container that shows the columns of thumbnails. I think I can do this.

**Comment by mzomparelli** [comment]
Let's keep this going in the new issue. Feel free to copy and paste your comments over there.

https://github.com/mzomparelli/zVirtualDesktop/issues/143

**Comment by dsp0105** [comment]
sure, thanks!
