### ISSUE TITLE
Option to change Font Size of Desktop Names

### ISSUE THREAD

**Issue by dsp0105** [mzomparelli/zVirtualDesktop#140]
Hi,

Can you please add the option to change the font size of desktop names so that I can decrease font size and give longer names for desktops with out getting clipped?

Thanks!

**Comment by mzomparelli** [comment]
Good idea! I'll do this.

**Comment by dsp0105** [comment]
Thank you :)

**Comment by mzomparelli** [comment]
This is implemented in the next version. I plan to publish in the next few days.

![image](https://user-images.githubusercontent.com/10564234/33800193-f2a06f5e-dd00-11e7-83b5-f610af5e7082.png)

**Comment by dsp0105** [comment]
Great! Thanks!

**Comment by dsp0105** [comment]
I tried it but it is not solving the purpose - which is to have more text for the desktop name,  it seems there is lot of padding (from all four sides) leading to very small amount of space left for the actual title. Can it be fixed if possible?

**Comment by mzomparelli** [comment]
It seems to work fine for me. Another thing you can try to get more text into the header is to increase the header height. On the settings window, Header Height is the setting directly above the Font Size setting.

Let me know if this helps.

**Comment by dsp0105** [comment]
Thanks, my bad, the padding went away/was minimal once I put in more text into the title. 
(I already was using increased Header Height to get more text into the title)
