### ISSUE TITLE
Website is down - I changed my ISP

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#141]
I'm having issues with my new ISP. They gave me a dynamic IP address and this is why my site is currently inaccessible.

I have switched the main download link to my Dropbox so that you can still download the EXE, but updating through the app will not work right now. This should be resolved within 48 hours.

**Comment by gwhittey23** [comment]
I clicked on the update menu item and box popup that sat there for awhile till closed it. It messed up the exe file so re-downloaded new one and it just starts in task bar but stops right away. Is there some registry setting I should delete that the app is using?

Edit - I searched registrey and deleted all mentions of the app and that allowed it to run

**Comment by mzomparelli** [comment]
A new one should work. Try executing it again.

**Comment by mzomparelli** [comment]
That's odd, no registry settings should stop this from working. I don't use the registry. Glad you got it working.

**Comment by mzomparelli** [comment]
zomp.co is back online

So, I switched from Comcast Xfinity to MetroNet. So far I'm satisfied with the internet that I receive. 
Here's the story behind what just happened with my server being down.

2 weeks ago a lady comes to my house offering me MetroNet service. I told her that I required an IP address that would not change because I am running web services. I used those exact words with her boss whom I had her call so that I could confirm that I would have a static IP address. I was assured.

Skip ahead two weeks to now (yesterday evening to be more specific), and my service is installed. The installer is nice, but not really too technical when it comes to software. Regular hardware guy. So I don't bring it up to him thinking I was ok because two people have assured me.

That night everything is working as planned. Somewhere in the middle of the night (GMT-6 Central Standard Time) MetroNet account configuration kicked in and put my connect through a NAT. This basically translates my IP address into another IP address making it impossible for me to receive incoming connections.

So, I call them this morning and tell them I need a static IP address and explain that I was assured I would have one. She told me that it would take 48 hours and I said please make it a priority. She said she is giving me a year of free static IP ($120 value). Up to this point I had no idea that I would be charged for a static IP. I thought I was already supposed to have it. I said thanks and please make it a priority.

Skipping to this evening as I'm driving home from work, I call again, this time I get a guy and I explain the story and how I called this morning. I tell him that I really need it tonight (I don't really need it at all ;]), and that I might have to switch back to Comcast. I said not only that, but that there is a hole in my house now from the installation that will have to be fixed due to an inaccurate description and offering of your services.

I get a call from an hour later from a technician. He provides me the details I need to plug into my router and quickly and easily configures their system so that the same details are associated to my account. It really is that simple for them, even though their sales people make it sound more complicated.

Was I wrong for pushing them to get it done now? You tell me.
