### ISSUE TITLE
Reset settings to default doesn't work

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#144]
The option "Reset settings to default" doesn't work.
The application stops working after clicking on that option.
After starting the application again, the settings are unchanged.
One must manually stop the application, then manually remove zVirtualDesktop_Settings.bin file from  C:\Users\username\AppData\Roaming\zVirtualDesktop directory in order to reset settings to default.

**Comment by mzomparelli** [comment]
Thanks for the feedback. I'm looking into this and will update accordingly.

**Comment by mzomparelli** [comment]
This is resolved in the next version. I should be publishing in a few days. Thanks for reporting the issue.
