### ISSUE TITLE
Alt-1, Alt-2,... Alt-X don't navigate to the Desktop

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#145]
I have changed the settings (please see my setting below) in order to use Alt-X key to navigate to desktops. But this change has no effect, pressing ALT-X doesn't work.
It started to work when I removed all "Move Window to Desktop #1 - ALT+WIN+NumPadX" entries from the configuration which were above, please see working settings below.

==== these settings don't work =====================
Navigate to Desktop #1 - CTRL+WIN+NumPad1
Navigate to Desktop #2 - CTRL+WIN+NumPad2
Navigate to Desktop #3 - CTRL+WIN+NumPad3
Navigate to Desktop #4 - CTRL+WIN+NumPad4
Navigate to Desktop #5 - CTRL+WIN+NumPad5
Navigate to Desktop #6 - CTRL+WIN+NumPad6
Navigate to Desktop #7 - CTRL+WIN+NumPad7
Navigate to Desktop #8 - CTRL+WIN+NumPad8
Navigate to Desktop #9 - CTRL+WIN+NumPad9
Move Window to Desktop #1 - ALT+WIN+NumPad1
Move Window to Desktop #2 - ALT+WIN+NumPad2
Move Window to Desktop #3 - ALT+WIN+NumPad3
Move Window to Desktop #4 - ALT+WIN+NumPad4
Move Window to Desktop #5 - ALT+WIN+NumPad5
Move Window to Desktop #6 - ALT+WIN+NumPad6
Move Window to Desktop #7 - ALT+WIN+NumPad7
Move Window to Desktop #8 - ALT+WIN+NumPad8
Move Window to Desktop #9 - ALT+WIN+NumPad9
Move Window to Desktop #1 & Follow - ALT+CTRL+WIN+NumPad1
Move Window to Desktop #2 & Follow - ALT+CTRL+WIN+NumPad2
Move Window to Desktop #3 & Follow - ALT+CTRL+WIN+NumPad3
Move Window to Desktop #4 & Follow - ALT+CTRL+WIN+NumPad4
Move Window to Desktop #5 & Follow - ALT+CTRL+WIN+NumPad5
Move Window to Desktop #6 & Follow - ALT+CTRL+WIN+NumPad6
Move Window to Desktop #7 & Follow - ALT+CTRL+WIN+NumPad7
Move Window to Desktop #8 & Follow - ALT+CTRL+WIN+NumPad8
Move Window to Desktop #9 & Follow - ALT+CTRL+WIN+NumPad9
Navigate to Desktop #1 - ALT+D1
Navigate to Desktop #2 - ALT+D2
Navigate to Desktop #3 - ALT+D3
Navigate to Desktop #4 - ALT+D4
Navigate to Desktop #5 - ALT+D5
Navigate to Desktop #6 - ALT+D6
Navigate to Desktop #7 - ALT+D7
Navigate to Desktop #8 - ALT+D8
Navigate to Desktop #9 - ALT+D9
Move Window to Desktop #1 - ALT+WIN+D1
Move Window to Desktop #2 - ALT+WIN+D2
Move Window to Desktop #3 - ALT+WIN+D3
Move Window to Desktop #4 - ALT+WIN+D4
Move Window to Desktop #5 - ALT+WIN+D5
Move Window to Desktop #6 - ALT+WIN+D6
Move Window to Desktop #7 - ALT+WIN+D7
Move Window to Desktop #8 - ALT+WIN+D8
Move Window to Desktop #9 - ALT+WIN+D9
Move Window to Desktop #1 & Follow - ALT+CTRL+WIN+D1
Move Window to Desktop #2 & Follow - ALT+CTRL+WIN+D2
Move Window to Desktop #3 & Follow - ALT+CTRL+WIN+D3
Move Window to Desktop #4 & Follow - ALT+CTRL+WIN+D4
Move Window to Desktop #5 & Follow - ALT+CTRL+WIN+D5
Move Window to Desktop #6 & Follow - ALT+CTRL+WIN+D6
Move Window to Desktop #7 & Follow - ALT+CTRL+WIN+D7
Move Window to Desktop #8 & Follow - ALT+CTRL+WIN+D8
Move Window to Desktop #9 & Follow - ALT+CTRL+WIN+D9
Move Window to Next Desktop - ALT+WIN+Arrow Right
Move Window to Next Desktop & Follow - ALT+CTRL+WIN+Arrow Right
Move Window to Previous Desktop - ALT+WIN+Arrow Left
Move Window to Previous Desktop & Follow - ALT+CTRL+WIN+Arrow Left
Pin/Unpin Window - ALT+WIN+ Z
Pin/Unpin Application - ALT+WIN+ A
Bring All Windows Here - ALT+WIN+ H
Open File: 'www.google.com' - ALT+CTRL+ G
Remove Empty Desktops - ALT+WIN+ R
Toggle Desktop View - WIN+Tab
Show Window Menu - WIN+Spacebar

====== working settings ==================
Move Window to Desktop #1 - ALT+WIN+NumPad1
Move Window to Desktop #2 - ALT+WIN+NumPad2
Move Window to Desktop #3 - ALT+WIN+NumPad3
Move Window to Desktop #4 - ALT+WIN+NumPad4
Move Window to Desktop #5 - ALT+WIN+NumPad5
Move Window to Desktop #6 - ALT+WIN+NumPad6
Move Window to Desktop #7 - ALT+WIN+NumPad7
Move Window to Desktop #8 - ALT+WIN+NumPad8
Move Window to Desktop #9 - ALT+WIN+NumPad9
Move Window to Desktop #1 & Follow - ALT+CTRL+WIN+NumPad1
Move Window to Desktop #2 & Follow - ALT+CTRL+WIN+NumPad2
Move Window to Desktop #3 & Follow - ALT+CTRL+WIN+NumPad3
Move Window to Desktop #4 & Follow - ALT+CTRL+WIN+NumPad4
Move Window to Desktop #5 & Follow - ALT+CTRL+WIN+NumPad5
Move Window to Desktop #6 & Follow - ALT+CTRL+WIN+NumPad6
Move Window to Desktop #7 & Follow - ALT+CTRL+WIN+NumPad7
Move Window to Desktop #8 & Follow - ALT+CTRL+WIN+NumPad8
Move Window to Desktop #9 & Follow - ALT+CTRL+WIN+NumPad9
Navigate to Desktop #1 - ALT+D1
Navigate to Desktop #2 - ALT+D2
Navigate to Desktop #3 - ALT+D3
Navigate to Desktop #4 - ALT+D4
Navigate to Desktop #5 - ALT+D5
Navigate to Desktop #6 - ALT+D6
Navigate to Desktop #7 - ALT+D7
Navigate to Desktop #8 - ALT+D8
Navigate to Desktop #9 - ALT+D9
Move Window to Desktop #1 - ALT+WIN+D1
Move Window to Desktop #2 - ALT+WIN+D2
Move Window to Desktop #3 - ALT+WIN+D3
Move Window to Desktop #4 - ALT+WIN+D4
Move Window to Desktop #5 - ALT+WIN+D5
Move Window to Desktop #6 - ALT+WIN+D6
Move Window to Desktop #7 - ALT+WIN+D7
Move Window to Desktop #8 - ALT+WIN+D8
Move Window to Desktop #9 - ALT+WIN+D9
Move Window to Desktop #1 & Follow - ALT+CTRL+WIN+D1
Move Window to Desktop #2 & Follow - ALT+CTRL+WIN+D2
Move Window to Desktop #3 & Follow - ALT+CTRL+WIN+D3
Move Window to Desktop #4 & Follow - ALT+CTRL+WIN+D4
Move Window to Desktop #5 & Follow - ALT+CTRL+WIN+D5
Move Window to Desktop #6 & Follow - ALT+CTRL+WIN+D6
Move Window to Desktop #7 & Follow - ALT+CTRL+WIN+D7
Move Window to Desktop #8 & Follow - ALT+CTRL+WIN+D8
Move Window to Desktop #9 & Follow - ALT+CTRL+WIN+D9
Move Window to Next Desktop - ALT+WIN+Arrow Right
Move Window to Next Desktop & Follow - ALT+CTRL+WIN+Arrow Right
Move Window to Previous Desktop - ALT+WIN+Arrow Left
Move Window to Previous Desktop & Follow - ALT+CTRL+WIN+Arrow Left
Pin/Unpin Window - ALT+WIN+ Z
Pin/Unpin Application - ALT+WIN+ A
Bring All Windows Here - ALT+WIN+ H
Open File: 'www.google.com' - ALT+CTRL+ G
Remove Empty Desktops - ALT+WIN+ R
Toggle Desktop View - WIN+Tab
Show Window Menu - WIN+Spacebar

**Comment by mzomparelli** [comment]
Thanks for the feedback again. I will confirm this and provide an update soon.

**Comment by mzomparelli** [comment]
So far I've been unable to reproduce an issue. I'll keep looking. Thanks for the feedback.
