### ISSUE TITLE
Opacity setting doesn't work

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#146]
The opacity setting (under "Overlay" tab) is labeled by "Opacity (0-100)" text.
Hovewer numbers between 0-100 don't have any effect.
Opactiy seems to work when I enter fractional numbers like 0,1  0,5  0,8 (note: I am using a comma as decimal point, when using a dot it doesn't work too. My windows is using Polish language settings where comma is used as decimal point).
Another issue is that when I enter a fractional number (like "0,4"), and then save settiing using OK button, and then go back to the "Overlay" tab, this 0,4 number is replaced by 85. If I accept this setting using OK or Apply button, then Opcacity stops working again.

**Comment by mzomparelli** [comment]
Thanks for the feedback. I'll look into this issue.

**Comment by mzomparelli** [comment]
This is fixed in the next version. I should be publishing in the next few days. You will still enter the opacity as a whole number between 0 and 100.

Thanks for reporting this issue.

The overlay is still a work in progress. Any additional feedback regarding the overlay is very much appreciated.
