### ISSUE TITLE
Crash when opening

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#147]
This happens about 50% of the time when I open the program. After it opens successfully though, it works fine.

Here is the debug error message Visual Studio gave me:

An unhandled exception of type 'System.InvalidOperationException' occurred in mscorlib.dll
Hashtable insert failed. Load factor too high. The most common cause is multiple threads writing to the Hashtable simultaneously.

**Comment by mzomparelli** [comment]
I’m out of town until Friday so I’ll look into this then. Sorry for the inconvenience.

**Comment by LexiRyedale** [comment]
I'm also seeing this, same error. Happens every time rather than 50% though. :( 
I'm on Windows build 17025.rs_prerelease.171020-1626.

**Comment by nicolasdejong** [comment]
Works fine for me.

You can try to remove (or rename) your settings file (while zVirtualDesktop is stopped) and see if it works from scratch. The file is %APPDATA%/zVirtualDesktop/zVirtualDesktop_Settings.bin.

If this issue happens only for new configurations, the above won't help. I'll attach my settings file, so you can try with that.

[zVirtualDesktop_Settings.zip](https://github.com/mzomparelli/zVirtualDesktop/files/1536819/zVirtualDesktop_Settings.zip)

(extract first. can't attach .bin files)

**Comment by LexiRyedale** [comment]
Yup, Replacing the setting file worked. <   scuttles away to re configure settings />

**Comment by mzomparelli** [comment]
Sorry you lost your settings. I'm going to investigate this weekend.

**Comment by ghost** [comment]
Replacing the settings file didn't work for me, even with an unmodified fresh settings file.

**Comment by mzomparelli** [comment]
This issue is resolved in the next version. I plan to publish in the next few days.

**Comment by LexiRyedale** [comment]
Thanks for your hard work!



On Sat, Dec 9, 2017 at 10:20 PM +0000, "Michael" <notifications@github.com<mailto:notifications@github.com>> wrote:


This issue is resolved in the next version. I plan to publish in the next few days.
