### ISSUE TITLE
Download links for older versions

### ISSUE THREAD

**Issue by dsp0105** [mzomparelli/zVirtualDesktop#149]
Could you please provide download links for older versions? I am seeing screen stutter and delay when switching apps with the latest version, I dont remember seeing it with previous version. I would like to debug more to see if it is because of ZVirtualDesktop or any other setting in my PC.

**Comment by mzomparelli** [comment]
I don't retain previous versions because I use source control. This allows me to revert back if needed. I'd like to help address this issue. Could you provide a video showing this issue occurring? Have you tried restarting your computer?

**Comment by mzomparelli** [comment]
Are you using the overlay when switching desktops? If so, disable it and let me know if the issues persist.

**Comment by dsp0105** [comment]
I dont use overlay, since I like speedy switching :)

Sorry, it was not a bug in zVirtualDesktop, but in Nvidia driver!! I updated and tried bunch of drivers but all were causing the issue. I removed the driver and it works fine :D

Also, I am confused since you merged threads, so just saying my idea here for an older issue.

I got a better idea regarding active and inactive desktops, how about providing user the option to minimize a desktop in DesktopView (I meant minimize it but it will show DekstopNumber or may be an minimized arrow). This is better in my opinion since user does not have to move around desktops to inactive side bar (my previous idea) and will preserve the Desktopnumber <--> Desktop name mapping in the *head of the user* . It is also similiar to what we do with inactive windows in Windows OS - we just minimize it. 

Please let me know, if this sounds better in clarity and in ease of execution.

**Comment by mzomparelli** [comment]
I'm currently working on something that sounds just like you are describing. It's still pretty early in development to say when I'll release it. Stay tuned. I still have some good ideas in my head.
