### ISSUE TITLE
Mouse Navigation - Using a minimum of clicks to jump desktops

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#15]
Let me first say thank you for making this utility and for letting us know about it. It's fantastic! :-)
Adding "Switch Desktop" to the icon right-click was a good idea. It saves us from having to move our hands over to the keyboard all time. But it still can't outperform the Windows built-in Task-View desktop switcher. Neither in number of clicks needed, nor in visual effects. So essentially, you just added something which is already available naitively.
The objective it to reduce the number of clicks to an absolute minimum.
Would it be possible to add a feature that would overlay a horisontal desktop ribbon similar to the one produced by right-clicking on Task-View, when you hover over the zDV icon?
(I guess with or without changing the rest of the desktop (like task-View does) until you click.
If that's not easily programmed, perhaps just a single row of digits from 1-n would could appear when hovering over the icon.

**Comment by mzomparelli** [comment]
Thanks for the feedback. I like your suggestion. I'll see what I can do about adding it.

**Comment by mzomparelli** [comment]
@oywino What if I make a double click or a single click of the system tray icon bring up the Task View page?

**Comment by oywino** [comment]
You mean - bring up the Windows Task-View page?
Just as if I had clicked the Windows Task-View icon instead?
No, that can't be what you have in mind (?)  
I mean, there are only a few real issues with the Windows standard Task-View feature as is. The main issue is that it is a bit overwhelming to be seen as a snappy and quick way to jump between Desktops.
You have created an elegant way to jump using the keyboard. What I'm looking for is a way to achieve the same snappy and elegant way using only the mouse.
So, essentially a way which is significantly snappier than using the Task-View icon which is already there.
The goal is; As few clicks as possible. As short mouse movements as possible (distance-wise). As few screen changes as possible (until the actual jump takes place).
So: hovering could bring up a row of small icons labelled 1-n, and on the next click (on the desired number), the jump takes place.
If the icon row 1-n appears just above the zVD System Tray Icon with the same size, look and feel, it would be a useful alternative to the more extensive and overwhelming Windows Task-View function.

**Comment by mzomparelli** [comment]
ok, I'm following what you're saying. I'll see what I can do.

**Comment by mzomparelli** [comment]
I'll admit that the "Switch Desktop" takes an extra click, but this app allows me to remove the Task View button from my taskbar. This frees up valuable taskbar real estate.

**Comment by oywino** [comment]
Oh, now I see. So by duplicating the Task-View, the gain for me as a user is that I can remove the Task-View!?
Well, that makes sense, not so much to save space, but to avoid having move the mouse between zVD and Task-View which happen to on the far opposite of my screen :-)
Let's do that and see how it turns out.

**Comment by mzomparelli** [comment]
You do realize there is a Windows hot key to open the task view, right? WIN+TAB

Which is a left-handed operation, but I do like the idea of opening the task view by clicking the zVD system tray icon.

**Comment by oywino** [comment]
I agree.... Then the objective here to evaluate if a feasible mouse-only alternative exists... :-)

**Comment by mzomparelli** [comment]
@oywino You can now click to open task view!

Only in the latest pre-release

https://github.com/mzomparelli/zVirtualDesktop/blob/master/zVirtualDesktop/bin/Release/zVirtualDesktop.zip?raw=true

**Comment by ghost** [comment]
Best way I've seen so far: Mouse wheel over the task bar switches to next/previous desktop. This is even easier than right click or a keyboard shortcut.

That's the easiest way I've seen so far in the various tools I tried ([virtual-desktop-enhancer.ahk](https://github.com/sdias/win-10-virtual-desktop-enhancer) had the scroll-to-switch-desktops feature). I didn't even know it had this feature until I triggered it by accident. Lucky oops!

**Comment by mzomparelli** [comment]
I will add this feature, but I personally dislike it. It's probably because I never switch one desktop at a time. I always go exactly where I need to go and Desktop View is my main way of switching now because it shows me where everything is and I can click any window and bring it up.

**Comment by oywino** [comment]
I kind of agree. It will be interesting to test though. Using mouseover on the taskbar instead of rightclicking an icon, is a good approach that never occurred to me. Just moving the mouse to an empty part of the taskbar today, does nothing in windows default. My next idea was to use that fact to automatically bring up a horisontal row of desktop thumbs (identical to the row you get when you press Win+Tab) without affecting the rest of the screen. And then have a framed highlight that scrolls left/right with the mouse wheel. Then leftclick to select.
