### ISSUE TITLE
Paypal not working

### ISSUE THREAD

**Issue by dsp0105** [mzomparelli/zVirtualDesktop#150]
I was planning to get a license, but seems Paypal or Credit card link is not working.

Appreciate the great tool! Keep up the good work :)

**Comment by mzomparelli** [comment]
Try restarting zVirtualDesktop to see if the link is fixed.  It seems ok on my side and I am currently logged into PayPal and their systems seems fine. Let me know. I'm just sitting here working on some of these bugs and watching Dr. House :)

**Comment by mzomparelli** [comment]
Purchasing entitles you to all future updates. You will never be asked to pay unless you require more than 3 computers.

**Comment by dsp0105** [comment]
Love House! Restarting app worked, now it can connect to Paypal, but now the purchase option is stuck at 3 computers :|

**Comment by mzomparelli** [comment]
I just updated it again. It meant to say $40. I did narrow it to just the one option though so that's not a bug. You could share your key code with your friends and family.

I was looking at other programs and noticed they just had one charge for 3 computers and that seemed easier for me. I may bring back the multiple options.

**Comment by dsp0105** [comment]
Oh, 40$ seems too steep and also since I need for only one computer.

**Comment by mzomparelli** [comment]
I'm never going to ask for anything else from you and I will promptly address issues you experience while using the program. Nonetheless, I will take your feedback into consideration.

**Comment by dsp0105** [comment]
Appreciate your support but charging for 3 computers is going to raise it for folks who need it on 1 computer, just my thoughts.

**Comment by mzomparelli** [comment]
Thank you for your feedback. I completely understand your position and will take this into consideration while I evaluate the price.

**Comment by mzomparelli** [comment]
You may now choose a 1 computer option again.
