### ISSUE TITLE
About page does not show activation info

### ISSUE THREAD

**Issue by dsp0105** [mzomparelli/zVirtualDesktop#151]
I just bought the license and then I entered the Key code, it said it will close and asked me to restart. I restarted the app, but the "about page" is not showing any activation info...
It might be a non-issue per se but having about page showing activation info would be helpful.

Thanks!

**Comment by mzomparelli** [comment]
Sorry for the confusion.

Using the key code will only register the computer. To see the "Account Details" page, you will need to log in using the credentials that are in the same email as the key code.

I did confirm that your computer has been registered so you don't need to do anything else unless you need to transfer the license to another computer.

**Comment by mzomparelli** [comment]
You are correct that it should still show you that the computer is registered. I will work on that. Thanks for the feedback.

**Comment by dsp0105** [comment]
Thanks!
