### ISSUE TITLE
Minimal bug: desktops overview does not close on switching desktop

### ISSUE THREAD

**Issue by nicolasdejong** [mzomparelli/zVirtualDesktop#152]
Just a small detail. I noticed when switching to a different virtual desktop that the desktops overview stays open on the virtual desktop it opened on. If I then switch back, it is still there. If I don't switch back but try to open the overview, it doesn't work (immediately).

I think it is better to close the overview when switching away from it, to avoid confusion.

(initially this happened because of the (annoying!) Windows bug that shows icons of applications that exist on a different desktop, and which moves to that desktop when clicked on it).

**Comment by mzomparelli** [comment]
Thanks for the feedback. I will look into this tonight.

**Comment by mzomparelli** [comment]
This has been fixed and code has been published without a version increment. I'm working out other bugs and enhancements before releasing an official version.

**Comment by mzomparelli** [comment]
The fix for this is in version 1.0.77
