### ISSUE TITLE
"zVirtualDesktop is already running"

### ISSUE THREAD

**Issue by CJS-Design** [mzomparelli/zVirtualDesktop#154]
![image](https://user-images.githubusercontent.com/509612/34070485-8af598f4-e267-11e7-9922-985cbb97ac58.png)

I cannot find it in the Task Manger (checked at least ten times, just right now again, after several reboots and so on).

What changed is the recent 90minutes upgrade of Windows.

![image](https://user-images.githubusercontent.com/509612/34070499-c7bd22c0-e267-11e7-9402-9bc9b9ce82de.png)

I have no Idea how to proceed, since I cannot uninstall? I do not have it in the Autostart Folders (started it manually until now).

Thanks for a great utility, I hope I can use it soon again :)

**Comment by nicolasdejong** [comment]
The process is not called “zVirtualDesktops”, but “Michael Zomparelli - zVirtualDesktops”. So if you look at the ‘M’, you’ll find it.

I guess he wants to make sure people don’t forget who wrote this piece of software :-)

(By the way, there is nothing to uninstall since it doesn’t come with an installer — one of the things I like about it)

**Comment by CJS-Design** [comment]
Thanks for your answer. I actually looked for both process names and forgot to write that. Still nothing.

(And yes, I like that too. )

**Comment by mzomparelli** [comment]
The process name is zVirtualDesktop.exe. Only the description has my name in it. Kill it from the Details tab in Task Manager.



![image](https://user-images.githubusercontent.com/10564234/34072231-030c8e02-e249-11e7-9132-42d1e430e7b0.png)

![image](https://user-images.githubusercontent.com/10564234/34072238-2078e684-e249-11e7-993b-be320f589dfc.png)

**Comment by mzomparelli** [comment]
I think having my name on it makes it more trustworthy. If this program was malicious then that would be a silly thing to do. And yes, it's also so you know who made the app.

**Comment by mzomparelli** [comment]
Do you have the icon in the system tray? If it's truly running then it should be there. If there then you should be able to right-click the system tray icon and choose exit.

A PC reboot should have solved the issue for you unless you have it auto-starting from somewhere.

**Comment by CJS-Design** [comment]
I neither have the process in the details tab nor the system tray icon.
Rebooting did not solve it.

I guessed it must be in Autostart somewhere but in all the places I know of that autostart something I cant find it in.

So, yeah, at the moment I am either overlooking something or I am screwed. :(
Probably, like 99% of the times in this cases, I am overlooking something very dumb.

**Comment by mzomparelli** [comment]
If it's not in Task Manager then it's not running. Would you mind downloading Team Viewer to allow me to help you. Send me an email at zVirtualDesktop@gmail.com

**Comment by CJS-Design** [comment]
Thanks for your offer. Right now I have to run home to my kids. I have teamviewer installed, so that is not the problem. I will send you an email later today or tomorrow. Thanks again for your fast response and help.

**Comment by mzomparelli** [comment]
No problem. I want to make sure you have the best experience and it does not sound like a good experience right now so I want to help you resolve it.

**Comment by CJS-Design** [comment]
Sorry for not writing earlier. 
I have used https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer to check my processes - no zVirtualDesktop is there. So somehow my system is screwed.

I also went trough the registry searching for all instances of zVirtualDesktop - deleted a few but nothing that seemed like it could influence this. One more restart and I am out of ideas.

**Comment by mzomparelli** [comment]
Process Explorer is a good tool and if you don't see it there then I believe you. I'm not sure what would be causing this for you. I could remove this check for you and send you a custom exe, but updating would bring the issue back for you.

Try downloading it again to see if that helps. We'll try that first and move on to another solution if this doesn't help.

https://zomp.co/Files.aspx?id=zVD

**Comment by CJS-Design** [comment]
I feel kinda dumb now: Redownloading worked.

Thanks for your help!

**Comment by mzomparelli** [comment]
I usually try the simplest solution first. Rebooting...that's why all IT guys will ask if you have restarted. That alone fixes a lot of issues. If it's a downloaded file then IT guys will ask if you have tried re-downloading the file. Those two things can quickly close tickets,

**Comment by CJS-Design** [comment]
Yeah, i worked in a IT Hotline of a global company. But with exe running directly from a downloaded folder I suspected the file could not change at all. So I did not think about redownloading.

Right now I am confused, but happy it is working again.  So happy that I just bought the license.

Thanks again.

**Comment by mzomparelli** [comment]
Thank you!!

**Comment by CJS-Design** [comment]
Okay, so it came back this morning. Right after clean reboot and zVirtualDesktop in Autostart it displayed the same error. Then I disabled Avast for 10 Minutes - and could start the utility.

If I enable Avast again, zVD is still runnning. If I then close zVD and try to reopen - I get the message from this issue (already running). So somehow this combination of Win10, Avast and zVD don't want to play together.

I even added the path of zVD to the trusted paths in Avast - that still did not help.

**Comment by CJS-Design** [comment]
Avast Behavior Shield is somehow responsible for this. I can add a trusted path to that component and that seems to work for now.

**Comment by mzomparelli** [comment]
Sorry about that. It could be the mouse and keyboard hooks that are causing the anti-virus to be triggered. Adding the exception to your anti-virus is ok. I promise that I'm not doing anything malicious.

This link is to VirusTotal for the current version or zVirtualDesktop
https://www.virustotal.com/en/file/4a9d79871e642cee482954934ef2bf9ddace3b4f52b31477cb2cf71bb30a25ea/analysis/1513572041/
