### ISSUE TITLE
App does not open after forcefully killing it

### ISSUE THREAD

**Issue by dsp0105** [mzomparelli/zVirtualDesktop#155]
App doesnt open after I forcefully kill it.

Also is there a cmd line option of closing the App?

**Comment by mzomparelli** [comment]
What are you seeing when you try to open it after killing it?

When I'm debugging my only method of terminating is forcibly and I've never had any problems.

I just forcibly killed my active release version and it started up fine.

**Comment by mzomparelli** [comment]
No, there is no command line to close the app. It was never designed to be used at all through a terminal window. It's all GUI.

**Comment by dsp0105** [comment]
Thanks for getting back,  found a bug in my Powershell script, it is working now without issues.


When I log in to my PC, I run a power shell script to set the task bar  icons' size based on monitor size.
Faulty flow: 
set task bar icon size,
kill explorer.exe, kill zVD
Restart explorer, Restart zVD

Correct flow; 
set task bar icon size,
kill zVD, kill explorer
restart explorer, restart zVD

**Comment by mzomparelli** [comment]
I’m happy to hear you figured out your issue.
