### ISSUE TITLE
Trouble with registration verification

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#157]
Hi, today, zVD suddenly gives me this message during startup:
https://i.imgur.com/tU3MXrM.jpg
If I right click the trayicon to bring up the context menu and select settings and then click account, zVD hangs and I have to terminate it using taskmanager.
I have never seen this behaviour before, and I haven't done anything (as far as I am aware of).
I'm currently running 1.0.74 but I cannot say for sure when the most recent update took place.

Rgds

**Comment by mzomparelli** [comment]
It's nothing you have done. I'm dealing with an ignorant user trying cause problems with my server. I should have expected this.

The server is online and you should be good to go. Let me know if you continue to experience this issue. I am working on another solution for the registration.

**Comment by oywino** [comment]
Oh, - I'm sorry to hear that. Thanks for letting me know, and good luck with your "cleaning job".
I stopped and restarted zVD and the message no longer appeared and I can again see my account :)

**Comment by mzomparelli** [comment]
@oywino please see an email from zVirtualDesktop from last night. Version 1.0.75 should fix fix this issue permanently. but I had to remove all registered computer for it to work. Your account has changed, you just need to activate your computer again. Don't reactivate until you have version 1.0.75.

**Comment by oywino** [comment]
I just did. Worked out ok. Thanks - and A Happy New Year to you Michael :)
