### ISSUE TITLE
Paid version displays trial dialog

### ISSUE THREAD

**Issue by jdmcfadden-usx** [mzomparelli/zVirtualDesktop#158]
I have version 1.0.0.74 of zVirtualDesktop, paid for and licensed on Dec. 18. At the time, I registered the application on the account screen using the key code I got via email after the purchase.  Today (Dec. 28), the program displayed a dialog shortly after startup indicating the trial period had expired. When I try to look at the account screen, I get a blank tab and the application stops responding until I restart it.

**Comment by mzomparelli** [comment]
This was an issue this morning, but the server has been responding well since the issue this morning. You should not be having this issue now unless you are disconnected from the internet or are blocking connection to the server.

Once registration is verified at program startup you can disconnect from the internet if necessary.

**Comment by mzomparelli** [comment]
I am aware of this inconvenience and I'm working on a solution.

**Comment by jdmcfadden-usx** [comment]
Yes, it is working now. Thanks so much. I find this utility very useful and well-implemented.

**Comment by jdmcfadden-usx** [comment]
This issue is occurring again. I'm unable to access the Accounts tab and I get a dialog indicating the application was unable to confirm my registration. I am connected to the internet.

**Comment by mzomparelli** [comment]
Did you register after you updated to 1.0.75?

The server is back up. Can you force an update and highlighted button on the Account Details page. Let me know if that message box contains a string of characters. If you don't have a local license then you will need to re-register your computer. I will un-register for you if that's the case.

![image](https://user-images.githubusercontent.com/10564234/34485623-3e80a25c-ef91-11e7-8e98-cb66a63d4f42.png)

**Comment by jdmcfadden-usx** [comment]
It is working again now. I think this was pilot error on my part; my software was not current. Sorry to have bothered you.

**Comment by mzomparelli** [comment]
I’m glad it’s working now. Don’t worry about bothering me. I want to make sure you are happy with the software.

**Comment by jdmcfadden-usx** [comment]
I have a local license, I see a registered computer in the accounts screen, but none of the features of the application are working. Maybe we should try unregistering and reregistering?

**Comment by mzomparelli** [comment]
When it goes into expired mode it turns the mouse and keyboard hooks off and you have to turn them back on after registering.

I hope your issue is as simple as that.

**Comment by jdmcfadden-usx** [comment]
Yes, that did it. Thanks.
