### ISSUE TITLE
Your trial has ended.

### ISSUE THREAD

**Issue by Ventzy** [mzomparelli/zVirtualDesktop#159]
Hello,
I have used zVirtualDesktop for some time but recently, when I start it I get

```
Your trial has ended.
Please purchase a license to continue using zVirtualDesktop.
```

I don't see anything on github saying this is trial and paid app.

**Comment by mzomparelli** [comment]
How long have you been using zVirtualDesktop?

What you are seeing is legit. You should have noticed the account tab on the settings form. This app was free while I was designing it, but now that I've got a pretty useful application I'm trying to earn money for the time I've invested as well as the time I continue to invest.

**Comment by mzomparelli** [comment]
Read this...
https://github.com/mzomparelli/zVirtualDesktop/issues/142

**Comment by Ventzy** [comment]
Thanks Michael, that makes sense. I haven't seen this announcements and anything related to it on the README, that's why it was unexpected to me. It is great app and I hope it will have the success you are aiming for.

**Comment by mzomparelli** [comment]
Thanks!
