### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#16]
Windows 10 has a setting where all default system tray icons are minimalstic white lines. I'd like to have zVD icon that looks the same. Similar to your White Box, but with white lines instead of black lines.

**Comment by mzomparelli** [comment]
@oywino Yes, those icons need work. I left Whitebox and Blackbox in so that someone would see them and fix them. I will fix them soon.

What is this minimal feature in Windows 10 you speak of? How do I activate it? I don't think I've seen this yet.

**Comment by mzomparelli** [comment]
I fixed these icons in v1.0.7. I am working on some new ones too. If you'd like to design a set then a good app for that is http://icofx.ro

Send me any you create and I'll add them with a name of your choice.

**Comment by oywino** [comment]
Here's a sip of my desktop: http://i.imgur.com/awH1844.jpg
You see how the zVD icon differs from the others. That's what I mean.
I'll be happy to experiment with icofx.ro but I'm not sure I'll be able to find time before towards the end of April.

**Comment by mzomparelli** [comment]
I see what you're saying about the icons. I'll make another set to be just like you have in your screen shot, but will be white instead of black. In the meantime, I think the fixed WhiteBox will look good on your machine.

**Comment by mzomparelli** [comment]
I just made a new set of icons that should match better for you. They aren't perfect, but they are not bad. You can use them if you download the pre-release v1.0.9. You can get this version by using the green download button from the main repository page.

Here's a screen shot
http://imgur.com/a/FCsAv

**Comment by oywino** [comment]
It would be easier to contribute if you would provide a zip with all the ico files you are currently using. Then we could continue from the one we prefer, using icofx...

**Comment by mzomparelli** [comment]
Ok, I will zip the icons folder and provide a link.
