### ISSUE TITLE
remove desktops

### ISSUE THREAD

**Issue by mcapella** [mzomparelli/zVirtualDesktop#160]
MICHAEL,

PLEASE FIX REMOVE DESKTOPS AND TITLES SHOULD MOVE WITH DESKTOP WHEN MOVED.

THX

**Comment by mzomparelli** [comment]
This will require an update and you dislike updates :P

**Comment by mzomparelli** [comment]
I've decided that this is not functionality I want in this application. However, I am open to further discussion on the topic.
