### ISSUE TITLE
Flashing Title bar

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#161]
Hi, I recall a while back that the issue with the flashing title bar occured (but I don't recall the issue # where we discussed it)
Then, you did something to make it disappear and it has since been gone, until a couple of days ago, it is now back again. I am now on 1.075 but I do not recall having made (or initiated) any updates myself. Does zVD update automatically in the background? 
Over the past two days, the flashing has increased until today it became permanent - Every time I change desktop, the title bar of the top most window flashes constantly (maybe also due to AeroRainbow?).
I had to terminate zVD and restart it to end this loop.
After a restart, it now just flashes a few times before it settles. Still, I prefer it not to flash at all, and I suspect it will gradually increase again over the coming days, until I again have to break.
Any ideas?

**Comment by mzomparelli** [comment]
I've been noticing this too. I think for some reason I removed the code that stops the flashing. I will address this tonight.

**Comment by mzomparelli** [comment]
I published an updated for this. It's not a new version number yet, but you can get it by pressing the "Force Update" button on the settings form. Let me know if this helps the issue.

**Comment by mzomparelli** [comment]
Are you seeing this issue when switching with DesktopView or the hotkeys or both? It appears to happen a lot less when using hotkeys.

**Comment by mzomparelli** [comment]
Continued here...
https://github.com/mzomparelli/zVirtualDesktop/issues/165
