### ISSUE TITLE
trial period instantly ending?

### ISSUE THREAD

**Issue by adipalihovici** [mzomparelli/zVirtualDesktop#162]
Hi, I just downloaded this for the first time today and not 10 seconds after I had opened it, a "Your trial has ended. Please purchase..." window appeared. 

I'm really interested in trying this out and potentially buying it, since I've been trying to copy linux's workspace-related features with AHK for years now, and this has the potential to be much less cumbersome to use. But I can't do any of that!

As far as I'm aware, none of the features worked other than a big "Desktop #" appearing when normally switching desktops using Window's built-in hotkeys.

Is the no-trial-period thing intended, or is it actually supposed to last 10 days and I just got unlucky? I tried downloading and unzipping it multiple times, by the way.

Thanks in advance for having taken the time to read this.

Edit: It also throws an unhandled exception when trying to access the "Show Desktop View" from the taskbar-accessible menu.
![exception](https://user-images.githubusercontent.com/16763127/35177033-7016cf60-fd85-11e7-8c71-87a74ba333d3.png)

**Comment by mzomparelli** [comment]
Restart the program and try again. It's unlikely for this to happen, but it is possible. I'll look for a solution.

Let me know if this is still an issue for you.

**Comment by mzomparelli** [comment]
When you start your trial you will have to enable the keyboard hook in order for hotkeys to work. When going into expired mode the hooks are turned off.

**Comment by mzomparelli** [comment]
I'm making some changes that will basically restart the trials for everyone

**Comment by mzomparelli** [comment]
You should download the new version...1.0.76
