### ISSUE TITLE
Flashing Titlebar and hanging

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#163]
Hi,  zVD is randomly going into a state where it flashes the titlebar of the topmost (focused) window when I change to another desktop. The intensity of the flashing (how long it goes on before it settles), seems to vary. 
Today also, I could no longer bring up the zVD menu when clicking on the taskbar icon. Neither left, nor right-click did anything. So I had to stop and restart zVD.
But the titlebar flashing continues.....

**Comment by mzomparelli** [comment]
I’m on vacation right now, but I’m heading back home this evening. I’ll look into this soon.

**Comment by mzomparelli** [comment]
What is you main method for switching desktops? DesktopView or Hotkeys?

**Comment by mzomparelli** [comment]
Since the change I made for this issue in version 1.0.76 I see the flashing taskbar button very little. When I do it stops flashing pretty quickly. Are you still using Aerorainbow?

**Comment by mzomparelli** [comment]
Continued here...

https://github.com/mzomparelli/zVirtualDesktop/issues/165
