### ISSUE TITLE
zVD crashes - now and then

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#165]
I think that my problem with random crashes is somehow linked to the fact that I use AeroRainbow.
The typical pattern is that the flashing of the titlebar increases slowly over time (several days). In the end it flashes continuously and the CPU load reaches 100% on all 4 cores after a short while. At that point it becomes almost impossible to launch even Task Manager in order to kill zVD.
So, I have been on the alert to look out for the increasing flashing and then manually restart zVD before it becomes too bad. So, eventually - now I restart zVD approximately 2-3 times per week.
The frequency here is clearly linked to how much I use zVD.
Keep in mind also that my computer runs 24/7. I never turn it off unless I have to.

**Comment by mzomparelli** [comment]
When you CPU reaches 100% utilization, is it AeroRainbow or zVirtualDesktop consuming the processor. I'm leaning toward this being an issue with AeroRainbow. zVirtualDesktop does not explicitly make the taskbar flash or alter desktop colors or themes. However, zVirtualDesktop will tell the window taskbar button to stop flashing.

If you were to try using zVirtualDesktop without AeroRainbow would you still have the same issue?

**Comment by oywino** [comment]
I will experiment a bit with your suggestions, and report back.
The strange thing is that when I kill zVD and restart it, things gets back to normal  - for a while...

**Comment by mzomparelli** [comment]
Try to find out which application is taking the CPU when this occurs. Also, try killing AeroRainbow instead of zVD next time to see if that can also resolve the issue.

If zVD is crashing then please visit the windows event viewer to get the stack trace. That would be very useful in helping me fix an issue with zVD.

**Comment by oywino** [comment]
Trying to capture the screen while the titlebar flashing escalates is almost impossible because the whole computer becomes totally unresponsive. So I had to do it in an earlier stage of the issue - long before the CPU load reaches 100% (See the enclosed image). This time, AeroRainbow was also running. Killing and restarting zVD fixes everything.
I'll continue to research. It just takes time.
https://i.imgur.com/gCbuQr5.jpg

**Comment by mzomparelli** [comment]
Did you try killing AeroRainbow instead?

When I tested this I was able to reproduce your issue, but since not using AeroRainbow I have never had any issues. I'll download AeroRainbow again and test on a VM.

**Comment by oywino** [comment]
My next attempt will be to kill AeroRainbow, but I'll have to wait until the issue emerges again.

**Comment by mzomparelli** [comment]
What happens in this scenario? I'm wondering if the issue is with AeroRainbow and Taskbar button flash.

-zVD not running
-AeroRainbow is running
-Any window flashes its Taskbar button

**Comment by oywino** [comment]
Hi, and thanks for your support.
I have reviewed all my settings in AeroRaibow and Winaero Tweaker as well as WIndows 10 Personalization Colors setting.  They all seem to influence and touch on conflicting  elements, including colorisation of title bars. My "cleanup" and housekeeping seems to pay off, but I'll have to give it some more time before I conclude.
I'll keep you posted.

**Comment by mzomparelli** [comment]
That's good to hear.  I hope it all works out. Let me know.
