### ISSUE TITLE
(Desktop overview + number)  to go to a desktop

### ISSUE THREAD

**Issue by dsp0105** [mzomparelli/zVirtualDesktop#170]
Hi Michael,

Wondering if this behavior can be added?

Steps for my senario:
------------------------
Lets say we have 3 desktops:

Desktop1 - Office mail
Desktop2 - Browsing
Desktop3 - Bugs

1. Open the desktop overview through a shortcut (in my case alt+tilde). 
2. Then add an option for the user to go to the needed desktop by pressing the corresponding number
(example: 3 if the user wants to go to "Bugs Desktop")

I know that you have the keyboard short cut option to directly go to Desktop 3, but that is not really useful since I have to remember the mapping in my head ("Bugs desktop" is Desktop 3). Hence I prefer to see the Desktop Overview before I selecting the desktop.

Thanks!

**Comment by mzomparelli** [comment]
I like this idea and it should be pretty simple to implement for numbers 1 to 9, but I'm not sure what to do for greater than 9. If you have any suggestions then let me know. My first go at this would be to only respond to 1 thru 9.

**Comment by dsp0105** [comment]
Thanks for accepting, it would save me lot of pain  :)

Think we can use the  Windows OS task bar behavior i.e., using 0 for 10th Desktop. But after that there is no simple way, the user has to use the mouse to click that desktop. This should be good too since it forces the user to move the "most used desktops" to numbers 1-10.

Think 10 desktops are enough for now, even on my new 38 inch Dell ;) That monitor + zVD are my time saviors 👍 

Also, I think I saw a bug where 10th desktop cant be named (No title appears in desktop overview), please let me know if I need to raise a new issue for that.

**Comment by mzomparelli** [comment]
The only place you can assign a name to desktops greater than 9 is in DesktopView. I just tried naming desktop 10 and it worked as expected.

In the settings form I limit to only show 9 desktops. In DesktopView, you can name 100 desktops with zVD.

**Comment by dsp0105** [comment]
I remember I noticed it a while back, but in the latest version it seems to be working fine, thanks!
Yeah, I wanted to name in DesktopView not in settings form (I dont use that at all, not sure what is the main use of that)

**Comment by mzomparelli** [comment]
Force an update right now and you'll have the feature you just requested.

The purpose of the settings form is so you can set a desktop wallpaper. That too can have 100, but I limit to 9 in settings. Who needs more than 9 desktops?

**Comment by dsp0105** [comment]
Awesome, thanks a lot!! 

Desktop view + number to go to a desktop is working 👍 

I see, okay,I don't use wallpapers anyways, since it slows down and also decreases clarity for my desktop icons.

I agree >9 desktops are not used normally, the use case would be like this:

1. Lets say current working set is say 6 desktops.
2. But in the non-working set, the user keeps 4 desktops for 4 issues he resolved recently (just in case  he has to revisit them). He waits for a week and see that out of 4 desktops, 2 are not needed, then he removes them totally. 

The process repeats, it is  a nice feature to have but not a high priority one though! 
Actually in my day to day work, I am restricting my desktops to be less than 10 since after that it gets hard to remember. 

Thanks again for the fast response and the fix 👍

**Comment by mzomparelli** [comment]
I created a bug in this that I just fixed. Prior to the current build this feature would prevent you from typing numbers as a desktop name. This is fixed now. Simply do a force update.

**Comment by dsp0105** [comment]
Sure, thank you!
