### ISSUE TITLE
Trial expired after 1 day

### ISSUE THREAD

**Issue by mholttech** [mzomparelli/zVirtualDesktop#171]
Hi,

I installed your program yesterday and was really liking but hadn't gotten much time to really use it.  Now today it's saying that it is expired.  I've seen a few other issues regarding this but not anything about how to fix it.

Please Help

**Comment by mzomparelli** [comment]
My server was down 30 minutes ago for backup and would have triggered this. If you restart zVD everything should be ok.

Unfortunately I have to perform backups once in a while and this means taking the server offline. It only takes about 10 minutes to perform the backup routine.

I'm very sorry about the inconvenience.

Please note that when you have purchased a license and registered a computer it will have a local license. This mean that an internet connection is not required for licensed computers.

**Comment by mzomparelli** [comment]
Also, running a version prior to 1.0.76 could cause this.

**Comment by mzomparelli** [comment]
If restarting zVD doesn't fix your issue and your version is current then I'll investigate as a bug. I plan on making some adjustments to make the messages more clear.

**Comment by mholttech** [comment]
I have restarted the app and the computer without success

**Comment by mzomparelli** [comment]
What is the name of your computer?

Feel free to send me an email with that info if you feel more comfortable in doing so. zVirtualDesktop@gmail.com
