### ISSUE TITLE
Looking for someone to make a video /article about zVD - Offering Free Licenses

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#173]
Please let me know if you are interested in earning free licenses by creating a written or video tutorial for zVirtualDesktop.

You can post videos on YouTube and send me a link.

**Comment by SolveAllProblemsRightNow** [comment]
if the goal here is more about reach, and visibility, i'd just post it all over all those sites that are more software windows related

could just send a quick email to all those sites that publish stuff as well

everything really depends on what exactly the goal is tho

**Comment by mzomparelli** [comment]
well obviously the goal is to sell as many licenses as I can. I'm not sure what sites you're referring to. Are you talking about it being bundled with other software?

**Comment by SolveAllProblemsRightNow** [comment]
lol why did you close it when you just said 'Thanks for the feedback. I've been meaning to revamp the readme.'

**Comment by mzomparelli** [comment]
I don’t need this open to do that.
