### ISSUE TITLE
Mouse back/forward buttons

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#174]
My mouse has back/forward buttons like these:
![](https://cache.gawkerassets.com/assets/images/lifehacker/2011/12/extramousebuttons.jpg)

I think it would be cool if I could press those over the taskbar to go backwards/forwards through desktops.

Could you add those as shortcut keys (similar to the middle click over taskbar shortcuts)?

**Comment by mzomparelli** [comment]
I think I might be able to, but I don't have a mouse with these buttons. All of my mice are gaming mice because buttons on my mouse are awesome. Anyway, I think this is what is referred to as the X buttons. X1 and X2. I'll put it together and let you test it out.

**Comment by mzomparelli** [comment]
I just pushed a build for testing this. Let me know if you have any issues. 1.0.78.6
The fourth number in my version is build. You will only be notified when the third number is incremented so you'll have to press the force update button to get this update.

```
MOUSE-TASKBAR-X1-CLICK
MOUSE-TASKBAR-X2-CLICK
MOUSE-FOREGROUND-CAPTION-X1-CLICK
MOUSE-FOREGROUND-CAPTION-X2-CLICK
MOUSE-ANYWHERE-X1-CLICK
MOUSE-ANYWHERE-X2-CLICK
```

**Comment by ghost** [comment]
Nope, it doesn't seem to work.
I've seen them called "IE (internet explorer) back" and "IE forwards" or just "browser back" and "browser forwards," if that helps.

**Comment by mzomparelli** [comment]
Does your mouse have tilt wheel? I wonder if X1 and X2 are for those. I have no way to test this. Do you have access to a window spy? Maybe you could listen in and identify the key as you are sending it to a window.

Does your mouse have software that allows you to configure those buttons?

**Comment by mzomparelli** [comment]
Can you specifically test button X2 in zVD? I might have the values incorrect. X2 could either be X1 or X2. X1 may not reference anything at all. I don't know which button on your mouse is X2. Just test something with X2 in zVD and try both buttons.

Thanks!

**Comment by ghost** [comment]
No tilt wheel, and I tried testing X1 and X2 with both buttons, neither worked. The configuration software I have just calls them IE Backwards and IE Forwards, but I've used them in a game that called them mouse 4 and mouse 5. As far as I can tell, that is the same thing as X1 and X2, as shown [here](https://autohotkey.com/docs/KeyList.htm), so I'm not sure why it doesn't work. I have a middle click on the taskbar shortcut in zVD that does work, so it's weird.

**Comment by mzomparelli** [comment]
I think I have this figured out. Give me about 20 more minutes and I should have a new build.

**Comment by mzomparelli** [comment]
Do another force update. I think I nailed it this time.

X1 should be the button that is closest to you which is probably the back button. X2 would be the front one. Please correct me if I'm wrong.

**Comment by ghost** [comment]
Definitely closer, but it seems that both the back and forwards buttons map to both X1 and X2.
There's also an issue where it seems to start capturing all mouse input once I use the X1 or X2 on the taskbar shortcuts, and I'm unable to click on anything, like if I try and click on a window it just won't become active, although some amount of right clicking does seem to be still work. The way I've figured out to fix it is by using the back and forwards buttons a few times while the mouse is over a different window. This bug actually happened to me with the middle mouse on taskbar shortcut yesterday, but I wasn't sure it was zVD's fault or something else.

**Comment by mzomparelli** [comment]
I'm not sure about issue where it stops capturing mouse. Open a new issue for that and I'll try to get to the bottom of it. I have not experienced this. I use TASKBAR-MIDDLE-CLICK to open the settings window.

As for both buttons tied together. The build I just published might take care of that. I'm sorry for all of this. I need to get your mouse so I can test before publishing.

**Comment by ghost** [comment]
No worries, thanks for trying! The new build doesn't seem to change anything though.
It's not a big deal if you can't get it working.
If you do want to get my mouse though, [this](https://www.amazon.com/Nixeus-Revel-Gaming-Windows-Rubberized/dp/B01HHGHCH8?th=1) is the one. It was $25 when I bought it like 2 weeks ago though, so I'm not sure why its suddenly so much more expensive.

**Comment by mzomparelli** [comment]
I was able to program my mouse to send those keys. This allowed me to test and I think it paid off. I just published a version that should be good now.

**Comment by ghost** [comment]
It works! And the weird mouse capture bug doesn't seem to happen anymore. Thanks!

**Comment by mzomparelli** [comment]
I have another update coming out shortly. I actually told you about it too soon. I still have some work to do, but it should be fine to use. It will only work for MOUSE-ANYWHERE right now.

**Comment by mzomparelli** [comment]
ok, now do an update to make it more complete. Let me know of any issues.

**Comment by mzomparelli** [comment]
I had to do some things that really shouldn't need to be done. Basically, I had to force the X buttons back in the up position. I have to do this so that it flows back up the hook chain and this means that it could still perform the normal x button functionality. To avoid this I try to set focus to the Taskbar first so that it won't go back to window. It appears it's not always fast enough though. I'll continue to "hack" at this lol

**Comment by ghost** [comment]
I just noticed it, but it looks like that hack causes the back/forward buttons to be pressed twice, even when not over the taskbar, which messes with browser navigation and etc.

**Comment by mzomparelli** [comment]
Did you get 1.0.79? I made more changes last night. I will look for another solution for this.

**Comment by mzomparelli** [comment]
I just published 1.0.79.1. I think this works now. I recall saying that before so take is at you will  :)

**Comment by ghost** [comment]
Yup, it seems to be all fixed now. Thanks!

**Comment by mzomparelli** [comment]
I think there still might be issues.

**Comment by dsp0105** [comment]
Thanks Michael, this is a very wonderful addition to zVD, I like your idea of using zVD as one-stop tool for KB and Mouse shortcuts. 

Like the option you provided for X1, X2 such on Taskbar/Screen/etc, nice thinking! 👍

**Comment by mzomparelli** [comment]
Any issue with this feature?

I'm going to close it. Feel free to open it again or create a new issue.
