### ISSUE TITLE
Mouse being indefinitely captured

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#175]
Sometimes when using middle-click-on-taskbar, zVD seems to start capturing all mouse input, and I'm unable to click on anything. If I try and click on a window it just won't become active and the taskbar and most things won't work, although some amount of right clicking does seem to be still work. The way I've figured out to fix it is by using the button that cause the error (e.g. middle click) a few times while the mouse is over a different window. This has only happened once with the middle click shortcut, but using the X1 and X2 buttons as mentioned [here](https://github.com/mzomparelli/zVirtualDesktop/issues/174#issuecomment-373561201) cause it to happen every time.

**Comment by mzomparelli** [comment]
If you enter a secure screen like the CTRL+ALT+DELETE screen then you can click in there to bring the mouse capture back.

It seems the middle click is getting stuck sometimes. I've rarely experienced this even though I do have a Middle Mouse hotkey action. I'll continue to investigate.

Please let me know if you see the same issue with a right or left-click hotkey action.

**Comment by mzomparelli** [comment]
Are you still experiencing this issue with middle click?

**Comment by ghost** [comment]
It hasn't happened to me since.

**Comment by mzomparelli** [comment]
If it happens again feel free to reopen or create a new issue.
