### ISSUE TITLE
CPU usage at top of idle

### ISSUE THREAD

**Issue by nicolasdejong** [mzomparelli/zVirtualDesktop#178]
While not really a problem, I still wonder why it is that zVirtualDesktop uses relatively much cpu:

![image](https://user-images.githubusercontent.com/12181216/38070366-f05b6a7a-331b-11e8-9969-c7152a67c00b.png)

(this is on a quad-core i7 desktop)

Is there some polling going on? If the window-positions are scanned a few times per second I can understand it, but I don't think that feature is in yet. Something with the keyboard? But that should be event based, I think. Anything I can switch off that I don't use?

And now that I'm here anyway: any ideas on when (or if) you'll work on newly requested features? It seems you no longer keep the Trello page up to date. I'm still hugely enjoying the current features, so no pressure, it would just be nice to have things like move to previously selected desktop or remembering window positions.

**Comment by mzomparelli** [comment]
Last night I did remove a piece of unnecessary 10 ms timer, but that should have been insignificant because it was an empty timer. You can force an update and see if there is a difference for you.

If you have mouse and keyboard hooks on then every time you move your mouse or press a key zVD is checking if it’s a hot key. This will use some cpu.

I’ll look into this more to see if there is anything I can do to bring down the cpu usage.

**Comment by nicolasdejong** [comment]
Nope, actually now it uses more cpu:

![image](https://user-images.githubusercontent.com/12181216/38087159-64d33e7e-3357-11e8-96b0-438b8a422f9d.png)
(note that 12.5% in my case is 100% of one core, so zVirtualDesktop is quite busy)

And also it changed my background image for some reason.

**Comment by nicolasdejong** [comment]
It didn't just change my background image, but it inserted one. The image for desktop 1 is a random image from the images directory I get the images from. The image from desktop 1 moved to 2, 2 to 3, etc. The image for desktop 9 is gone.

Selecting image in 'desktops' configuration makes it black. Configuration seems unchanged. Trying to set images back to the way they were.

**Comment by mzomparelli** [comment]
Sorry that is the result of adding a slideshow option for wallpapers. I’ll look into the cpu usage this evening.

**Comment by mzomparelli** [comment]
I have a solution in mind

**Comment by nicolasdejong** [comment]
Switching desktop now switches background image twice. E.g. switching to desktop 5 shows background for 4, then 5. Switching to desktop 9 shows 8 then 9, etc. So I get a short slideshow for each switch.

**Comment by mzomparelli** [comment]
hmm, that is strange. This might sound silly, but since you just updated it altered the settings file slightly. Try restarting the app now that there is a new settings format applied.

I'm working right now to decrease the CPU usage. I should be able to at least get it down to the original level you first reported.

**Comment by mzomparelli** [comment]
I just published a new build that should reduce the CPU back to what you were originally seeing.

**Comment by mzomparelli** [comment]
In my testing, this helped pretty well. Here is a screen shot CPU usage time using Performance Monitor.

I did this test last night and it was higher so this build definitely reduced the CPU usage.

![image](https://user-images.githubusercontent.com/10564234/38090479-5f68c078-3328-11e8-8faa-88e2ffe67118.png)

**Comment by mzomparelli** [comment]
This also helped reduce the memory usage. Thanks for calling this out. I will continue to improve on this issue.

**Comment by nicolasdejong** [comment]
Thanks. Everything is back to normal now. Even better, the cpu seems lower than before. I'll keep checking.

![image](https://user-images.githubusercontent.com/12181216/38091399-bcb85e54-3365-11e8-877c-d6d35ef04058.png)

**Comment by mzomparelli** [comment]
Awesome! Let's leave this open while I investigate  more.

**Comment by mzomparelli** [comment]
I was able to reduce CPU usage even more by combining three threads into one.

**Comment by nicolasdejong** [comment]
Great! Top notch support again. Thanks!

**Comment by mzomparelli** [comment]
I was able to reduce the CPU usage a tad more. This could possibly have negative consequences to the applications's functionality, but in my testing it seems ok.

**Comment by mzomparelli** [comment]
Ultimately, the CPU in use is coming from the hook threads. We need those for hotkeys so I think I've reduced this as much as possible. Reducing the CPU usage for these threads will slow down the thread. This could have very noticeable effects on your mouse and keyboard clicks. There are a few other threads running,but they use very little CPU.

Update Thread: Checks if an update is available every 60 minutes. CPU usage is very minimal.
Activation thread: A 30 minute check for unlicensed users and a 12 hour check for licensed users. This also in minimal CPU.

**Comment by mzomparelli** [comment]
I'm going to close this because I think I've done as much as I can. However, I will keep this in mind and continue looking for ways to reduce the CPU usage.
