### ISSUE TITLE
Just a simple question

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#180]
You're adding new features, like these:
·	MOUSE-TASKBAR-X1-CLICK and MOUSE-TASKBAR-X2-CLICK
·	MOUSE-FOREGROUND-CAPTION-X1-CLICK and MOUSE-FOREGROUND-CAPTION-X2-CLICK
·	MOUSE-ANYWHERE-X1-CLICK and MOUSE-ANYWHERE-X2-CLICK
But I failed to figure how and what and why ?

**Comment by mzomparelli** [comment]
These only apply to mice that these two extra buttons. There is a picture of a mouse with these buttons in issue https://github.com/mzomparelli/zVirtualDesktop/issues/174

There still may be bugs when using these in a hotkey.

**Comment by oywino** [comment]
Ooo! That is a very cool feature! :)
