### ISSUE TITLE
Option to convert CapsLock to a modifier key

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#181]
Provide an option in settings that would cause the CapsLock key to act as a modifier key that could be used in hotkeys.

**Comment by mzomparelli** [comment]
I can't be (and I know I'm not) the only person that dislikes the CapLocks key. It makes sense to convert this key to a modifier key like CTRL and SHIFT.

**Comment by mzomparelli** [comment]
This is good to go in the newly published version 1.0.80.6

Please let me know if there are any issues.

**Comment by SolveAllProblemsRightNow** [comment]
i use 'sharpkeys' for that - works for all single keys to single keys

still gotta do autohotkeys for the other things...

**Comment by mzomparelli** [comment]
Sharpkeys uses the registry and does not work in all apps. I am using a keyboard hook to convert capslock to modifier. The keyboard and mouse hooks are how all of zVD's hotkeys work.

What are you using autohotkey for? I used to use AHK too. Lately I don't have a need for it.

**Comment by mzomparelli** [comment]
@SolveAllProblemsRightNow I think you are mistaken about Sharpkeys. That program can't turn capslock into a modifier. It can make it a modifier key by copying an existing modifier. zVD turns capslock into its own modifier. The capslock modifier.

This means capslock is not simply a copy of the shift or CTRL key. It is its own and I can use hotkeys like the following for different actions:

CAPSLOCK+A
SHIFT+A
CTRL+A
WIN+A
CAPSLOCK+SHIFT+A
ETC...

**Comment by mzomparelli** [comment]
I just got an idea though. Some people may want to still use capslock so I need to create a hotkey action to toggle capslock. This will allow you to permanently keep capslock as a modifier and then use whichever keys you want for the capslock action.

EDIT:
There is an action now to Toggle CapsLock
