### ISSUE TITLE
Softpedia 100% Clean Award

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#182]
I am pleased to announce zVirtualDesktop has received a 100% Clean award from Softpedia.

Softpedia emailed me today to inform me that they have tested zVirtualDesktop in their lab and have concluded the program is 100% Clean of spyware and malware.

http://www.softpedia.com/get/Desktop-Enhancements/Other-Desktop-Enhancements/zVirtualDesktop.shtml

All of you who have interacted with me should already know that I'm professional and my only goal is to create the best virtual desktop utility.

**Comment by SolveAllProblemsRightNow** [comment]
you seem like a cool cat according to the pic you have xD

i wonder what you do tho, im likely going macos longterm and would want everyone to switch to w/e i decide =)

tho im still still reading up on late-stage of os-related stuff, some polishing end stuff prior to the ultimately final decision

**Comment by mzomparelli** [comment]
I've tried to use Mac. It's not for me. However, I do prefer my iPhone over Android.

**Comment by mzomparelli** [comment]
Aside from the OS itself, you should consider Apple's hardware practices when making your decision.

https://www.youtube.com/channel/UCl2mFZoRqjw_ELax4Yisf6w
