### ISSUE TITLE
needed - make a clean list on the front/main page

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [mzomparelli/zVirtualDesktop#183]
hey how's it going

its me from https://github.com/mzomparelli/zVirtualDesktop/issues/121

you wanna make a clean list of the main features that thing has so i can test it eventually (maybe tomorrow?)?

just a clean straight list of main features at the beginning of https://github.com/mzomparelli/zVirtualDesktop

you know?

i've no idea what this does, and many ppl also dont know, and those ppl just leave, cos they wont ask, just normal human behaviour

need a clean list of main features at the start of the main page https://github.com/mzomparelli/zVirtualDesktop

ill be happy to inform/let ya know of anything that is unclear

**Comment by mzomparelli** [comment]
Thanks for the feedback. I've been meaning to revamp the readme.

**Comment by SolveAllProblemsRightNow** [comment]
well right now or a set date is as good of a time as any, since most things seem/appear to get bloated over time, and  after knowing what it does, ill be sure to check my issues page to test it out -- every cycle of 100,000 tabs i get through hopefully quickly....

**Comment by mzomparelli** [comment]
Do it for me :). I'll let you know if you missed anything.

https://github.com/mzomparelli/zVirtualDesktop/issues/173

I like to write the code. I've never been good with documentation.

I can offer $$ as well

**Comment by SolveAllProblemsRightNow** [comment]
lol i dont need $, im def no mercenary for hire ha

i cant tho you see cos im not the one that made/dev it, so i dunno what it does, you would be the best person

the main features is just a list cos it's not all minor features, it's just the main ones, it isnt something you need any extensive documentation for

also anyone that likes it would already make a video/article if they're a youtuber/blogger so wont be to concern about that but that's me

**Comment by SolveAllProblemsRightNow** [comment]
lol why you closed it?

**Comment by SolveAllProblemsRightNow** [comment]
for example, **'Navigate Desktops'** is likely one of the main features

w/e is the main features or most commonly used or most helpful should be at top, with a top heading

maybe break the sections up into 'desktops/functionality' and 'cosmetics/visuals'

one of the best pages i've seen is 

* https://github.com/ParticleCore/Iridium/wiki/Features

but the old page was a lot better cos it had pic

* https://github.com/ParticleCore/Particle/wiki/Features

the #1 reason why it was/is so good is -- specifically -- cos when you are on the options/settings page of this chrome extension, it had a direct link to the specific  features -- so you can see what it does

the features are also descriptive enough for most of them

i dont think i've seen anything out there so far that is as good as how that person did it


---

that list of features isnt structured/ordered/sorted by helpfulness, which is the best/most helpful kind of sorting, but i cant think of anything atm that is that good in telling you what something does

with limited numbers of features i think a list from top to bottom is fine

as i look at that page again, not only did they section/break it into 'main sections'

* video
* general

they also have subsections within that as well, that is solid, i cant begin to say how basic and good that is

it also seems they had revised the 'sections/section heading' from the prior to this current version -- since maybe it made more sense to them, also the features is slightly different

**Comment by mzomparelli** [comment]
this is helpful and I appreciate you taking the time to write all of this.

**Comment by mzomparelli** [comment]
I have a website now and soon I will be incorporating the license management into the site as well.
