### ISSUE TITLE
Permanently display some apps on all desktops

### ISSUE THREAD

**Issue by jdmcfadden-usx** [mzomparelli/zVirtualDesktop#184]
Prior to discovering zVD's existence, I was using the built-in Windows interface for multiple desktops and I somehow managed to permanently make my Skype window visible on all desktops. This behavior has continued once I started using zVD. I never have to tell zVD to show Skype on all desktops because it's already there. I'd like to achieve the same effect with other windows I frequently use, such as Slack and the DOS console. As it stands now, I have to assign them to all desktops every time I start zVD. Is there a way to assign them permanently like I apparently did with Skype?

**Comment by mzomparelli** [comment]
Does the pinned Skype window persist after a restart? I suspect you are pinning application instead of pinning just the window. zVD will allow you to do both types of pinning. Look for the hotkey action of Pin Application to see if that is what you are seeking.

**Comment by mzomparelli** [comment]
What you're looking for your Slack window should be Pin/Unpin Application

**Comment by jdmcfadden-usx** [comment]
Pinning the application worked and it did persist through a shutdown and reboot. Thanks for your help.
