### ISSUE TITLE
Navigate to previous Desktop sometimes fails

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#189]
zVD 10.0.84.3
When working in Google Chrome 66.0.3359.139 on certain Ajax-based pages, zVD's "Navigate to Previous Desktop" using the "Mouse-Anywhere-X1-Click" causes to zVD to attempt to close the browser.
Using the ordinary Ctrl-Win-Leftarrow does not produce the same problem. Neither does the same happen on most ordinary web pages. Moving forward using X2-Click causes no problem.
The particular page in question is the web frontend to QNAP servers. I haven't seen this elsewhere, but it was never a problem with zVD earlier.

**Comment by mzomparelli** [comment]
try 1.0.84.7

**Comment by mzomparelli** [comment]
I misread this so you probably wouldn't see a change in 1.0.84.7. I'll look into this and get back to you.

**Comment by mzomparelli** [comment]
Can you send me a link to a page that would have an issue?

**Comment by oywino** [comment]
At this point no, cause this issue comes only with the web admin page of a QNAP NAS which is internal on my LAN.  But I've never seen this before with zVD.
I'll let you know if it happens with an external web.

**Comment by mzomparelli** [comment]
Does the page respond to X1 when zVD is not running? If so, what does it do?

**Comment by oywino** [comment]
Yes, it does. 
Hence - since I have never seen this before (I've used X1 with zVD since first introduced), it must be due to some new (or unintended) feature that has arrived with one of the several releases and updates lately  to QNAP QTS Web frontend. Do you agree?

**Comment by mzomparelli** [comment]
What does X1 do in the web app when zVD is not running? Typically, web pages will navigate back with this button. It's a mouse/browser function and shouldn't be page specific.

**Comment by oywino** [comment]
That's strange, cause all it does is trying to close the page. That is clearly not an App function as the web throws a warning asking if I'm really leaving the page without logging of properly.
So this X1 behaviour must then be generic Chrome behaviour. But why then only in this page and no others?

**Comment by mzomparelli** [comment]
I have a solution. Give me a minute.

**Comment by mzomparelli** [comment]
Please test 1.0.84.8

**Comment by mzomparelli** [comment]
This should not happen anymore.

Is it possible that this was occurring because you were pressing X1 while your mouse was over the Chrome tab? This is a feature in Chrome. X1 to close a tab.

**Comment by oywino** [comment]
And where do I find that?

**Comment by mzomparelli** [comment]
Force update on settings window or download from main Github page.

**Comment by oywino** [comment]
OK, I did - but the result is the same.
![image](https://user-images.githubusercontent.com/18447119/39826898-8931da94-53b6-11e8-8131-264b5a101d28.png)

**Comment by mzomparelli** [comment]
That looks like it was generated by the page because you basically hit the back button. Mouse X1 in Chrome acts like the back button. To confirm, you should be able to generate this message box by pressing the back button in Chrome while on this page.

The changes I made in 1.0.84.8 should help. Can you confirm that you have this version? Also, ensure that the mouse hook is enabled. It can't work without the mouse hook enabled.

**Comment by oywino** [comment]
Yes, I have version 1.0.84.8
The thing is that I've never seen this before, and I've used X1 since you first released it. And I use it all the time! Now it just gives me trouble. (I'm not blaming you). I just don't understand why Chrome suddenly began to interpret X1 from my mouse when it has never done so in the past?

**Comment by mzomparelli** [comment]
Yeah, it seems strange. Let me look at it some more and maybe I can figure something out. It's just that one web page then? No other web pages have an issue?

**Comment by oywino** [comment]
Well, yes - but I normally don't think of it as a Web page, but more like a thinclient based admin front end for the QNAP OS.

**Comment by mzomparelli** [comment]
If it's running in Chrome and is HTML then we'll call it a web app even if it is internal to a network.

I just published 1.0.84.9. In this version I am taking a different approach to the mouse hook. I have not tested this fully, but it seems to be working the same. I hope this fixes your issue and doesn't cause any other problems.

**Comment by oywino** [comment]
I'm now on 1.0.84.9 and the problem is still the same. 
Keep in mind that if I turn off zVD, the same happens. This I do not know if it also happened before, cause I've never used X1 until you introduced me to it.

**Comment by mzomparelli** [comment]
I know why it's  happening and I'm looking for a solution.

**Comment by mzomparelli** [comment]
ok, I'm pretty sure this is fixed now. The issue was definitely my fault. I've changed my implementation of the mouse hook and everything should be good now.

1.0.84.10

**Comment by oywino** [comment]
Yess!  Now it's OK!  :)
