### ISSUE TITLE
Window banner flashing is back again

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#190]
Hi, after your successful debugging of the X1 issue, the flashing window banner problem is now back again. (it was gone for a long time after you fixed it a while ago).  Sorry, I don't recall the issue#

**Comment by mzomparelli** [comment]
Nothing has changed with this and the mouse hook fix the other day is unrelated. So this is just a coincidence. The flashing should stop within a few seconds of starting. Can you confirm the flashing is stopping?

**Comment by oywino** [comment]
Yes, it flashes rapidly for about 1.5 seconds, then stops.
But up until previous version it didn't flash at all (and it hasn't since you solved it).

**Comment by mzomparelli** [comment]
Try the update...1.0.85.1

**Comment by oywino** [comment]
Significantly better, but occasionally still flickering. Moving between screens now seems to avoid setting focus on any active apps - thus no flickering. However, when the "jump" takes place as a result of a programmatic action that also brings focus to a foreground app, then it flickers.
Your approach this time seems more like a workaround than bug kill.  :)

**Comment by mzomparelli** [comment]
"as a result of a programmatic action"

What do you mean by this? Are you referring to a desktop switch that wasn't initiated by zVD?

**Comment by oywino** [comment]
Exactly!

**Comment by mzomparelli** [comment]
I just published 1.0.85.2. It should reduce the flashing even more.

**Comment by oywino** [comment]
Indeed it does 👍
