### ISSUE TITLE
Failed to activate

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#195]
As mentioned, I am working on moving everything to a new computer, but upon attempting to activate zVD on the new computer using only my activation key, it spins for a while and then a small window comes up saying "Web service error" ?

**Comment by mzomparelli** [comment]
My server was down. It's back online now.

**Comment by oywino** [comment]
Yes, now it works! Thank you :)

**Comment by mzomparelli** [comment]
@oywino is your other computer still active? The reason I ask is because you have three licenses and now two are being used. To deactivate computers you simply log in with your credentials instead of using the key code. When logged in you can activate the current computer and deactivate other computers.

Alternatively, I can deactivate your old computer if you would like me to.

**Comment by oywino** [comment]
Hi, if it's ok with you, I'd like to leave it as is. Currently I'm slowly migrating everything to a new PC. That takes time because I want to move slowly - testing everything before I finally shut down the old. And I have many apps on it that I need to re-install, test and verify. Some apps are easily moved from one PC to the next, but others are very difficult - mainly because the author (developer company) does not offer easy transition models or migration path - including test/dual license models for the transition period.
Also, I'm keeping my old PC on Win 1709 while the new is 1803 which is still plagued with bugs, so I may run into problems which will delay me even more. While I'm onto this, I depend on my old PC for everyday work, and I have gotten used to (and fond of) zVD which increases my efficiency.
Then, I have equipped myself with a Dell XPS 2-in-1 ultraportable with i7 CPU, and if zVD offers any advantages on a touch screen, I'd like to have it running also on that device.
In the end, I think I'll only need two licenses, so if I could let you know when - I'd appreciate that.

**Comment by mzomparelli** [comment]
You have control to do this anytime when you login on the Account tab. However, if you run into issues let me know and I can take care of it on my end.

**Comment by oywino** [comment]
Thank you very much :)
