### ISSUE TITLE
Object Reference Error when switching desktops

### ISSUE THREAD

**Issue by clucksted** [mzomparelli/zVirtualDesktop#199]
Just installed the latest version, and when switching desktop we see "Object reference not set to an instance of an object."  The object indicated is zVirtualDesktop:GetApplicationView.

I'm running EPI 17692, and zVD 1.0.87.0

**Comment by mzomparelli** [comment]
17692 is not supported yet. Microsoft has apparently changed IApplicationView again. It's an easy fix and I'll release a version this evening. The highest supported Windows 10 version I have so far is 17672. I'll comment this evening when I publish the 17692 version.

**Comment by clucksted** [comment]
Got it!  I didn’t realize MS was being so flaky with their own APIs within insider.  I’ll be more patient in the future.

**Comment by mzomparelli** [comment]
IApplicationView and IApplicationViewCollection are undocumented interfaces. I suspect Microsoft is waiting to document them once they have finalized them. It's possible they may never document these interfaces. Sometimes Microsoft only changes the GUID, but sometimes they actually add/remove members from the interfaces. Either way, I can get it working.

**Comment by mzomparelli** [comment]
I'm currently downloading the 17692 update so I can inspect the new interfaces. I should have a new build shortly.

**Comment by mzomparelli** [comment]
This should fix your issue. You should be able to update zVD as normal until MS changes the interface again.

https://zomp.co/Files.aspx?id=zVD_Insider

It looks like you created an account to open this issue. That's awesome! There is a lot of great software you can find on GitHub. Please if you like zVirtualDesktop, hit that star button up top :)
