### ISSUE TITLE
1.0.10p the zVD setting window always pops up

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#20]
I noticed in 1.0.10p that whenever I now click on the Windows Task View icon, the zVD setting window always pops up next to whatever else is on that desktop.
If the desktop is empty, only the zVD window pops up.
That does seem like a bug (and not an Easter egg).....

However - while searching for eggs, I noticed a new feature; Alt-LeftClick on the zVD taskbar icon :)

**Comment by mzomparelli** [comment]
Yes, i noticed this and it's the result of how I use the main form as the settings window. I will fix this before 1.0.10 is released.

**Comment by mzomparelli** [comment]
ALT+LeftClick is new to me. It's the equivalent of doing ALT+TAB and it is a side effect of adding the feature of opening the Task View with the icon. A nice side effect!

This also is not the Easter Egg. A hint....the Easter Egg is a picture of my dog about to be attacked by a pack of pigs.

**Comment by mzomparelli** [comment]
This is fixed. I will publish a full release of 1.0.10 once I add your icons and try to deal with other issues.
