### ISSUE TITLE
File name of download

### ISSUE THREAD

**Issue by irahsu** [mzomparelli/zVirtualDesktop#200]
Clicking the Download buttons at [https://github.com/mzomparelli/zVirtualDesktop](https://github.com/mzomparelli/zVirtualDesktop) downloads a file with single quotes around it as below:
'zVirtualDesktop.zip'

This means that Explorer thinks the file extension is (zip'), and doesn't open it as a zip file. Also, the file is downloaded file type is text, not binary... it actually downloads ok, but just needs to be renamed before the file is usable.

I am using Firefox 61 on Windows 10.

Thanks!

**Comment by mzomparelli** [comment]
I'm aware of this issue with FireFox. It doesn't do this with Chrome. I'll look into it this weekend.

Thanks for the feedback.

**Comment by mzomparelli** [comment]
This issue is fixed.
