### ISSUE TITLE
zVD visual ideas

### ISSUE THREAD

**Issue by benz145** [mzomparelli/zVirtualDesktop#202]
Hey @mzomparelli, as you know, a lot of my feedback so far has been related to the visual design of zVD's desktop view (if it wasn't clear, I'm a very visual person!). I thought it might be a fun exercise to mockup some suggestions that I've been thinking about relating to the layout of zVD's desktop view. I hope you don't mind me taking a stab at it.

![zvd-visual-ideas](https://user-images.githubusercontent.com/12601485/42128516-2768a7f0-7c62-11e8-950a-f269dc3ce340.png)

Ignore the actual color values, I stuck with a simple palette just to experiment with contrast. Actual colors would need more consideration.

**Comment by mzomparelli** [comment]
Great feedback!

I think I can address the spacing pretty easily. Changing the borders for the table is going to be a little more tricky. Possibly I can address it by overriding the paint event.

**Comment by mzomparelli** [comment]
In the version you have, you already have the ability to highlight the header of the active desktop. You could do something like this. If you perform a force update then you can check out some additional changes and let me know how it's going.

![image](https://user-images.githubusercontent.com/10564234/42129761-25991b30-7c94-11e8-8a7a-0e40fd4f3dbf.png)

![image](https://user-images.githubusercontent.com/10564234/42129763-2f383cac-7c94-11e8-9f3b-bae635b21ae7.png)

**Comment by benz145** [comment]
Cool I just tried the latest version and I can already see improvements in spacing. However the spacing I'm seeing is still pretty tight compared to your screenshot above. Here's what mine looks like (on a 2560x1140 monitor):

![image](https://user-images.githubusercontent.com/12601485/42130243-f4c726d2-7c93-11e8-95fc-ad6df8b53e08.png)

I think the spacing in your screenshot is better/more clear than what I'm currently seeing. 

I did spot the active header color options, in the screenshot above you can see I went with a simple opposite color label to make it standout.

A bit off topic, but I also noticed there is an option to make the column background the desktop background. After checking the box my column backgrounds are still blank. I'm guessing this only works when using the background options built into ZVD and not the Windows background options?

**Comment by mzomparelli** [comment]
Yes, you need to set backgrounds in zVD for it to work in DesktopView.

For the spacing, you can try setting the window thumbnail width buffer. I added this in order to adjust for a scrollbar. This is probably why mine look more spaced than yours.

![image](https://user-images.githubusercontent.com/10564234/42130288-d65906e0-7ca5-11e8-9097-f1ceba6ff964.png)

**Comment by benz145** [comment]
Ah yes I see now. I've set it to 30 and it looks great! I also see that the thumbnail dragging is coming along nicely. Possible to animated the existing thumbnails downward to make room for the incoming thumbnail when dragging between columns? This sets up a clear indication to the user that the action of dropping the thumbnail into a new column is a valid action.

**Comment by mzomparelli** [comment]
I'm trying to get it to animate like you say. I'll do my best to make it work.

**Comment by mzomparelli** [comment]
I'm going to close this issue, however I will continue to improve the drag and drop functionality and animation.
