### ISSUE TITLE
Out of date releases / changelog

### ISSUE THREAD

**Issue by benz145** [mzomparelli/zVirtualDesktop#206]
Is there a reason that the latest release for ZVD on GitHub is from back in October 2017? I'm trying to find the best way to be able to tell when there's new updates. 

Also, is there a changelog hosted anywhere?

**Comment by mzomparelli** [comment]
Change log is built in to the program.

![image](https://user-images.githubusercontent.com/10564234/42524719-f3d93b0c-8436-11e8-813c-94430c76d795.png)

This project is no longer open source. If you're looking for the current build it can be found using this link.

https://zomp.co/Files.aspx?id=zVD

For the last code commit you can visit this fork, however it is old and doesn't have DesktopView and it doesn't use hooks for the hotkeys.

https://github.com/jan-glx/zVirtualDesktop


For updates, zVD will tell you when there is an update.

**Comment by mzomparelli** [comment]
I'm either going to remove all releases from GitHub or try to do a better job of uploading them. I haven't decided yet, but I am leaning toward removing them all. What do you think? Do you think GitHub browsers would prefer to find releases there or is the download button good enough?

**Comment by benz145** [comment]
Speaking as an end user, I usually navigate to the release section and look for the latest full release and find that to be a convenient location to look for changelogs.  If you plan on making GitHub your primary point of distribution, perhaps it would be best to have all the releases here in one place. Otherwise maybe point people toward a dedicated microsite and don't bother with releases here.

**Comment by mzomparelli** [comment]
I have created the final Github release that always points to the current version. This should eliminate any confusion on how to download.

https://github.com/mzomparelli/zVirtualDesktop/releases
