### ISSUE TITLE
Setting a background color on one desktop affects all desktops

### ISSUE THREAD

**Issue by JoelAzaria** [mzomparelli/zVirtualDesktop#208]
I set a background color on Desktop # 2 (only desktop #2.)  
Color change seems to have affected all desktops which is wrong behavior.

![image](https://user-images.githubusercontent.com/470908/43545224-4faf39cc-95a3-11e8-88bf-a16fb365bd29.png)

Also, I think DesktopView should show the background colors for the respective desktops when set.  Not a bug (more FR) but worth a mention here in case you're in that part of the code.

**Comment by mzomparelli** [comment]
I'm looking into this issue.

For DesktopView check out this checkbox. It uses color.

![image](https://user-images.githubusercontent.com/10564234/43553444-9e5e94bc-95b4-11e8-97c5-e25dce95992d.png)

**Comment by mzomparelli** [comment]
What's happening here is that when you switch to a desktop where the wallpaper has not been configured then nothing changes. What is your suggestion to this? Should I default to show desktop wallpaper 1 when no wallpaper is configured?

**Comment by JoelAzaria** [comment]
Depends.  What's the relationship between desktop 1 and the System wallpaper?  

If they are one and the same (ie desktop 1 is not independent - setting desk 1 changes System) then yes, default to desktop 1.
If System wallpaper is a separate entity then you should default to System so that Desk 1 can be and remain independently settable of the other vDesktops.

Optionally, I can envision a use-case for some users who would want desktop 1 to be/act as the default. (assuming desk 1 and System are not linked ofc.)  You could accommodate these users by either:

1. having a switch/checkbox to toggle this behavior between unset desks defaulting to System or desk1 or
1. just have these users set the System wallpaper to effect change on the unset/default desks' backgrounds
 

my 2c anyway..
