### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#209]
Hi, as you know zVD has become an integral part of my everyday computing life, and I have made myself somehow dependent on it. I am still experiencing unexplainable issues from time to time. Most are intermittent and difficult to reproduce. Like this one:
https://i.imgur.com/xVLyTJc.jpg
Here, the chain of events were approximately as follows;
1. changing desktops suddenly becomes increasingly sluggish.
2. zVD lacks behind on updating the desktop wallpaper
3. eventually, it fails to keep up alltogether
When I finally get to the desktop overview, it begins to fill each row with the same thumbnails. finally it crashes completely, and all I can do is to kill it using Task Manager.
After a fresh restart, everything is ok - for a while (a week or two), before things begin to go sour again.

I'm sorry that I cannot be of much help in pinpointing the actual cause or describe how it can be reproduced.

**Comment by mzomparelli** [comment]
Please obtain some more info when this happens.

While in Task Manager, before you kill zVD, get the below screen shot from the Details tab. You will have to add two column by right-clicking the header. (User Objects and GDI objects)

Also, please confirm the version you are running.

What you describe sounds like a memory leak in DesktopView.

![image](https://user-images.githubusercontent.com/10564234/43715350-d8bd5c76-9945-11e8-9348-a15d111d198f.png)

**Comment by oywino** [comment]
I will, but I'll have to wait until the next time it happens.

**Comment by mzomparelli** [comment]
I have confirmed there is a memory leak in DekstopView and I'm working on correcting it. Restarting the app will temporarily fix any issues caused by the leak.

**Comment by mzomparelli** [comment]
I figured out a big part of the memory leak and corrected it. There is still something else causing a leak, but it is almost insignificant. You can force an update now to get this build.
