### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#21]
I've made two sets for you to evaluate. They're not fancy at all, just plain'n'simple win10 style.
[Icon-9_1.zip](https://github.com/mzomparelli/zVirtualDesktop/files/893930/Icon-9_1.zip)
[Icon-9.zip](https://github.com/mzomparelli/zVirtualDesktop/files/893931/Icon-9.zip)

**Comment by mzomparelli** [comment]
Very nice! What would you like to name them?

**Comment by oywino** [comment]
The ones in 9_1 is called "Agency" and the ones in 9 is called "Narrow"

**Comment by mzomparelli** [comment]
These icons have been added. I will release version 1.0.10 soon.

**Comment by oywino** [comment]
Thanks for including my Icons. However, they did not quite look as I expected. I think I need some more guidelines. I used 128x128 size. The white border line becomes invisible. The Agent font is too small, and the Narrow font could also be larger, but not necessarily thicker. I was hoping to find the font MS used for the clock and date, and just frame it.

**Comment by mzomparelli** [comment]
128x128 might be too large. All of the ones I created are 32x32 or 48x48. I see if I can make a set to your liking with the clock font.

**Comment by oywino** [comment]
Thanks :-)
I'm leaving for Easter holiday now and will not be back before April 20, so it will be quiet from my side for a while. I wish you a nice Easter.

**Comment by mzomparelli** [comment]
Thank you! You have a nice Easter too!
