### ISSUE TITLE
Switching to different desktop immediately switches back

### ISSUE THREAD

**Issue by nicolasdejong** [mzomparelli/zVirtualDesktop#210]
This is probably caused by focusing the wrong window after switching.

It can be quite confusing because the background image change always lags for a second or two (4k screen, slow bg change, there's a ticket for that I think), so there is a lot of flashing and after a while you're back at the desktop you started at. Switching a second time generally works correctly (but by then I'm a mix of confused & annoyed).

My request would be to make the 'focus window on new desktop' optional via settings (unfortunately, because I love it when it works).

The basic idea of focusing a window on the desktop that was just switched to is sound. You would want to prevent typing in a window that is on a virtual screen that is not visible! Microsoft really made a mess of this virtual desktop paradigm (so fortunately we have zVirtualDesktop ;-))

Anyway, windows stealing focus is quite a problem in Windows anyway, as it is nicely described here:

https://news.ycombinator.com/item?id=13690732

**Comment by mzomparelli** [comment]
I've experienced the sudden jump back to the previous desktop when switching. I'm looking into this.

**Comment by mzomparelli** [comment]
I published changes that I think should help this.

**Comment by mzomparelli** [comment]
The recent update (1.0.92.0) should prevent this from happening. Let me know if you it persists in 1.0.92. So far I haven't seen it.

**Comment by nicolasdejong** [comment]
The update made things much worse for me. In two thirds of all cases the desktop switches back immediately (it was something like 10%). Sometimes a minimized window will open after switching.

So my request is to add an option in the configuration where for switching desktops the behavior is one of:
- don't focus a window (this option gives the guarantee there will never be a backflip)
- insert an alt-tab key event (this option I think should work most of the time)
- the current behavior, which I think tries to remember what window was active in the target deskop a time that desktop was left

This way you can continue to experiment with better ways to focus a window, while for those of us where it is not working correctly can choose to disable it. Or you make it a checkbox and I'll press alt-tab myself after the switch.

**Comment by mzomparelli** [comment]
I'm sorry you're having issues. I do like your solution for this and will work on making it configurable. I've made some additional tweaks in 1.0.92.2. Can you confirm this is still a major issue for you in the most updated version?

**Comment by mzomparelli** [comment]
Update to 1.0.92.3 and test it out.

![image](https://user-images.githubusercontent.com/10564234/50669014-46d76180-0f88-11e9-97ad-65c27b3bbdc3.png)

**Comment by nicolasdejong** [comment]
Thanks Michael, much appreciated. However I think something is wrong with this implementation because if I choose 'Do Nothing' I have constant backflips. The 'Send Alt+Tab' works much better for me, but I still have to do 'Alt+Tab' myself after the desktop switch since the window on the 'old' desktop is still focused. The 'Focus Last Window' works ok and didn't notice any backflips in the time I tested this.

If I would guess, the current implementation:

shows 'Do Nothing' but acts 'Focus Last Window'
shows 'Focus Last Window' but acts 'Send Alt+Tab'
shows 'Send Alt+Tab' but acts 'Do Nothing'

Perhaps it's a sorting thing? Even so, I now have a solution where switching desktops works perfectly again. Thanks!

**Comment by mzomparelli** [comment]
They aren't mixed up. If you are still seeing the backflip with Do Nothing set then I think something else might be causing this. I'm going to continue testing this. I'll let you know what I figure out.

**Comment by mzomparelli** [comment]
I'm seeing the immediate switch-back when switching desktops. I'll be looking into this further and hope to have a fix soon.

**Comment by mzomparelli** [comment]
I just published 1.0.92.5 to try and fix this issue. Only Windows 10 1809 is supported in this build while I continue to test.
