### ISSUE TITLE
App freezes on startup

### ISSUE THREAD

**Issue by jdmcfadden-usx** [mzomparelli/zVirtualDesktop#218]
Beginning with the last round of Windows updates (I'm not positive they're related, but the timing suggests they might be), the zVirtualDesktop has several times failed to start successfully but gets frozen in memory.

![image](https://user-images.githubusercontent.com/20133559/49448595-3eccac00-f7a7-11e8-8093-2df1d3993897.png)

When this occurs, the app is listed as in memory but suspended according to ProcessExplorer (see picture). I get access denied when I try to stop the app via ProcessExplorer. In some cases, I can't start a new instance of the app because I get a dialog telling me that the app is already running. In other cases, I can.

Looking through the Windows Application event log, I find this error:

Application: zVirtualDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at WindowsDesktop.Interop.IVirtualDesktopManagerInternal14328.GetDesktops()
   at WindowsDesktop.Interop.VirtualDesktopManagerInternal.GetDesktops()
   at WindowsDesktop.VirtualDesktop+<GetDesktopsInternal>d__22.MoveNext()
   at System.Linq.Buffer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToArray[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at WindowsDesktop.VirtualDesktop.GetDesktops()
   at zVirtualDesktop.GLOBALS..cctor()

Exception Info: System.TypeInitializationException
   at zVirtualDesktop.Program.InitializeApp()
   at zVirtualDesktop.Program.Main(System.String[])

zVD version is 1.0.91.0.

My OS information is below. Let me know if there's any other information you need.

OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17134 Build 17134
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	Dell Inc.
System Model	Latitude E6540
System Type	x64-based PC
System SKU	05BE
Processor	Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz, 2801 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. A16, 9/1/2015
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	Dell Inc.
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.17134.285"
Time Zone	Eastern Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	8.08 GB
Total Virtual Memory	18.3 GB
Available Virtual Memory	7.24 GB
Page File Space	2.38 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, DMA Protection
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not InstantGo, Un-allowed DMA capable bus/device(s) detected, Disabled by policy, TPM is not usable
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by mzomparelli** [comment]
Thanks for the detailed stack trace. I will look into this tonight.

**Comment by mzomparelli** [comment]
How often are you experiencing this since updating Windows?

**Comment by mzomparelli** [comment]
In looking at the stack trace in detail, it appears to be crashing while getting the number of desktops during the startup phase. I think I have a solution for this.

**Comment by mzomparelli** [comment]
I just published 1.0.91.1 that should fix that crash. I don't if this is related to the application hang on startup, but it probably is.

**Comment by jdmcfadden-usx** [comment]
It's happened about five or six times, but it doesn't happen every time. I'll force an update after 3 p.m. EST today (I will be rebooting then as I move from work to home). I can't get the suspended instance out of memory right now except by a reboot and I don't really have that much time until then. Thanks for the response.

**Comment by jdmcfadden-usx** [comment]
Updated to 1.0.91.1 and no problems so far. I will reopen ticket if problem reoccurs. Thanks for the quick turnaround.
