### ISSUE TITLE
What's your favorite icon theme?

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#22]
Mine is White Box and my second favorite is Numpad - White.

**Comment by enumag** [comment]
Blue because it's the easiest to read. Still though it's just a small icon - it would be far better to have the desktop number and icons of the applications briefly shown in an overlay upon switching.

**Comment by mzomparelli** [comment]
Thanks for the feedback. Would you mind creating a new issue to add the overlays? I like the idea!
