### ISSUE TITLE
zVirtualDesktop Updater runs indefinitely

### ISSUE THREAD

**Issue by jhickey86** [mzomparelli/zVirtualDesktop#220]
New Win 10 install. Tried running the zVD EXE and the updater dialog just runs over and over again. Noticed that the file size of the EXE fluctuates during this process, seems to go from zero to 1.7mb with every pass.

The zVD never starts and I have not found a way to get past the updater. After running the EXE once Windows won't let me run it again, doesn't work in Administrator mode either. I get a "Your PC can't run this app" notification. 

Occasionally if I re-extract the EXE I get "There was an error updating" and it immediately closes after dismissing the notification.

Win 10 Pro
Version 1809 (OS Build 17763.107)

**Comment by mzomparelli** [comment]
I published a faulty build for that Windows build last night. Sorry about that. Give it a try again and let me know if the issue persists.

**Comment by jhickey86** [comment]
Re-downloaded the EXE and it worked! Appears to be functioning normal now.

Appreciate your prompt response.

**Comment by mzomparelli** [comment]
Thanks for opening an issue for this. Anytime something goes wrong then open an issue. I usually respond and fix bugs quickly. Adding features is a little slower these days, but new stuff still gets added sometimes.
