### ISSUE TITLE
zVirtualDesktop does not work with Windows 1809 

### ISSUE THREAD

**Issue by jsonMartin** [mzomparelli/zVirtualDesktop#225]
Hello, I just upgraded to the newest version of Windows through Windows Update.

Now after the update, it won't open at all - it says zVirtualDesktop is incompatible with this version of windows:

![image](https://user-images.githubusercontent.com/4033621/50539550-be9c2b00-0b47-11e9-94c1-bfe50d063ca2.png)
![image](https://user-images.githubusercontent.com/4033621/50539554-d8d60900-0b47-11e9-97d2-e1f852a8ba56.png)

**Comment by mzomparelli** [comment]
It should automatically be downloading this version for you. I've got the same exact version of Windows as you.

https://zomp.co/Files.aspx?id=zVD1809

**Comment by mzomparelli** [comment]
@jsonMartin are you still having issues with this?

**Comment by mzomparelli** [comment]
I think maybe you had a corrupted exe. It could happen when downloading. If the issue persists please reopen this issue or create a new one.

**Comment by jsonMartin** [comment]
@mzomparelli Ah ok, it just didn't auto update but I just got a chance to try the link you provided and it seems to be working for me. Thanks!

**Comment by mzomparelli** [comment]
That’s great to hear. Open a new issue if you have any problems.
