### ISSUE TITLE
Computer must be registered for 10 days before being unregistered

### ISSUE THREAD

**Issue by dsp0105** [mzomparelli/zVirtualDesktop#228]
Could you please remove that restriction - I was trying to setup a new computer and activated my license on that. But that computer has some other issues, so I am going back to my old PC, but I cant deactivate zVD on new comp due to the above error.

**Comment by mzomparelli** [comment]
This is to prevent someone from transferring from there work PC to their home PC every day. I can help you out by removing the one you don't want. Shoot me an email @ zVirtualDesktop@gmail.com with the name of the computer you want to remove.

**Comment by dsp0105** [comment]
Thanks Michael, sent the mail.

**Comment by mzomparelli** [comment]
Your request has been completed.

**Comment by dsp0105** [comment]
Thanks!
