### ISSUE TITLE
Keyboard hook stops working after a while and crashes when disabled

### ISSUE THREAD

**Issue by nicolasdejong** [mzomparelli/zVirtualDesktop#231]
After a while the keyboard shortcuts set in zVirtualDesktop are not working anymore. When I then go to 'other settings' and disable the keyboard hook (with the intention to re-enable it) it leads to a crash.

This is not a fluke but regularly recurring. I can then restart the app and all is well, until after a few days the same occurs again. I use the keyboard-shortcuts extensively (moving to other desktops, changing volume, skipping songs) so notice it quite quickly.

I didn't change any of my settings since half a year or so, and this behavior is something of the last month or two I think, so it seems it was introduced recently.

**Comment by mzomparelli** [comment]
Sounds like zVD is getting kicked out of the hook chain on you computer. I haven't noticed this myself, but I will watch for it and investigate. Do you have any pending Windows updates? Sometimes that can cause undesired results

**Comment by mzomparelli** [comment]
Can you post the call stack from the crash? Would be found in the Windows Event Viewer.

**Comment by nicolasdejong** [comment]
Faulting application name: zVirtualDesktop.exe, version: 1.0.92.3, time stamp: 0x5c2eacdf
Faulting module name: KERNELBASE.dll, version: 10.0.16299.820, time stamp: 0x917adac5
Exception code: 0xe0434352
Fault offset: 0x001045a2
Faulting process id: 0x6ff8
Faulting application start time: 0x01d4b34989abf3ab
Faulting application path: C:\Various\zVirtualDesktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 754fc540-9265-4e0b-a9ab-720c05e19d7a
Faulting package full name: 
Faulting package-relative application ID: 

Not very helpful, I'm afraid. The logs of the other crashes look very similar.

**Comment by mzomparelli** [comment]
There should be another record that has a stack trace. Some of the stack trace will be jumbled due to obfuscation, but I should be able to make sense of it.

**Comment by nicolasdejong** [comment]
Yes. I should've looked a bit further. Here is another one that includes the stack trace:

Application: zVirtualDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at zVirtualDesktop.HookManager.NWfliDIXWT()
   at zVirtualDesktop.HookManager.FKlB9cwkhdWClRiGDL1()
   at zVirtualDesktop.HookManager.NXJlqgjGab()
   at zVirtualDesktop.HookManager.DPw2Agw07Y5uyEku4kL()
   at zVirtualDesktop.HookManager.remove_KeyUp(System.Windows.Forms.KeyEventHandler)
   at WexiKII3HaBnX2Z3voC.KBvy3sIIbET8MHWn0kl.JrpX5kuGmBbILPK8Fky(System.Object)
   at WexiKII3HaBnX2Z3voC.KBvy3sIIbET8MHWn0kl.sbtFCSG7QX()
   at WexiKII3HaBnX2Z3voC.KBvy3sIIbET8MHWn0kl+rGCwp83K42aw66X121G.uRyQmK5ario7EebK96an()
   at WexiKII3HaBnX2Z3voC.KBvy3sIIbET8MHWn0kl+rGCwp83K42aw66X121G.S7qQzgH8Au()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by mzomparelli** [comment]
Yep, that's what I am looking for. Thanks!

**Comment by mzomparelli** [comment]
I wasn't able to identify a cause for this issue. However, I have implemented something that should prevent it from crashing when you try to restart the hook.

My thoughts on this issue is that Windows is dropping zVD from the hook chain for some reason. If possible, try to gather more info that could help me. Like maybe it happens after heavy CPU use. This is possible because if you have other software taking all processing then zVD will be unable to respond to the hook chain thus Windows will disconnect it.

**Comment by nicolasdejong** [comment]
I'm not sure, but it may have happened several times after resuming the suspended machine. Also McAfee (mandatory unfortunately on the work laptop) sometimes asks so much that it brings the machine to a crawl for a few seconds (even the music screeches), so that may have something to do with it. I've set the priority of zVirtualDesktop to 'high'. Lets see if it happens again.

**Comment by mzomparelli** [comment]
I have experienced this issue and the fix for the crash when disabling the hooks does indeed work. That's the solution until I figure out how to identify when the hook has been disconnected.

**Comment by nicolasdejong** [comment]
I think for me it only happens after a resume from standby. And then only one in four times or so. So no big issue, especially if it no longer crashes when resetting the keyboard hook.

**Comment by mzomparelli** [comment]
This should be fixed in current build.
