### ISSUE TITLE
Update readme to clearly indicate program requires paid license after trial period.

### ISSUE THREAD

**Issue by tasonosenshi** [mzomparelli/zVirtualDesktop#232]
I've just found this program after searching for a while for a better way to manage all of my windows for my university studies.  I previously was using the now defunct [Windows 10 Virtual Desktop Enhancer](https://github.com/sdias/win-10-virtual-desktop-enhancer).
    
I noticed a weird download link for this program and checked the versions/tags pages to make sure it was right.  When I opened the application it informed me that it was only a 10 day trial before requiring a license, which apparently costs $30 for one machine?  Honestly I feel bait-and-switched.  Had I known that before downloading I might have been more okay with it, but now I don't even want to trial the program.

Please update the project readme to clearly indicate that this program is a 10 day trial only before requiring a license fee.

**Comment by mzomparelli** [comment]
I'm sorry that you were misled and I will update the readme to state at the top that it is a trial and that a license must be purchased to continue using.

I hope you'll still give it chance as it is a very useful utility. If you do, please don't hesitate provide additional feedback. I really appreciate it.

**Comment by mzomparelli** [comment]
The read me has been updated. Feel free to open another issue or send me an email at zVirtualDesktop@gmail.com

Thanks!
