### ISSUE TITLE
Mouse hook doesn't 'hook-in' after reboot

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#236]
I'm on 1.0.93.0 and noticed that after PC reboot, the mouse hook fails until I manually do a deselect/apply/select/apply of the mouse hook box.
No big thing - just wanted to mention it.

**Comment by mzomparelli** [comment]
thanks for this info. I'll try to create a mechanism to detect if the hooks are working. If I can detect it then I can just restart the hook like you are, but automatically.

**Comment by mzomparelli** [comment]
This should be resolved with current build.
