### ISSUE TITLE
Hotkeys not working after Windows 10 1903 Update RPC Server issue?

### ISSUE THREAD

**Issue by bpluly** [mzomparelli/zVirtualDesktop#239]
After updating the second 1903 Update, Hotkeys stopped completely.
One of the significant elements of this update was handling the BlueKeep vulnerability with RPC.
In the log for around the right date (3rd July) I have the line:

'The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)'

**Comment by mzomparelli** [comment]
It’s going to be about a week or so before I can address this issue. It sounds like the VirtualDesktop interface has changed and will be an easy fix.

**Comment by bpluly** [comment]
Ta
I meant to acknowledge this at the time.

**Comment by mzomparelli** [comment]
I'm not having any issues with 1903. Do you have a different build than me?

![image](https://user-images.githubusercontent.com/10564234/61175041-99fd2300-a56e-11e9-8eb5-9d7d8140f511.png)

**Comment by bpluly** [comment]
It's exactly the same. :-(. I'll see if I can get any more information, it might be coincidental with 1903 but the RPC Server error is significant. I'll start there and work backwards.

**Comment by mzomparelli** [comment]
Do you have an update to this? I'm still not seeing any issues. Make sure you  have the keyboard hook enabled in zVD Settings/More Settings

**Comment by bpluly** [comment]
The hook runs for some time and then disappears with, for example, Ctrl Wnd #, moving to the tab number # in Firefox. This might be complicated by running something else that takes the keyboard hook and doesn't put it back, NVIDIA is the most likely. 

To figure it out I really need to debug the chain of hooks which mean uncovering the archaeological skills I had some long time ago. 

I don't mind it being closed in the meantime I'll create a new issue and reference this one if I ever get any more evidence.

Ta

**Comment by mzomparelli** [comment]
A hotkey manager should swallow the hook event if it handles it. Otherwise keystrokes would get through to other apps that should not because they are a hotkey that was handled.

If Nvidia is using a hook and it has the hook before zVD then it could be swallowing the event. Check the Nvidia settings and remove hotkeys you want to use in zVD.

**Comment by mzomparelli** [comment]
Until I we decide anything else, I'm going to mark this as Software Conflict

**Comment by bpluly** [comment]
That's fair.

**Comment by bpluly** [comment]
I've pretty much isolated this to Nvidia GeForce Experience.

**Comment by mzomparelli** [comment]
I have that application. Give me more details to your hotkeys and what you're trying to do and I'll try to help.

**Comment by bpluly** [comment]
It's all just standard hotkeys I haven't changed any mapping. There's probably a third leg to this but as long as I don't run anything that uses it, like games it's fine. 

At first I thought it was Firefox or an extension as the Ctrl-Wnd-n chords become got to Tab n in Firefox but that looks like a red herring.

**Comment by mzomparelli** [comment]
I'm on 1909 now and I'm also testing insider builds and I'm not having any issues. Reopen a new issue if you continue to have problems and you think it is zVD.
