### ISSUE TITLE
Trial user: can't get to settings

### ISSUE THREAD

**Issue by howardgrams** [mzomparelli/zVirtualDesktop#241]
I have just installed zVirtualdesktop for a trial, but I can't get to the settings menu.  (Win 10-64 Pro 1903).  When I right click on the icon and then click on zVirtualdesktop settings, I get a pop-up saying
An error occurred showing the settings window. See aditional details below.
Object reference not set to an instance of an object.
zVirtualdesktop::includeDic
![zVirtualdesktop](https://user-images.githubusercontent.com/49214395/61176693-510b9580-a593-11e9-8416-5ab671eeb3cd.jpg)

**Comment by mzomparelli** [comment]
Try deleting the settings file located in %%AppData%%\zVirtualDesktop

Maybe back it up first

**Comment by mzomparelli** [comment]
Can you let me know if this solved your issue? Please reopen this issue if not.
