### ISSUE TITLE
Loosing Mouse Hook randomly

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#244]
Some time ago, I began loosing the mouse hook feature randomly. First, only now and then, but as time goes by - increasingly more often. Now it happens almost ever other day.
Every time, I have to launch the settings page and disable/re-enable the mouse hook, and it begins working again.
As far as I know, I have - and never had any other software that use the same button. I do not play games on my computer.
This issue is becoming annoying.... I was hoping you had a solution?

**Comment by mzomparelli** [comment]
I’m disappointed to hear that zVD is annoying you. I think I have a potential solution to for this, but it will require compiling. I’m opening the project now.

**Comment by mzomparelli** [comment]
I just published 1.0.93.2 that should resolve this. However, if this doesn't work then I have another thing I can try, but what I have is better and should work. Try it out and let me know if the issue persists.

**Comment by oywino** [comment]
Hi,

I installed 1.0.93.2 on Tuesday, and so far it's been ok.
Thanks for your support.

Rgds
Oyvind

September 24, 2019 7:07 AM, "Michael Zomparelli" <notifications@github.com (mailto:notifications@github.com?to=%22Michael%20Zomparelli%22%20<notifications@github.com>)> wrote:
	I just published 1.0.93.2 that should resolve this. However, if this doesn't work then I have another thing I can try, but what I have is better and should work. Try it out and let me know if the issue persists.

**Comment by mzomparelli** [comment]
I'm going to mark as resolved, but I'll leave the issue open for a little while in case you experience the issue again.

**Comment by mzomparelli** [comment]
This may not be resolved. I may have just experienced something similar except it was the keyboard hook. To be fair, I only added code to handle the mouse part so you may not notice for a while. However, I'm testing a different solution for both the keyboard and mouse hook. I'll be testing for a couple of days and if everything works fine I will publish as 1.0.93.3.

**Comment by wdscxsj** [comment]
@mzomparelli Would you please add a new GitHub release when a new version is available? Thus one who "watches the releases" can receive a notification email, with no need to run update checks. Thanks.

**Comment by oywino** [comment]
I have experienced the issue again, but much less frequent than before. I am unable to see a pattern or a particular situation causing it.

**Comment by mzomparelli** [comment]
I don't usually publish revision releases, but I will in this case. I've been testing with 1.0.93.3 and I have not experienced the mouse or keyboard hook not working since. I will publish this build later today.

**Comment by mzomparelli** [comment]
I just published 1.0.93.3 as I said I would. There is a slight change to the version you tested and I think this will resolve the issue. Let me know if the issue persists. I will continue to watch for it myself.

https://github.com/mzomparelli/zVirtualDesktop/releases/tag/1.0.93.3

**Comment by oywino** [comment]
Hi,
I think that 1.0.93.4 is slower, more "jumpy" and often the desktop background update is lagging behind, more than on 1.0.93.2 (I never managed to find 1.0.93.3)
Am I right?

**Comment by mzomparelli** [comment]
I quickly changed something else hook related so 1.0.93.3 was quickly replaced with 1.0.93.4

You should not see any difference in performance. The only thing that I can think of that would have affected performance would be the obfuscation routine. This is done on the fly and changes with every compilation. Let me review the settings to see if I can reduce the flow complexity it adds.

I will look into this and publish another version. In the meantime, try restarting your machine.

**Comment by mzomparelli** [comment]
Let me know if you still have this issue. It seems good for me.

**Comment by oywino** [comment]
It's been stable since we last talked. 
Good work Michael 👍
