### ISSUE TITLE
Feature request: option to disable ClipboardEx

### ISSUE THREAD

**Issue by wdscxsj** [mzomparelli/zVirtualDesktop#246]
Is it possible to add an option to turn off ClipboardEx? It seems that the clipboard history feature introduced in Windows 10 1809 makes it largely redundant. I like the idea of doing less things and doing them well (and saving the memory a little bit). Thanks.

**Comment by mzomparelli** [comment]
ClipboardEx is disabled by removing all hotkeys related to it.

**Comment by wdscxsj** [comment]
I see, thank you. :)
