### ISSUE TITLE
Bitdefender identified latest version as virus

### ISSUE THREAD

**Issue by maximojoexpress** [mzomparelli/zVirtualDesktop#251]
I attempted to install the latest exe and Bitdefender blocked it immediately. I see this is a known issue in the past depending on the build. Has anyone else had this happen to them recently? 

This was on Windows 10.

**Comment by mzomparelli** [comment]
Sorry you are having issues. I scanned the downloadable executables with Virus Total and it came back with 2, but Bit Defender not one of them. Nonetheless, it should not be triggered by any. I think maybe it has something to do with the obfuscation tool I'm using. I'll look into it and try creating new builds in the coming days.

**Comment by maximojoexpress** [comment]
Hi again, unfortunately this is still an issue with the latest version of BitDefender and zVirtualDesktop.

![image](https://user-images.githubusercontent.com/17994986/80540128-11ac1980-89ec-11ea-915a-01ec8422d88a.png)

**Comment by mzomparelli** [comment]
I'll install BitDefender and test it out

**Comment by mzomparelli** [comment]
Where are you downloading zVD from? What is the version number?

I just installed BitDefender in a VM and have a 30 day trial. I then copied zVD in and scanned the file. The scan reported no threat. I then executed zVD and everything works fine.

![image](https://user-images.githubusercontent.com/10564234/80544682-2dc1a380-8977-11ea-9a38-2f31f6524c5d.png)

**Comment by maximojoexpress** [comment]
Downloaded the latest release [from here](https://github.com/mzomparelli/zVirtualDesktop/releases). Make sure you Update Now to the latest virus stuff through the task tray icon. Yes I can scan the exe too and it's fine but it's when you run it that the problem occurs. It puts the exe in quarantine. FYI I have the paid version which may be the difference.

Make sure you have all the protection features turned on.

![image](https://user-images.githubusercontent.com/17994986/80545840-9fd9cd00-89f7-11ea-96da-2e9eb70de480.png)

**Comment by mzomparelli** [comment]
My version should be up to date and complete during the trial. If it fails to pick up threats in trial mode then what good would it be.

I have it running fine in a VM with BitDefender. I can't purchase BitDefender for the purposes of testing.

Please make sure you download directly from https://zVirtualDesktop.com

**Comment by mzomparelli** [comment]
![image](https://user-images.githubusercontent.com/10564234/80547173-2a311b00-897d-11ea-8e14-58d0399c95b1.png)

**Comment by maximojoexpress** [comment]
I downloaded it directly from your site, still the exact same problem. I'm on Windows 10 2004 if that helps. It's an insider build but due out in a month or so. Might want to try it on that build to see if the problem occurs (if you aren't already).

**Comment by maximojoexpress** [comment]
Added an except in BitDefender for it and now I get this. Maybe it's 2004.

![image](https://user-images.githubusercontent.com/17994986/80547492-b550f600-89fb-11ea-8557-733aa5a4459f.png)

**Comment by mzomparelli** [comment]
I have an Insider Build VM that I test with, but it does not have BitDefender. What happens if you send the file to VirusTotal.com?

**Comment by maximojoexpress** [comment]
"2 engines detected this file" though not BitDefender.

https://www.virustotal.com/gui/file/e66179a6623ac9f3d2e25a1670232e38c939b14704623c917d288648502fb9ee/detection

**Comment by maximojoexpress** [comment]
But I don't think the scanning is the problem, it's more it's behavior when it runs where BitDefender detects something it thinks is nefarious.

**Comment by mzomparelli** [comment]
can you zip and email me the exe? zVirtualDesktop@gmail.com

**Comment by maximojoexpress** [comment]
Will do. I will send you the exact one below after I restore it from quarantine.

![image](https://user-images.githubusercontent.com/17994986/80555368-70d15480-8a13-11ea-8db5-7fcb7c9bbe8b.png)

**Comment by mzomparelli** [comment]
We solved this. BitDefender does not like zVD extracting its updated from within itself. I doubt I'm going to change this anytime soon so for now you'll have to update manually or add a BitDefender rule to allow it.
