### ISSUE TITLE
Always on Top functionality

### ISSUE THREAD

**Issue by SHHSSH** [mzomparelli/zVirtualDesktop#252]
Is this a potential feature by any chance?

We could utilise something as simple as the pin Alt+Win+Z/A to toggle windows on and off from always on top.

This provides a rather efficient flow of switching a window (e.g; cmd prompt) from one desktop to another to work with by throwing it on top of say a fullscreen browser. There are programs like AutoSizer that I sometimes use in conjunction to work around this. But I believe it would be a great feature.

Thanks,

Noah.

**Comment by mzomparelli** [comment]
Yes, this already exists. You can create a hotkey or right-click a thumbnail in DesktopView.

![image](https://user-images.githubusercontent.com/10564234/70146776-8317b400-1668-11ea-87b5-d28d9d01a72d.png)

**Comment by SHHSSH** [comment]
Thanks!
