### ISSUE TITLE
What can't the registration stick once and for all?

### ISSUE THREAD

**Issue by djrobby** [mzomparelli/zVirtualDesktop#258]
I purchased my license 6/26/2019 and since then, I've had to remove and re-register the EXACT SAME PC approximately 3 times. It's a little frustrating becuase every time this happens, I have to: 

1) look through buried email to find registration info and 
2) go through the process of unregistering and re-registering the same computer! 

Also, why isn't there a website where we can manage our account instead of always having to login through your software? I know a lot of folks (including myself) use password managers these days and logging in through your software is cumbersome becuase it's not a browser...even though your login/account administration looks like a .NET browser component!

**Comment by mzomparelli** [comment]
I'm really sorry for this. The license will stick. This was the result of me having to change something in the licensing logic. I don't foresee the need to do this again so your license should stick going forward.

You will be happy to know that I am working on bringing the account management to the website. I don't know when this will be completed so please stay tuned.

**Comment by mzomparelli** [comment]
Also, as a recommendation, maybe you can store all the zVD info in your password manager for easier access. This should allow you to store notes too where you could put the keycode. You might even be able to attach the actual email receipt to the record in your password manager as well.

**Comment by bpluly** [comment]
Ah I should have checked issues before emailing, it's just that's it's happened almost on the 12 month anniversary and not happened before.

**Comment by mzomparelli** [comment]
It looks like you got this figured out. I'm really sorry for the inconvenience.

**Comment by bpluly** [comment]
> 
> 
> It looks like you got this figured out. I'm really sorry for the inconvenience.

No problem, I created a new key before re-registering as that seemed a Good Thing to do, and probably where you've made the change.

**Comment by djrobby** [comment]
Thanks for the update @mzomparelli. Considering this is now resolved, I'll go ahead and close this issue. Please let us know once the web based account management is up!

**Comment by mzomparelli** [comment]
@djrobby sorry, forgot to come back and let you know the web-based account management is mostly functional. It's missing a few things like the ability to change password, but I will get around to that at some point. If you ever need a password reset then just send me an email. I have an automated way of issuing a new password from the site, but not on user pages yet.

Let me know if you have any issues.

https://zvirtualdesktop.com
