### ISSUE TITLE
New version makes many window thumbnails appear blank

### ISSUE THREAD

**Issue by benz145** [mzomparelli/zVirtualDesktop#260]
Running the latest version (April 2nd, 1.0.95), I like the change to the thumbnail aspect ratio and that ZVD appears where your mouse is.

However this version seems to have introduced a bug where many of the thumbnails appear blank (see attached photo). 

It seems that all but the topmost thumbnail on each monitor tend to go blank. If I make active one of the blank applications, eventually I can get the thumbnail to show correctly, but then one of the lower thumbnails will become blank. Hard to tell exactly what's going on.

![zvd bug](https://user-images.githubusercontent.com/12601485/80754911-bb6ed180-8ae4-11ea-92e9-a38efc43b542.png)

**Comment by mzomparelli** [comment]
this is happening for minimized windows. I'm looking for a solution to this. However this is not a new issue. Can you let me know if it's because they are minimized?

**Comment by benz145** [comment]
None of the windows are minimized. Attaching a video here to try to demonstrate the behavior. Seems like when I make an application active, the first open of ZVD does not show the thumbnail, but the second open does -- at which point, the previous active application goes blank. (FYI, some of the applications I'm clicking on are becoming active on my other monitor but it may look like they aren't appearing correctly in the video -- AFAICS, this doesn't seem to relate to which monitor the applications are on).

https://gfycat.com/niftyvaguedogfish

**Comment by mzomparelli** [comment]
Have you tried restarting your computer?

Another thing to try is running zVD as admin.

Let me know if either of those help.

**Comment by benz145** [comment]
I tried both but neither solved the problem.

**Comment by benz145** [comment]
Any word on this bug? It has made the app much less usable for me, since I rely a lot on the thumbnails to quickly identify which window I'm looking for.

**Comment by mzomparelli** [comment]
This is weird. You might be the only one having this issue. What Win10 version and zVD version? Can you share a list of running processes so I can try to rule out software conflicts?

**Comment by benz145** [comment]
Still happening after various restarts and updates of Windows : (

I'm on Windows 10 1909 (18363.959) and ZVD 1.0.95.5. 

A list of running processes is attached:

[processes.txt](https://github.com/mzomparelli/zVirtualDesktop/files/4962585/processes.txt)

**Comment by benz145** [comment]
I'd really love to track down this bug. It's very much hampering the usefulness of ZVD for me since I can't see the thumbnails and have to guess if I'm clicking on the right window when the window names are not descriptive.

Edit: Opps.. looks I had accidentally clicked 'Close Issue' but didn't mean to.

**Comment by mzomparelli** [comment]
Are you running Win10 2004 yet? I reviewed your process list and nothing stands out. I can even see the issue in your video, but it's not clear what would cause it. I'm using DWM and I do see that you have that exe running. Reviewing the code does not shed any additional light into what is causing your issue.

**Comment by mzomparelli** [comment]
Does the log file show any exceptions? I see that I am logging exceptions when trying to get the thumbnail.

**Comment by benz145** [comment]
Finally on Windows 2004 and unfortunately it's still happening. Here's the log file.
[zVirtualDesktop_Log.zip](https://github.com/mzomparelli/zVirtualDesktop/files/5520261/zVirtualDesktop_Log.zip)

**Comment by mzomparelli** [comment]
Do you still have these processes?

![image](https://user-images.githubusercontent.com/10564234/98751342-93aad100-2385-11eb-81dc-da5495c266cd.png)

Specifically lghub.exe sounds suspicious because there are multiple and based on this user it might be compromised.

![image](https://user-images.githubusercontent.com/10564234/98751418-aae9be80-2385-11eb-965a-767bfabbe649.png)
https://www.file.net/process/lghub.exe.html

**Comment by mzomparelli** [comment]
I would say start a VM and install software one by one until the issue shows itself. So far, you're the only one with this issue so it has to be a software conflict.

**Comment by mnakamuramx** [comment]
I'm observing this issue on Windows 11, zVD 1.0.98.3. The very first time the Desktop View is shown upon running zVD, thumbnails are all correct, but after a few desktop switches, some thumbnails go blank.

![2022-01-18 18 34 34 REFORMA - Periodismo independi](https://user-images.githubusercontent.com/84426377/150041440-08e1c745-7c5c-4288-b857-34c5aa9be7fb.png)

**Comment by mzomparelli** [comment]
I just published 1.0.98.6 that should fix the thumbnail issue. Please let me know if the issue still persists for you.

Sorry for the delay in fixing this. The issue didn't happen to me until I got my new PC. The odd thing was it didn't start right away. It only started last night. Anyway, it was the exact issue you guys said and I was able to track it down now that I was able to see it.

**Comment by mzomparelli** [comment]
@mnakamuramx I noticed in your screenshot the header row is kind of small and cutting off the pin text. Did you know that you can adjust the size of the header and the font size?

![image](https://user-images.githubusercontent.com/10564234/151712915-d94d74cf-d8d4-4082-b4bc-b83eb3bca635.png)

**Comment by mnakamuramx** [comment]
It appears to be fixed. Thank you. It used to be that the very first time the desktop view was invoked, thumbnails looked fine, and they went bad after a few desktop switches. I have now switched several times and the thumbnails look fine.

**Comment by benz145** [comment]
Still broken for me on Windows 10 (21H1, 19043.1706). Running ZVD 1.0.98.3.

![image](https://user-images.githubusercontent.com/12601485/172491085-812fd30a-d63f-449c-a29b-0e10899a6706.png)

**Comment by benz145** [comment]
Wow so apparently my ZVD got stuck thinking it was up to the latest version, but using Force Update pulled down the latest and now it *appears* to be fixed! I'm so happy to have this fixed, thank you! Fingers crossed it stays this way 😬

**Comment by mzomparelli** [comment]
No actually you only get a notification for minor releases and not the individual builds. This allows me to to publish a build and await feedback before I publish to the masses. You have figured out that the force update will always grab the most recent build.

**Comment by mzomparelli** [comment]
I'm so surprised it fixed the issue from 1.0.98.3 to 1.0.98.11. Nothing with desktopview has been modified.

**Comment by mzomparelli** [comment]
it is about time I push 1.0.99.0 to the masses

**Comment by benz145** [comment]
Oh man I just keep looking at it and it's so much easier to tell what I'm looking for now 😅. Thanks for tracking this one down.

What's the best way to support you if I already own the software? Just buy another key?

**Comment by mzomparelli** [comment]
Just buying another key is best unless you want to actually donate? I think the fees are less. I really appreciate the support. I really love that you all like my app so much. 

This is me, or you can buy more licenses you get something too. Really you don't have to though, but I appreciate it.

https://www.paypal.com/paypalme/michaelzomparelli

**Comment by benz145** [comment]
I bought an extra key hoping to give it away, but I see it is tied to my account. Is it possible to give the key away to someone else?

**Comment by mzomparelli** [comment]
Sure, send me the email address of the person you want to have and I will generate an account for them.

**Comment by benz145** [comment]
I was going to give it away to whoever could claim it alongside a ZVD shout-out on twitter 😅. If it's not possible with your account/key system, I understand and I'll try to get the email of whomever wants it.

**Comment by mzomparelli** [comment]
Yeah sorry, not support that but I like the idea so I'll probably make some tweaks. For now your shout out might still work. Just ask the winner for their email. If you do the shoutout I will give 1 in 25 retweets or 1 in every 50 replies a free license and you can give yours away if you want. I'm curious how many replies you get. Can you see who retweets your stuff? I just pulled those number out of thin air. feel free to suggest something else. I like the idea of a giveaway though.

**Comment by mzomparelli** [comment]
how many twitter followers do you have? I need more marketing.

**Comment by benz145** [comment]
That's awesome! Since it's a fairly niche piece of software I don't know how much traction it will get but we'll see. Yes you can see who has retweeted/replies, and you can select randomly from that list and ask for their email to claim their key for as many as you'd like to give away.

**Comment by benz145** [comment]
I'll shoot you an email for a little more coordination.
