### ISSUE TITLE
Auto close when opening

### ISSUE THREAD

**Issue by l13rb4git** [mzomparelli/zVirtualDesktop#261]
I was using this program for about one week, but today it stop working. I can't start the program.

Here is the log message: 

`24/06/2020 15:29:17,Program Started,,,frmMain,,
24/06/2020 15:29:17,Program Exited,"Icon Theme: Green, DesktopView Count: 0, Pin Count: 0, Move Count: 0, NavigateCount: 0, Hotkey Trigger Count: 0",,frmMain,,`

**Comment by l13rb4git** [comment]
I've already deleted the config file and the problem persists.

**Comment by mzomparelli** [comment]
What version are you running? If not 1.0.95.3 then please try downloading and running that version and let me know if that solves your issue. Also, could you let me know your computer name. If you don't want to post it here then you can email it to me @ zVirtualDesktop@gmail.com
