### ISSUE TITLE
standard task view

### ISSUE THREAD

**Issue by KB3168** [mzomparelli/zVirtualDesktop#263]
can you put a switch to use the standard task view?

**Comment by mzomparelli** [comment]
You can still use the Task View button on the taskbar. You can also change the desktop view hotkey to something different so that win+tab opens Task View.

**Comment by mzomparelli** [comment]
Are you looking to be able to create a custom hotkey to open the default Task View?

**Comment by KB3168** [comment]
Yes, I've seen that and it's ok.Thank you vert much.Il 11 lug 2020 18:57, Michael Zomparelli <notifications@github.com> ha scritto:
Are you looking to be able to create a custom hotkey to open the default Task View?
