### ISSUE TITLE
zVD network access for license verification 

### ISSUE THREAD

**Issue by dev169** [mzomparelli/zVirtualDesktop#264]
Hello,

First of all many thanks for your efforts, you've done a great job. So much so that I've bought myself a license.

I was wondering what the situation is regarding internet access after the license has been validated. It looks like zVD periodically tries to connect to the license server, and after a few unsuccessful attempts complains and quits, forcing me to manually run it again.

Is it expected that the system should always be connected to the internet for zVD to work even after the license has been validated initially? Or maybe there is some issue with my setup specifically? I am on v1.0.95.3, Windows 10 2004 if it makes any difference.

**Comment by mzomparelli** [comment]
I do have it check periodically to help prevent license abuse. If a valid local license is found then I was suppose to be postponing the check for 2 days but I noticed that I’m only doing  5 hours. If it fails that check 5 times it will shutdown. I will do a little more work on this part and hopefully have a better process in the next update.

**Comment by dev169** [comment]
Thanks for the prompt reply and for looking into this.

At least in my case it happens more often than every 5 hours, it looks like once every hour. I've attached a log to better illustrate this. I do think the fact that the program exits if it can't periodically touch base should be noted as a limitation somewhere, alongside the IPs that are being used (for whitelisting).

In an ideal world I would prefer this check to happen only when I am installing zVD. You can potentially fingerprint the device, and when/if the license is verified add the fingerprint to my account or deny the activation if I'm over the number of allowed devices. I can't think of any downsides with this approach.

![image](https://user-images.githubusercontent.com/5874526/86909845-a5971180-c110-11ea-837b-013a91b2a6f8.png)

**Comment by mzomparelli** [comment]
In my next update I will eliminate the check on my server for license validation. In doing so, in order to prevent abuse of the licensing, I will only allow you to unregister a computer from the registered computer itself. You'll still be able to contact me directly to unregister a computer in case you are unable to do so.

**Comment by dev169** [comment]
I think that sounds great! I'll be keeping an eye out for the next version. Many thanks.

**Comment by mzomparelli** [comment]
Please test 1.0.95.5. If your machine has a valid local license then it will bypass the activation server. I'm still tinkering with this and I might make additional changes before pushing out a major version.

**Comment by mzomparelli** [comment]
Offline activation is now available in 1.0.96.0
