### ISSUE TITLE
Application immediately stops running

### ISSUE THREAD

**Issue by TomeASilva** [mzomparelli/zVirtualDesktop#271]
I'm Windows 10, version 1909, 
build 18363.1198

As soon as I open the app it immediately stops running, without throwing any error

**Comment by mzomparelli** [comment]
Yeah something going on with this obfuscation tool I'm using. Some builds run and some don't. I just published all new builds. Hopefully this goes away with a different obfuscation tool. Let me know if the current builds are still having issues.

**Comment by mzomparelli** [comment]
I discovered a bug in the update for the obfuscation tool I'm using. I have reverted to the previous version of the tool and created all new builds.

**Comment by mzomparelli** [comment]
I'm going to close this as reverting to the previous version of the obfuscation tool should solve this. If still and issue please reopen this.
