### ISSUE TITLE
New version - broke ZVD

### ISSUE THREAD

**Issue by dsp0105** [mzomparelli/zVirtualDesktop#272]
After updating to new version, zVD doesnt work - nothing happens  - multiple restarts of system/zVD, still  zVD doesnt run, new update complete broke it :(

(Ver 1809)

**Comment by mzomparelli** [comment]
I had a bad batch of builds due to an update with the obfuscator tool I use. All of this should have been fixed last night. You may have downloaded one of the bad builds. Can you try downloading directly from zVirtualDesktop.com and let me know if it works. If not, I'll make new builds right away.

**Comment by mzomparelli** [comment]
I did publish a new 1809 build. Should be good now.

**Comment by dsp0105** [comment]
Thanks, updated to the latest it is working now
