### ISSUE TITLE
Unable to open zVirtualDesktop settings upon right clicking tray icon

### ISSUE THREAD

**Issue by samwzlim** [mzomparelli/zVirtualDesktop#274]
This was working fine yesterday when I first downloaded it, but now when I try to access settings from right clicking the tray icon, a new instance of zVirtualDesktop settings opens in the taskbar but is not visible on the screen. As a result, I am not able to change anything. The weird thing is that it's present in both task view and desktop view but I can't see it on the desktop

![image](https://user-images.githubusercontent.com/74489037/105046503-219ce980-5aa4-11eb-80e4-9a4aa36262ac.png)

**Comment by mzomparelli** [comment]
yeah, I have code in there is that is supposed to remember where you put the window. I'm going to remove that code.

In the meantime, to get the window back on the screen, do the following:

1.) While holding SHIFT, right-click the button for the settings window on the taskbar and choose the "Move" option.
2.) Press an arrow key (this will lock the window to your mouse cursor)
3.) Once you see the window simply click to let go

Let me know if this works for you.

**Comment by mzomparelli** [comment]
I've published a new build that stops trying to remember window location.

**Comment by samwzlim** [comment]
> yeah, I have code in there is that is supposed to remember where you put the window. I'm going to remove that code.
> 
> In the meantime, to get the window back on the screen, do the following:
> 
> 1.) While holding SHIFT, right-click the button for the settings window on the taskbar and choose the "Move" option.
> 2.) Press an arrow key (this will lock the window to your mouse cursor)
> 3.) Once you see the window simply click to let go
> 
> Let me know if this works for you.

yup it works and i can move the window freely now, thanks!
