### ISSUE TITLE
Can't find round robin feature for ctrl+win+left/right

### ISSUE THREAD

**Issue by ronakmsoni** [mzomparelli/zVirtualDesktop#284]
This is not quite an issue, but I can't find any other place to ask this.

I'm having trouble finding out how to turn on the round robin feature for ctrl+win+left/right. I can't find it in the settings. Can anyone help?

**Comment by mzomparelli** [comment]
Round robin is automatic. You just need to create hotkeys:

![image](https://user-images.githubusercontent.com/10564234/114924504-b1c4a380-9df3-11eb-9829-e8d9772498b1.png)

![image](https://user-images.githubusercontent.com/10564234/114924545-b8ebb180-9df3-11eb-9ee7-e0b5b3f37e84.png)

**Comment by ronakmsoni** [comment]
Thanks!
