### ISSUE TITLE
zomp.co is marked by BitDefender as a dangerous page

### ISSUE THREAD

**Issue by birnam** [mzomparelli/zVirtualDesktop#286]
Subsequently, BitDefender is blocking what I assume are login and/or license verification attempts roughly every 30 seconds.

![image](https://user-images.githubusercontent.com/430066/118865404-e3c39c80-b8ae-11eb-9d5e-203a392f9d15.png)

**Comment by mzomparelli** [comment]
Yeah, I don't know about the 30 seconds unless I have it keep retrying. It should not be any more than 1 hour. I'll look into this. 

That is the url I use for updates and I suspect it sees that and that the exe is unsigned. You just have to trust me here until I decide to start signing my exe and build reputation. I assure you that nothing malicious is occurring. Just trying to offer people a useful tool that I use everyday. Maybe add an exception to Bitdefender. Sorry for the inconvenience.

**Comment by mzomparelli** [comment]
I am a little concerned that bitdefender is reporting http rather than https. There should not be any http requests coming from zVD.

**Comment by mzomparelli** [comment]
Also, I can't stop pinging this server because it's also the activation server. If you buy zVD then you can register offline and then block the activation server. However, this would prevent automatic updates as well.

**Comment by mzomparelli** [comment]
My homepage on that url is probably not helping either. I need to update that with more content s it doesn't seem suspicious. Ultimately I'm going to move the activation server to https://zvirtualdesktop.com

They are on the same server. I just need to change some mapping and update some code. Easier said than done really.

**Comment by birnam** [comment]
BitDefender also gives me the error/warning when I try to visit zomp.co directly. I have purchased zVD so I'll try the offline registration to see if it will quiet the warnings, although obviously that's treating the symptom and not the disease.

After leaving this going longer, I think the gaps are mostly an hour between tries, however there was a big chunk about the time I wrote the issue report where they were coming every 30 seconds.

I can confirm, it's reaching out to https. The screenshot above was me trying to reach the site directly and I just typed in the bare domain, sorry if that was confusing. https in a browser also causes the warning.

**Comment by birnam** [comment]
This is the warning created from zVD as recorded by BitDefender. I tried looking for any helpful reasons but I haven't found anything.
![image](https://user-images.githubusercontent.com/430066/118890295-6eff5b00-b8cc-11eb-8117-5892fbe396b1.png)

**Comment by birnam** [comment]
Here is the BitDefender page on reporting false positives though -- this might be helpful
https://www.bitdefender.com/consumer/support/answer/29358/

**Comment by mzomparelli** [comment]
thanks, I have submitted the url as a false positive. Not sure what they'll think when they see the home page. There was no place for me to enter more info so I hope that they contact me via the email they also asked for.

**Comment by mzomparelli** [comment]
the disease is the people that create malicious code not that zVD is flagged as a false positive. Even if I sign my code it's still possible to be flagged due to not having enough reputation on the certificate to satisfy the anti-virus. This can be a costly battle for me. Code-signing certs are not cheap and you have to keep them up to date or else lose all the reputation it has gained.

**Comment by mzomparelli** [comment]
Bitdefender has unblocked my url.

![image](https://user-images.githubusercontent.com/10564234/119213057-212c5380-ba82-11eb-87b3-2da01b3a50ae.png)
