### ISSUE TITLE
Not working on windows 10 anymore

### ISSUE THREAD

**Issue by dominikbullo** [mzomparelli/zVirtualDesktop#292]
The shortcuts not working anymore. Also when I press win + tab, it didnt show zvirtual desktop, but only classic windows desktops manager.

Windows 10 Edu 21H1 19043.1288

**Comment by mzomparelli** [comment]
Makes sure the keyboard hook is enabled in zVD->Settings->More Settings.

**Comment by dominikbullo** [comment]
Thank you!!! I dont understand how it turn off....Thank you, closing this 👍
