### ISSUE TITLE
Plase add the Fill option for the desktop images

### ISSUE THREAD

**Issue by tester0077** [mzomparelli/zVirtualDesktop#298]
Just found this app; like it and have got myself a license for one PC need it for at least one or two more.
Would like it even more if there was as option to use the 'Fill' option for my favorite desktop wall paper.
I was using that option up to now and, without it, the wallpaper does not fill the screen for all of my 3 monitors and, instead leaves a black strip on both left and right.

**Comment by mzomparelli** [comment]
Thanks for the feedback and thank you for purchasing a license. I am aware that some work needs to be done in the wallpaper area and I will keep this issue in mind when I get time to dig into all of that.

**Comment by tester0077** [comment]
In some of your old code one can achieve this with

if (style == Style.Fill)
    {
      key.SetValue(@"WallpaperStyle", 10.ToString());
      key.SetValue(@"TileWallpaper", 0.ToString());
    }

**Comment by mzomparelli** [comment]
Thank you for that. I will work this in.

**Comment by mzomparelli** [comment]
I have worked this into 1.0.98.10. let me know if you have any issues.

**Comment by mzomparelli** [comment]
The force update button on the settings form will force a download from the server. Users are only notified upon major updates which I will be releasing soon.

**Comment by tester0077** [comment]
Looks like it works as expected.
Thank you.
