### ISSUE TITLE
Create a new desktop when trying to move windows to non-existence desktop

### ISSUE THREAD

**Issue by arieljannai** [mzomparelli/zVirtualDesktop#30]
If I have only one desktop open, and I'm trying to move a windows to the right (with alt+win+right) it does nothing, since there's no desktop on the right. I think it should create one automatically.

And also - maybe add an option to automatically close empty desktops

thanks!

**Comment by mzomparelli** [comment]
It should already create desktops as needed. Are you using version 1.0.21. Download that version and see if this issue still occurs and report back please.

I will look into removing unused desktops.

**Comment by arieljannai** [comment]
Yep, I'm using 1.0.21 - just started using it today.
Any idea? Are there any logs I can look at?

Winver: 1607 (build 14393.969)

**Comment by mzomparelli** [comment]
I'm testing this now and it is working fine in version 1.0.21. I deleted all my desktops and tried moving and navigating to a non-existent desktop and it created it for me and all of the necessary ones in between.

I will implement logs in the next version so we can get tot he bottom of this. In the meantime, just create your desktops ahead of time.

I am running 1607 14393.953 at work and a different version at home and they both work fine.

**Comment by mzomparelli** [comment]
For my own curiosity, would you be willing to tell me where you heard about this app?

**Comment by arieljannai** [comment]
Saw it in a comment in another gh project, which to it I arrived from a SO question

**Comment by mzomparelli** [comment]
@arieljannai I just realized why you have this issue. WIN+ALT+Arrow keys are the default Windows hotkeys for this. I don't control those. Do you think I should override them so I can handle this appropriately? You won't see this issue if you use any other hotkeys to move or navigate.

**Comment by mzomparelli** [comment]
@arieljannai Ok, so what I did here was implemented Round Robin. This means that if you have 2 Desktops and are on Desktop 2 and move a window to the right it will actually go to Desktop 1. When it reaches your last desktop it starts over. One of my users requested this. Please let me know if you are seeing it work the way I have described and I would love your feedback on that feature.

**Comment by mzomparelli** [comment]
@arieljannai Having 9 desktops isn't too much impact on the system so I'm not sure I will implement a feature to remove unused desktops. I'll create a issue for it asking for feedback.

**Comment by arieljannai** [comment]
The Round Robin works great 💪 
Thanks! I'll just keep another one always opened
