### ISSUE TITLE
zvirualdesktop wont install to my 22h2 w11 pc

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#301]
I receive this error when opening .exe: 
![Clip_20221019_031034](https://user-images.githubusercontent.com/110556802/196567879-a232f4c3-0708-47f5-a8f1-99942df1c823.png)

**Comment by mzomparelli** [comment]
can you run Winver and tell me what is your build number?

Win+R -> winver -> Enter

**Comment by ghost** [comment]
downloading insider build version via website fixed my problem haha. 
22h2 build 22621.674

**Comment by ghost** [comment]
There is a huge dealbreaker for this virtual desktop. There is no support for multi monitor setup? zvirtualdesktop should have an option to show every open application on each monitor. I will open a request for that. So others can see it.
