### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by hisbvdis** [mzomparelli/zVirtualDesktop#316]
Hello. Could your please tell should your app work on Windows 11?
I tried to run it, but I receive weird message (attached screenshot)
Thanks in advance
![2023-09-13 19 10 36](https://github.com/mzomparelli/zVirtualDesktop/assets/5147554/3c2ab93b-80bd-49c3-a0ab-58495de0849c)

**Comment by mzomparelli** [comment]
run winver and tell me your build:

win+R then type winver

**Comment by mzomparelli** [comment]
I suspect you just need to update windows like others users have done

**Comment by hisbvdis** [comment]
> run winver and tell me your build:
> 
> win+R then type winver

![2023-09-14 10 05 04](https://github.com/mzomparelli/zVirtualDesktop/assets/5147554/ed8d604d-ca73-4607-a53d-4fd8dcf61bbc)

**Comment by hisbvdis** [comment]
> I suspect you just need to update windows like others users have done

I'm going to try updating right now.

**Comment by mzomparelli** [comment]
yep you need to get to 22621.2215

**Comment by mzomparelli** [comment]
you should remove that winver image as you left you email visible.
