### ISSUE TITLE
Overlay with a desktop number when switching

### ISSUE THREAD

**Issue by enumag** [mzomparelli/zVirtualDesktop#45]
When moving a fullscreen app I found it difficult to determine which desktop I'm on at the moment and whether I should stop or move more. Currently the only things I can use for orientation is on the taskbar which I'm not looking at when switching desktops.

A better thing would be to briefly show an overlay upon switching with some information:
- mainly the desktop number
  - later the desktop name if you add support for named desktops
- icons of the applications running on that desktop
  - or possibly previews/titles instead? icons are probably the best option though

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Desktop Switch Overlay](https://trello.com/c/VH9EAAFZ/5-desktop-switch-overlay)

**Comment by mzomparelli** [comment]
This is coming in version 1.0.68. Currently not configurable, but will change that as soon as I handle the losing of settings when I alter the settings structure.
