### ISSUE TITLE
Option for alt+tab menu to only show current desktop's windows

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#47]
This would help each desktop feel much more like its own environment/workspace.

Thanks!

EDIT: Apparently there is a setting for this in windows settings, but it doesn't seem to work for me. I'll see if I can figure out what's happening.
EDIT: Looks like display fusion is causing the issue, not this.

**Comment by mzomparelli** [comment]
Can you tell me what that Windows setting is so I can try it?

As far as this issue...it appears to be working for me (only showing the windows for the active desktop in ALT+TAB) so it must be Fusion as you say. Still, I'd like to know where this setting is that you mention.

**Comment by ghost** [comment]
Settings > System > Multitasking > Virtual Desktops
![image](http://i.imgur.com/otQDV5a.png)
