### ISSUE TITLE
Crash, might be related to using task view but I can't reliably reproduce it.

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#48]
Here is the error message. I'll see if I can get more info the next time it happens.

An error occured navigating to the specified desktop. See additional details below.

The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)

zVirtualDesktop::GetCurrentDesktop

**Comment by mzomparelli** [comment]
Thanks for the info. I will investigate this issue. If you get more info then please post here.

**Comment by mzomparelli** [comment]
Apparently the call to the underlying IVirtualDesktop interface failed which caused this error. Unfortunately, that's the extent of info I have right now.

**Comment by mzomparelli** [comment]
How long was the app running before the crash? Did you move any windows or navigate since running the app and before crashing?

I ask because I might have identified an issue and I will be trying to test if it causes any issues. Basically, I store a variable that hold the number of desktops. This gets changed when desktops are removed or added, but I was not setting it at program start. I've added code that sets it at program start, but it won't be available until I publish 1.0.41. If you continue to see a crash like this then let me know and I'll push out the update sooner so you can test.

**Comment by ghost** [comment]
I was able to get it to crash a few times in a row by opening up task view and dragging a window to a new desktop, and then switching, but after those few times everything has been working perfectly. Here is the extended crash info:

<details> 
  <summary>Spoiler </summary>
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at WindowsDesktop.Interop.IVirtualDesktopManagerInternal14328.GetCurrentDesktop()
   at WindowsDesktop.Interop.VirtualDesktopManagerInternal.GetCurrentDesktop()
   at WindowsDesktop.VirtualDesktop.get_Current()
   at zVirtualDesktop.frmMain.CreateDesktopMenu()
   at zVirtualDesktop.frmMain.SystemTrayMenu_Opening(Object sender, CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnOpening(CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ContextMenuStrip.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Int32 x, Int32 y)
   at System.Windows.Forms.ContextMenuStrip.ShowInTaskbar(Int32 x, Int32 y)
   at System.Windows.Forms.NotifyIcon.ShowContextMenu()
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
zVirtualDesktop
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Utilities/zVirtualDesktop/zVirtualDesktop.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
Microsoft.VisualStudio.Diagnostics.ServiceModelSink
    Assembly Version: 4.0.0.0
    Win32 Version: 14.0.23107.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Diagnostics.ServiceModelSink/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Diagnostics.ServiceModelSink.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.
</details>

**Comment by mzomparelli** [comment]
Thanks for providing the stack trace. It's very helpful. I see that SystemTrayMenu_Opening was called. Did you right-click on the icon right before it crashed? I'm wondering if this was called via a left-click to open task view. It shouldn't be called on a left click.

**Comment by ghost** [comment]
The sequence of events every time is that the system tray icon stops updating to show the current desktop, and if I try and switch desktops via hotkey, it doesn't switch and the error dialog from the first post comes up. Then, when I right click on the system tray icon, the error message with the stack trace comes up.
The error is happening pretty frequently, and it just happened without me ever opening up task view or moving any windows. I opened the program, stayed on a single desktop, and then tried switching, and it crashed. I'm going to keep display fusion closed for a while and see if the crash still happens, since that was causing other issues.

**Comment by mzomparelli** [comment]
I'm new to Display Fusion so I'm headed over to their site to check it out.

So far, you are the only one reporting a crash or unresponsive state so I suspect it could have to do with something running on your machine. Nonetheless, I still would like to get to the bottom of it and maybe I can do something with my app to help. The info you continue to provide is useful and greatly appreciated.

**Comment by ghost** [comment]
I'm still not sure if displayfusion was responsible since I was able to run it for a full day without crashes with displayfusion closed, but it turns out I had some weird issues with windows, and now that I've fixed those, this seems to be running fine even with displayfusion. I'll update if anything changes, but I think for now this is resolved.
