### ISSUE TITLE
Switch desktops independently on each screen

### ISSUE THREAD

**Issue by pitxels** [mzomparelli/zVirtualDesktop#53]
This is a future request to have multiple desktops and switching between them per every screen.

Just see how OSX works is awesome.

**Comment by mzomparelli** [comment]
Could you elaborate please? I don't use OSX. I can't stand it. I am interested in hearing more about how this feature works though.

**Comment by pitxels** [comment]
Just check this video on minute 2:45 http://youtu.be/Mi6AhogZCeg he is changing the desktop on only one monitor (where the mouse pointer is currently). This is something Windows doesn't have. That's why I am suggesting it as feature.

**Comment by mzomparelli** [comment]
I'm not sure I like this idea. I use both monitors at all times so switching just a single monitor to a different desktop would actually be a bad thing. I will check out the video and let you know what i think after watching. Based on your description, I probably won''t implement this feature.

**Comment by mzomparelli** [comment]
I watched the video and while that is an interesting idea I think it defeats the purpose of multiple desktops. I don't even think I could accomplish something like this with Windows 10 VD. It have to be completely custom.
