### ISSUE TITLE
Ability to assign non-standard keys

### ISSUE THREAD

**Issue by enumag** [mzomparelli/zVirtualDesktop#56]
I'm using Microsoft SideWinder X4 keyboard which has some additional keys S1 to S6 on its left side. I'd like to assign some of these to zVirtualDesktop. So far I could not find any way to achieve that. Any ideas?

**Comment by mzomparelli** [comment]
I don't think I can handle these keys because they are driver specific. I will look into though.

Since this is driver specific you should have software that allows you to program these keys.

**Comment by mzomparelli** [comment]
One thing you might be able to do is assign a hotkey to one of those buttons. Basically, you should be able to program it to send keys, then you could have zVD listen for that hotkey and perform an action. That's the best I have at the moment, but I am still looking into it. 

I'm a supply chain engineer by day and zVD is just a hobby for me. This means that I can only work on it on my own time. Sometimes I'll fix a bug while at work so I can use it myself while working.
