### ISSUE TITLE
error when trying to navigate to previous/next desktop

### ISSUE THREAD

**Issue by Aran-Fey** [mzomparelli/zVirtualDesktop#61]
Whenever I try to navigate to the previous or next desktop, this error dialog appears:

![untitled](https://cloud.githubusercontent.com/assets/22036272/25840972/65995a04-349e-11e7-8ffc-a59e0e4c75bd.png)

Note that I'm not using the default (Windows) keyboard shortcuts, but have created my own hotkeys for "Navigate to Desktop #Previous" and "Navigate to Desktop #Next".

**Comment by mzomparelli** [comment]
@Rawing thanks for the feedback.

Does this error message occur when you navigate to a desktop directly using a hotkey that takes you to a specific desktop?

What hotkeys did you choose for the next and previous actions?

What is your Windows 10 version? You can get it by opening the run dialog (WIN+R) and typing WinVer.

**Comment by Aran-Fey** [comment]
This error only occurs when I use "navigate to next desktop" or "navigate to previous desktop"; moving directly to a specific desktop works fine.

I'm using Ctrl+Alt+UpArrow/DownArrow, but I've confirmed the bug also occurs when I try other key combinations.

My OS is Windows 10 Pro version 1703 (build 15063.138).

**Comment by mzomparelli** [comment]
Thanks, I'll investigate this evening.

**Comment by mzomparelli** [comment]
I have identified the cause for this issue and it will be corrected in an update I publish tonight.

You will have to delete the bad hotkeys and recreate them. They were created incorrectly via my code.

Version 1.0.49
