### ISSUE TITLE
How does this pin a window or app to all desktops?

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#62]
For my own virtual desktop management app I would like to know how to programmatically pin a window or app to all virtual desktops. Can you share how you did this? Or where is some other documentation that shows how to do this?

... actually (I just searched some more), I think maybe I can find a way here in this repository for [win-10-virtual-desktop-enhancer](https://github.com/sdias/win-10-virtual-desktop-enhancer).
(I don't know how anyone figures any of this out. It is like magic to me.)

(And really, I would also appreciate if this project was open source and I'm sure I'm not the only one.)

**Comment by mzomparelli** [comment]
Grabacr07 created a library that uses the IVirtualDesktop interface. I forked his code and I'm using it and maintaining it in zVirtualDesktop.

https://github.com/Grabacr07/VirtualDesktop

This project was open source at one point, but I wanted to be the only one maintaining it. Once I get bored I will put it back out here on GitHub.

**Comment by mzomparelli** [comment]
@noido FYI, Don't use win-10-virtual-desktop-enhancer. Go straight to Grabacr07's project. Skip all the middle man projects.

**Comment by mzomparelli** [comment]
@noido you can come to me if you need any help. I'll show you portions of my code to help you with your project. Try handling the pinning on your own and if you continue to have trouble I'll walk you through how to add this feature to your project using Grabacr07's project. If you use his project you should use the code instead of a compiled library. I did this to make sure all I had to publish was an EXE.

**Comment by ghost** [comment]
Too late! Haha. I already figured out how to port all two of my features (per-desktop random wallpaper folder, and per-desktop icons) to win-10-virtual-desktop-enhancer (AutoHotKey).

I'm not familiar with making DLLs and using them in other code, but it looks like that's what I would have had to do if I used the .cs project.

I'm also not used to seeing that reason for closed source, that is interesting and thank you for sharing (probably if I did the same thing, I would hide everything in the repository except the .exe, and leave a note about why it is closed.). I just get concerned when I think someone might be working for a quick buck—I tried that once and would gladly trade the buck for my time back. XD

Also, whenever I see code that adds useful Windows feature like with these virtual desktops, I think it may be useful to share with Microsoft. What's the most relevant way to contact them about these? I would think to email their Windows Insider Program. (And I hope they know about AHK; it seems crazy fast for prototyping UI designs.)

**Comment by mzomparelli** [comment]
Sure I would love a quick buck and why shouldn't be able to profit from this. I made this app because I needed it. Originally, I didn't intend on anyone else using it. If you like a program then you should help out the developer for the time they put in. I do this when I see donate links for things I find very useful.

If you think AHK is nice for prototyping UI then you should get involved in .net C# and VB. I would never create a program with AHK, only simple stuff. Sure it's powerful, but that doesn't make it the best choice.

The best way to contact Microsoft with feedback is through the Feedback Hub. You can find it in the Windows Store.

I do plan on opening it back up, but I enjoy maintaining on my own. Until I get sick of it I don't want anyone's code, only their feedback.

**Comment by ghost** [comment]
I liked the option to tip a Lamborghini.

**Comment by mzomparelli** [comment]
haha thanks. I thought i would try and lighten it a bit with some humor. Make them smile and maybe they're more likely to donate a few bucks. Feel free to send me $200k :) That would make me happy.

**Comment by ghost** [comment]
I think there is at least one feature set for virtual desktops that can be useful enough for people to want to pay for. (I haven't thought of more yet. Too lazy.)

I was considering the possibility of running a scheduling program for separating timed tasks—kind of like "Quiet Hours" or "do not disturb" or even a school schedule. There is one set of features where the user (or their supervisor!) can set a list of whitelisted and blocked programs for a time block. This is possible without multiple desktops. However, I was also thinking of the possibility of separating the programs to other desktops, or maybe even locking the user to a specific desktop during time blocks (like a classroom!). (That's kind of like an abstract version of an actual 3D school day—why not just make an actual 3D workspace? haha)

That one for me is just an interesting play on the idea (I almost want to do it, but not quite. Maybe someone else does!). Though I see things like https://getcoldturkey.com/writer/ and think "Maybe if someone really wants this then I'll be more willing to work on it."

It's kind of interesting seeing what value propositions people are looking for and willing to pay for. That lamborghini? Maybe it's for a race—for collecting self-driving car data for everyone—for driving around the pope and the president's wife. (Or maybe some nice old man just has too much money and wants someone to enjoy the pleasure of a fresh new lamborghini ("How kind!") ... because he wants to sell more lamborghinis to more rich programmers.)

So I like to think about how these things can be useful. (And who's going to want what the most, too? Helps to pitch the right idea to the right party.)

**Comment by mzomparelli** [comment]
I like you! You seem like a creative person with cool ideas. I like the idea of limiting or blocking certain app or blocking to a specific desktop. I'm not sure I would ever use it, but I can think of a few people that would find it useful. I'm not sure.

Someone else suggested an idea for this app. This person says that Apple Mac virtual desktops allow you to switch a single monitor to a different desktop. I'm not sure how I feel about it. I always use all my monitors for each desktop and I feel like this would actually make it worse. I can see times where it would be cool though. What do you think about that idea?

**Comment by ghost** [comment]
I thought about per-monitor desktops. I imagine dragging tabs around in a browser, and think it could be implemented well like that. For example, if you have several different activity sets on monitors, you can drag and drop the desktops on those monitors to swap them. This is intuitive and would let you rearrange the monitors so your main monitor matches your new main task.

I saw one possible implementation of this idea (haven't tested) in this link https://www.actualtools.com/virtualdesktops/independent_virtual_desktops_on_multiple_monitors.shtml

Also, I think the idea I am thinking of may be expressed better as "A UI to switch desktop or monitor positions", and may be done without using virtual desktops at all. Basically, you would see images of the monitors, drag and drop them on the UI, then hit Switch, and it switches the monitors. Maybe there is also a way to drag the monitors on the UI so they look like the way you have them set up on your computer (I think maybe it can take that from one of the Windows settings?).
