### ISSUE TITLE
DesktopView - White thumbnails for UWP apps

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#70]
Hi, why is it that so many window (app) thumbs just shows up white all the time?
This is not persistant og just one nd the same App, but random and can happen to any, many,a few or none. I have not been able to see a pattern, so I'm not able to help ....
![zvd-capture](https://cloud.githubusercontent.com/assets/18447119/26144269/6c5f0730-3ae8-11e7-9ca1-82d23b3eb1ee.jpg)

**Comment by mzomparelli** [comment]
It means that the live thumbnail is white, but more likely it is that the live thumbnail couldn't be created or for some reason was not. I have see this only with Universal Windows apps. 

Have you tried restarting your PC? At the very least, try restarting zVD.

Please continue to provide any additional details on this. I will continue to investigate myself.

**Comment by oywino** [comment]
Restarting the PC makes no difference. The strange thing is that this is intermittent by nature. I will try to restart zVD next time it happens.
On the side, I also notice that whenever Mail for Windows is running, it often produce two thumbs in zVD Desktop View; One main app thumb which for the most part looks correct, and an additional all white thumb named Inbox. 
Although I never see more than a single window when using Mail for Windows.... zVD typically produces two...

**Comment by mzomparelli** [comment]
The multiple thumbnails occurs with the Universal apps and I'm looking for a solution. It happens because of the way Microsoft implemented this. There truly are multiple window handles. I just need to figure out how to get the main one.

**Comment by oywino** [comment]
Excellent - that sounds encouraging (although I don't know what you mean by an app being "universal" ?)

**Comment by mzomparelli** [comment]
Universal is Microsoft new type of apps. Some are pre-installed, but all others would come from the Windows Store. Microsoft Edge, Windows Mail, Xbox, etc. are universal apps. I've been away from enhancing zVD for a little while, but as soon as I get back to it I will deal with this. 

I'm coaching my son's baseball team and that's been taking a lot of my time lately.

**Comment by oywino** [comment]
Coaching your son sounds like quality time :-)

**Comment by mzomparelli** [comment]
Yep! I enjoy it. He's getting older (14 in June) so I have to get all this in while he still wants anything to do with me. They grow up so fast.

**Comment by oywino** [comment]
I know. Mine are 36 and 40, but I have 4 grandchildren...  :-)

**Comment by mzomparelli** [comment]
I'm 36 in September, but I still feel like I'm 21. I hear from older people all the time that say your mind doesn't really change, only your body does. They also say the time goes faster and faster. Probably because adult responsibilities keep us busy. Time went slow in the younger years because we always had something to look forward to. Driver's license, alcohol, etc.

**Comment by mzomparelli** [comment]
In messing with Universal apps, Windows Mail and Edge, I noticed that it only displays two thumbnails (one being an actual thumbnail and the other being a white window) when you are not on the desktop where the window is located. Can you confirm this on your end?

Next step is to compare the two windows and determine which one is always visible and test if that is the one that gets the actual thumbnail.

As far as white windows for you, I'm not sure about that. What are your computer specs?

**Comment by oywino** [comment]
Yes, that is correct - at least for Windows Mail. It only occurs when I am on another desktop.
The one which is always visible - is the one named "Inbox" - and it is always just white. Also this is the one that does not "exist" on the Desktop.
My Computer Spec is: Dell Latitude with an Intel i7 with 8-cores and 8Gig memory and 2x256Gig SSD.
I use an external 2560x1440 Dell monitor with it all the time.

**Comment by mzomparelli** [comment]
That's a pretty nice PC you have there. It eliminates performance issues as a culprit to this issue.

For work I use a crappy i5 with 8 GB RAM. zVD works great.

At home, my best PC is a laptop running i7-6820HK, 64 GB RAM, 1070 Nvidia Graphics Card. I don't see much difference with this machine and the work laptop as far zVD goes.

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DesktopView - White thumbnails for Store apps](https://trello.com/c/xOMMGgwK/13-desktopview-white-thumbnails-for-store-apps)

**Comment by oywino** [comment]
I don't understand your link. What is DesktopView?

**Comment by mzomparelli** [comment]
Don't worry about my link. I just referenced this issue from my Trello board and it added a link here. DesktopView is the window with all the thumbnails that you can drag n drop to other desktops.

**Comment by mzomparelli** [comment]
This is a copy of issue #118 

I changed the color so it's not white and also other bug fixes. Let's continue in the newer issue.
