### ISSUE TITLE
Start menu opens on previous desktop

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#72]
If I switch desktops and press the windows key, I have to press it twice for the start menu to open, and sometimes it jumps me back to the previous desktop. This only happens when pressing the windows key, not when actually clicking the start button. This didn't use to happen, even in v 1.0.50, so I'm not sure what changed, but this is happening on two different computers.

**Comment by mzomparelli** [comment]
I can confirm this is happening, but I can't confirm it used to work because I never noticed this. I'll look into it. I'm also investigating Desktop View causing the app to crash. I think I might have a memory leak I need to deal with. I noticed it only crashes when there are many windows open.

**Comment by mzomparelli** [comment]
How were you able to see the start menu open on another desktop? I can reproduce the start menu not popping up, but I can't move to another desktop where it's open.

**Comment by ghost** [comment]
I can't actually see it on the other desktop (the start menu always stays open when switching desktops for me), but sometimes when I press the key the second time, it jumps me back to the other desktop, so I assume it's opening there.

**Comment by mzomparelli** [comment]
ok, thanks for the info.

**Comment by mzomparelli** [comment]
I don't know what to do about this. A small annoyance yes. If more people complain I'll reopen the issue.
