### ISSUE TITLE
Keep getting prompted to update the app. 

### ISSUE THREAD

**Issue by grant-gregory** [mzomparelli/zVirtualDesktop#73]
Keep being told to update to Version 1.5.1 since I have version 1.5.0. I click yes and then it downloads and subsequently tells me I have an update available for version 1.5.1 (and that I still have version 1.5.0). Is there a way I can either 1 install properly, or 2 stop having these popups?

Thanks.

**Comment by mzomparelli** [comment]
Sorry, this is happening on some machines. I will get around to fixing the updater soon. In the meantime, just grab the current build manually using this link and replace where you have the old version unzipped. I know this bug sucks and I'm sorry. I will fix it.

http://zomp.co/Files.aspx?id=zVD

I hope everything else is working ok. Keep the feedback coming. I really appreciate it.

**Comment by mzomparelli** [comment]
I am going to close this issue soon though because I already have an issue open to fix the updater. Again, I'm sorry for the inconvenience.

https://github.com/mzomparelli/zVirtualDesktop/issues/57

**Comment by mzomparelli** [comment]
Out of curiosity, what kind of machine are you running that is giving you issues? I run zVD on several PCs and this updating issue only happens on my Surface Pro 4.

**Comment by grant-gregory** [comment]
Thanks for your help! I have a Surface Pro 4 as well. It may have to do with how Surface devices utilize a very stringent Secure Boot - although I'm not sure.

**Comment by grant-gregory** [comment]
@mzomparelli
When I try to download the newer version from the link above, or from GitHub Windows Defender tells me that a virus is detected... I am stuck on this version and can't get to .60

**Comment by mzomparelli** [comment]
It might just be smartscreen blocking it because it came from the internet. Try this link to download the current version manually. FYI, this link will always get you the current version.

https://zomp.co/files.aspx?id=zvd

**Comment by mzomparelli** [comment]
Sorry, I see I already provided the link. I have Windows Defender and it doesn't say anything to me. I just sent it to VirusTotal. Sometimes it gets flagged and a rebuild can fix it.  I'll see what I can do.

**Comment by mzomparelli** [comment]
Windows defender isn't picking it up. This has to be Smartscreen. You should see a link in the lower left hand window of the warning. Click that and you will get an option to execute. I don't use Smartscreen. I am my own Smartscreen ;)

https://www.virustotal.com/en/file/9137c983a13f8d8cc82ece15e91131da4b2addcf2317e25f9e124b4b87f737b5/analysis/1499813545/

**Comment by grant-gregory** [comment]
Thanks, I was able to install it.
