### ISSUE TITLE
1.0.52 and 1.0.53 update notifications

### ISSUE THREAD

**Issue by mwalker212** [mzomparelli/zVirtualDesktop#74]
I'm running 1.0.51 and this morning I had a notification for 1.0.52 but when I accepted the update it simply closed the current version and nothing happened, the executable was not updated. I then received another notification this afternoon after a restart for version 1.0.53 but that, too, did the same thing and, so, I still have 1.0.51 installed.
I note that these new versions don't appear on here so are they even legit? Are you having issues or has someone hacked the update process?...

**Comment by mzomparelli** [comment]
Yes, all updates are legit. I'm the only one with the current source code.

When this happens simply download the new EXE manually. Some PCs are having this update issue and I'm looking into it. Sorry for the inconvenience.

http://zomp.co/Files.aspx?id=zvdexe

**Comment by mwalker212** [comment]
Hmm, just to follow on from that, I downloaded the update and when I tried to run it Windows chimed in with the following message:

Windows protected your PC
Windows Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk.

Application: 
zVirtualDesktop.exe 
Publisher:  
Unknown publisher

**Comment by mzomparelli** [comment]
This is because I did t sent a link to the zipped file. You can get past smart screen. There should be a link that says run anyway. The file is safe, but if you're uncomfortable then no one is making you use it.

You can try this link to the zip file or just use the green download button on GitHub next to the donate button. That link always get the most recent zip file.

HTTPS://zomp.co/files.aspx?id=zvd


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mzomparelli** [comment]
Actually, don't use the github link yet. It still points to Dropbox. I'll update that in about 30 min.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mwalker212** [comment]
No problem, I allowed the other download to run. All good :)

**Comment by mzomparelli** [comment]
Awesome!

I just updated the link on the main github page. When this happens again you can simply use the github download link

https://zomp.co/files.aspx?id=zvd

How do you like zVD? I made it for myself and realized others would like it too.

**Comment by mwalker212** [comment]
I tried using Linux (Ubuntu) as my main desktop for about a year or so but little things here and there eventually brought me back to Windows. One of the main things I missed from Linux, though, was the easy virtual desktop switching, and your app is the perfect option I've found for Windows, and then some. So a job well done. I'll sort out a donation in the near future :)

**Comment by mzomparelli** [comment]
Thanks for the great feedback. Hearing it never gets old.
