### ISSUE TITLE
WMI Provider Host, high CPU-usage

### ISSUE THREAD

**Issue by robinrosenstock** [mzomparelli/zVirtualDesktop#75]
If zVirtualDesktop is active, then on my Computer the WMI Provider Host is around 7-8% CPU Usage

**Comment by mzomparelli** [comment]
I haven't noticed this. I just checked and the WMI process is fine on my PC with zVD running. Could you provide some additional info, like what you were doing with zVD at the time. Also, by chance, is your Windows 10 an upgrade from a previous version of Windows? After reading some articles it appears many users see this after an upgrade. I don't recommend upgrading. You should always format and install fresh.

**Comment by robinrosenstock** [comment]
My System was a fresh Windows 10 install. Is it because of the „Creators Update“? Unfortunately, I have no idea, which other application is interfering with zVD on my machine...

**Comment by mzomparelli** [comment]
The creators update should be fine. I have the latest Window 10 updates on all my machines and none of them have this issue. Does zVD function normally for you or are you having issues? Is there specific area in zVD you can point to that might be the culprit? I'm basically asking if you can pin point it to something you were doing in zVD. I don't know of any programs that don't play nicely with zVD besides the displaying of thumbnails for Windows 10 store apps, but that issue isn't causing any major issues that I know of.

**Comment by robinrosenstock** [comment]
zVD is functioning normal, but only the WMI Provider Host process drains CPU. I had thought, that maybe this is a known problem... and because I don't know, what can be done to solve my problem, maybe you should close this issue. Maybe keep in mind this Problem, if it pops up someday again. Thanks

**Comment by mzomparelli** [comment]
There is something that I want to try for the next update that might help. I'm going to leave this open so that I can come back and ask you if the update helped. I should get this update in within the next few days.

**Comment by robinrosenstock** [comment]
Ok, Thanks again

**Comment by mzomparelli** [comment]
I got to this sooner than I thought I would. Version 1.0.55 addresses some exception handling that I feel might be causing your issue.

**Comment by mzomparelli** [comment]
I don't think that version will fix it. After more investigation I think I might have found the true issue. Should have another update soon.

**Comment by mzomparelli** [comment]
ok, I've identified it and removed what was causing this. It opens up a bug again that I have to figure out another way to solve. I was running a WMI query to check if the login screen is visible because once it's not visible I have to clear the modifiers keys that have been pressed. The problem is, when using CTRL+ALT+DELETE to access this screen it prevents zVD from seeing that the keys have been depressed. Once the login screen is brought up, zVD is no longer notified until the screen is closed.

**Comment by mzomparelli** [comment]
I can't have that bug  so until I find a better solution I need to use WMI to test if the CTRL+ALT+DELETE screen is open and closed. The best I can do right now is increase the interval in which I make that test.

**Comment by mzomparelli** [comment]
This is fixed when I publish version 1.0.56

**Comment by robinrosenstock** [comment]
Yeah, it's working. I will donate for sure.

**Comment by mzomparelli** [comment]
Thanks! I appreciate every penny I get. :)
