### ISSUE TITLE
Request: +3, -3

### ISSUE THREAD

**Issue by nicolasdejong** [mzomparelli/zVirtualDesktop#77]
(sorry for a feature request without even able to use it on my W10-1511 but I'm just enthusiastic, ok? :-)

Can you add a +3 desktops mapped to DOWN and -3 desktops mapped to UP? That way I could navigate the grid using all four cursor keys.

My initial desktop then would be 5 and the first four others would be LEFT (4), RIGHT (6), UP (2) and DOWN (8).

**Comment by mzomparelli** [comment]
Can you perform the Windows update manually?

http://go.microsoft.com/fwlink/?LinkID=799445

This is an interesting request. Let me think about it and how I could implement this.

**Comment by mzomparelli** [comment]
I've been thinking about this as I do my regular work which is  not nearly as fun as working on zVD. I am wondering how you would like the numpad switcher once the hotkeys work for you. I will still consider your feature request, but in the meantime maybe give that a try. Also, have you tried DesktopView? I don't even use the hotkeys anymore since adding DesktopView. I use it in place of Alt-Tab a lot too since I have it mapped to a mouse button to open DesktopView.

**Comment by nicolasdejong** [comment]
Can't update. I don't have the user rights. Enterprise environment. That's how it goes unfortunately.

Sure, numpad-switcher would do fine as well. But I figured the UP would be like calling the LEFT three times in a row (same for DOWN == 3x RIGHT). Just without the animations (as with the 'round robin' option). But it's just a nice-to-have.

DesktopView works good too. That is a good fallback.

**Comment by mzomparelli** [comment]
Even if you had the rights, the Enterprise version can't install it manually. It has to wait for the auto-update.

It shouldn't be too difficult to implement the feature you want. The problem will be how I label this in the hotkey screen window as a task option so that users understand it. Do you have any suggestions there?

I promised another user a feature that allows you to scroll desktops when your mouse is over the taskbar so I have to work on that first.

**Comment by nicolasdejong** [comment]
No hurry. I'm glad you are so quick to reply already. And it's not like I can use it at the moment ;-)

My suggestion would be to label it like this:

Navigate to Desktop #n-1 -- ALT+WIN+LEFT
Navigate to Desktop #n+1 -- ALT+WIN+RIGHT
Navigate to Desktop #n-3 -- ALT+WIN+UP
Navigate to Desktop #n+3 -- ALT+WIN+DOWN

Thanks!

**Comment by mzomparelli** [comment]
I've been thinking about this and I'm pretty sure I have it all figured out in my head. This is actually going to be fairly easy to implement. It will be setup as a hotkey action for which you will be able to program your own key combination. You already know what you want yours to be, but I don't want to force others to have it that way. I want to keep the hotkeys completely configurable. Anyway, I have all that figured out and I just wanted to let you know that this should be in the next version which I'll probably get around to this weekend.

Too bad you still probably won't have an updated WIn10. What is stopping your employer from updating?

**Comment by mzomparelli** [comment]
Also, please share this app with anyone that you think will like it. Share on Facebook, Reddit, LinkedIn....wherever. It is my users that make this program what it is, It is the feedback and feature requests, like yours, that test my abilities to make zVD a great utility.

**Comment by mzomparelli** [comment]
@nicolasdejong 
Question:
What do I do when the user is on desktop 8 and presses down (+3)? Round-robin or wall?

**Comment by nicolasdejong** [comment]
That's great, thanks! I have no idea why my employer is waiting so long to update. All we can do is wait. Perhaps I should update my personal laptop to W10 but I hardly use it. 

Regarding the 8+3 (or 2-3), you already have a round-robin option. Perhaps use that? In round robin an (n+3)%desktops should do the trick.

**Comment by mzomparelli** [comment]
@nicolasdejong  Would you like to help me with something?

When I release this update I want the change log to display an image. This image will be an example of how this grid feature should work (using arrow keys as the example). I want users to fully understand and I think a picture will help them grasp it. Will you create that image for me? I will give you credit for it in the change log. Or maybe an image isn't the way to go and a simple summary will suffice. What do you think?

**Comment by nicolasdejong** [comment]
Sure. I think text will suffice, but I'll try it for a bit. Please allow me a few days to find the time.

**Comment by nicolasdejong** [comment]
Ok, how about this:

Navigation +3, -3

These navigation options exist as support for the 'grid' icon.
It assumes 9 desktops in a 3x3 grid as follows:

1 2 3
4 5 6
7 8 9

The +3 then acts as going one row down.
The -3 then acts as going one row up.

When the 'round robin' option is checked, doing +3 on the bottom row will navigate to the top row (e.g. 8 -> 2).
When the 'round robin' option is unchecked, doing +3 on the bottom row will have no effect.
Same for -3 on the top row (e.g. 3 -> 9).

**Comment by nicolasdejong** [comment]
It may be nice to have an option that prevents moving between rows when doing +1 & -1 which supports 'round-robin', like +1 :: 3 -> 1 otherwise +1 :: 3 -> 3. Like a '3x3 grid' mode. Just a nice to have, nothing more.

**Comment by mzomparelli** [comment]
This made it into version 1.0.63
