### ISSUE TITLE
Add Hotkeys to Move Window and Follow it to the Desktop

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#8]
I already h ave the ability to follow a Window when you move it, but I have not implemented that to the user. Would like feedback as to what the default hotkey should be for that.

**Comment by mzomparelli** [comment]
I'm going with hotkey CTRL+WIN+ALT+Numpad to move a window and follow it to the desktop.

**Comment by Kinmarui** [comment]
Sounds good,
also having CTRL+WIN+ALT+LEFT/RIGHT would be great

**Comment by mzomparelli** [comment]
I just built the CTRL+WIN+ALT+Numpad Hotkey. I will add the left and right before I create a new release.

**Comment by mzomparelli** [comment]
Is left and right very useful since we can specify exactly which desktop we want by using Numpad? I'll add just because you like it.

**Comment by Kinmarui** [comment]
It may be useful if I have only 2 v-desktops, then it feels more ergonomic than using numbers.
Btw you say numpad but it should work with numbers above qwerty also? Important for laptops without separate numpad.

**Comment by mzomparelli** [comment]
I thought about using the numbers above the letters, but I currently use those for a clipboard app I created. I need to finish the form that allows users to configure the hotkeys so they can choose those number keys if they want to.

**Comment by mzomparelli** [comment]
How do you like the app as it is now? Any issues, errors? I hope you get good use out of it and please share the GitHub link with anyone you think would like it.

**Comment by Kinmarui** [comment]
No problems,
as you know before I used 
https://github.com/Eun/MoveToDesktop (very lightwaight, but no ability to move to #number desktop)
with
https://www.facebook.com/Win10VirtualDesktopSwitcher 

but if you implement task movement between desktops then I will use your solution only :)

**Comment by mzomparelli** [comment]
What do you mean by "Task Movement"? Are you referring to moving windows with left and right arrows and following the window to the desktop?

**Comment by Kinmarui** [comment]
Yup, sorry i wasn't clear about it
