### ISSUE TITLE
MOUSE-TASKBAR-SCROLL and MOUSE-ANYWHERE-SCROLL EXPLAINED

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#80]
I read about the above in your version history, and I am a bit embarrassed to admit that I completely failed to understand what function/feature you try to implement/explain here. But I have a feeling it's something I want. Could you please elaborate a bit deeper and explain what exactly MOUSE-TASKBAR-SCROLL-UP and MOUSE-TASKBAR-SCROLL-DOWN means?  What should I do and what effect should I expect to see?

**Comment by mzomparelli** [comment]
Yes, I would be happy to. 

By creating these as "keys" you can choose from, it is not limited to just navigating to desktops. Here's what I do:

Volume Up:  +MOUSE-TASKBAR-SCROLL-UP
Volume Down: +MOUSE-TASKBAR-SCROLL-DOWN
When my mouse is over the taskbar and I scroll the volume is adjusted

Navigate to Next Desktop: CTRL+WIN+MOUSE-ANYWHERE-SCROLL-UP 
Navigate to Previous Desktop: CTRL+WIN+MOUSE-ANYWHERE-SCROLL-DOWN
When my mouse is anywhere, including the taskbar, if no same hotkey is for TASKBAR, then this action is executed. When this happens, the scroll is **not** sent through to the focused window.

Does this help you understand it?

**Comment by oywino** [comment]
No - regretfully. If I hold down CTRL+WIN and then use the scroll wheel on my mouse, I get all kinds of effects depending on where my mouse is. If Inside Mail For Windows, the font is scaled (up/down). If I'm on my desktop, all my shortcut icons scale (up/down).. etc.
I am unable to figure out what/how zVD comes in to play.... !?

**Comment by mzomparelli** [comment]
Did you setup the CTRL+WIN+SCROLL hotkey? Let me test this out with Mail. It works for all my other programs.

You have to set this up as you would any hotkey.

**Comment by mzomparelli** [comment]
I just tested the mail app and it works as expected. Can you post a screen shot of the hotkey window for this particular hotkey?

Here is what mine looks like.

This is my navigate desktop with ANYWHERE scroll
![image](https://user-images.githubusercontent.com/10564234/27997428-71839a06-64bd-11e7-87e1-1489db2af528.png)


This is my volume control with a TASKBAR scroll
![image](https://user-images.githubusercontent.com/10564234/27997476-6b0d1dfe-64be-11e7-9fc7-4237dbab3e96.png)

**Comment by oywino** [comment]
Aha, now I see. Perhaps I'm a bit slow - but I failed to understand that I first had to configure this the way you've now illustrated by these two screenshots. Thanks a lot.

**Comment by mzomparelli** [comment]
That's my fault. I never explained it very well. Would you say it makes sense this way now that you know? It allows for the best configuration this way I think. You get to choose exactly what you want to do. I'm going to leave this open so others can benefit after my failure to explain off the bat.

**Comment by oywino** [comment]
Oh absolutely.
My goal is to be able to do as much as possible without having to take my hands off the Mouse, and at the same time with as few mouse clicks/moves as possible. I've been thinking on buying one of those fancy gaming mouse with tons of buttons and flashing red lights, but so far I've resisted the temptation just because I do not want to learn to many customized tricks that cannot be utilized when I move from computer to computer (home/office/clients).
So, the objective is to be able to do it all ( or at least as much as possible) with just a regular plain old mouse.
Can you remember I suggested once that I would like to see a feature like this: Mouse-Over on the zVD taskbar icon would automatically trigger (launch) a row of icons (similar to the TaskView, but perhaps smaller), preferably animated as fly-outs from the zVD taskbar icon, and with the current desktop icon highlighted in some way, and then the scroll wheel could be used to loop though the desktops (left/right). Alternatively moving the mouse pointer and clicking on the desired desktop icon would jump you directly to that particular one. I can't remember if you rejected the idea or not.

Another thing I'd like to mention with reference to the various navigation methods as is, -  is that its very visible (and disturbing) that the programming sequence is causing the wallpaper to flash during updates. Currently is seems like; first it move to the next desktop, then it updates the wallpaper. It should have been nice to see this in the opposite order; First update the wallpaper, then move.
My wallpapers are customized to help me recognize a fixed number of predefined desktops. I always keep my Office stuff on desktop three, and my Multimedia stuff on desktop 4, and my remote control windows on desktop 5, and my Virtual machines on desktop 6 and so on, and so on. having wallpapers customized to help me navigate (without being lost) has become essential. But the current "flashing" during wallpaper update sometimes misleads me to think I'm on the wrong desktop.
Of course I can peek on the zVD icon number, but often keeping focus and eye-contact on certain spots on screen is essential during my line of work. :-)

**Comment by mzomparelli** [comment]
Thanks for the feedback. I did not forget about you request and I have not rejected it. I haven't decided if I will or not. 

As far the wallpaper goes. Let me see how that feels if I change the wallpaper before moving. If it feels good then it will be in the next update.
