### ISSUE TITLE
Is there a hotkey for Desktop View?

### ISSUE THREAD

**Issue by enumag** [mzomparelli/zVirtualDesktop#82]
The desktop view is a great feature but it seems the only way to access it is though the tray icon? I don't see any hotkey like that in the settings.

Also I'd like to have the pinned apps column in desktop view on the left instead of on the right. I usually use like first three desktops and I don't like dragging all the windows I want to pin across the whole 32'' screen. (This is not too important, I can learn using hotkeys instead.)

**Comment by enumag** [comment]
Oh and by the way the download button in readme is still broken for me in Firefox the same way as I reported some time ago.

**Comment by mzomparelli** [comment]
There is a hotkey action for it. It's called "Toggle Desktop View" and I have it set to CTRL+SHIFT+Z. I did not default a hotkey for this.

The pin column started off on the left and it confused others and myself so I switched it to the right. Maybe I'll add an option for the user to choose left or right.

**Comment by mzomparelli** [comment]
I'm going to download Firefox and test the button.

**Comment by enumag** [comment]
I don't see any such hotkey in zVirtualDesktop settings (using v1.0.61). Also CTRL+SHIFT+Z is not doing anything.

**Comment by mzomparelli** [comment]
You have to setup the hotkey:

![image](https://user-images.githubusercontent.com/10564234/28338120-87eccb52-6bcd-11e7-9da3-771010e6e229.png)

**Comment by enumag** [comment]
Yeah I found that in the meantime. But even after I add it this way it does not work.

**Comment by mzomparelli** [comment]
Read this and make sure the hooks aren't off. They default to off by accident. once you turn them on they will turn on every time you start zVD.

https://github.com/mzomparelli/zVirtualDesktop/issues/83

**Comment by enumag** [comment]
Yeah, that helped. Thanks.
