### ISSUE TITLE
Hotkeys Not Working

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#83]
Hi, After upgrading to 10.0.61 today, none of my shortcut keys work anymore. I can manually access the desktopview and change desktops vis the taskbar icon, so the program itself is running, but is doesn't respond to any of the key combinations anymore.
Please help...?

**Comment by mzomparelli** [comment]
Go into the about screen and turn on the mouse and keyboard hook

In my screenshot they say "Stop" because they are already on. Yours should say "Start".

![image](https://user-images.githubusercontent.com/10564234/28337370-0c39764c-6bcb-11e7-8340-3ab1ba625234.png)

**Comment by mzomparelli** [comment]
I accidentally have this default to off. I will fix that in the next update. Once you turn them on they will turn on automatically when you restart the app.

**Comment by oywino** [comment]
Back in business again... thank you! :)

**Comment by mzomparelli** [comment]
I added these just in case some users had issues with the mouse hook. They can turn it off.

Actually the mouse hook doesn't go off completely. If you turn it off, and the keyboard hook is on, then the mouse hook will automatically start when you  press a modifier key and turn off when you aren't pressing a modifier key.

**Comment by buchmiller** [comment]
I updated from 1.0.60 to 1.0.63, and it did not automatically restart the hooks. I read the comments in this issue to figure out how to get it working again.

**Comment by mzomparelli** [comment]
@buchmiller ok if I'm understanding correctly, you have it working again after turning the hooks on?

New users have the Keyboard hook automatically started. I can't figure out why it's not starting for existing users, but once you start it, it will start automatically every time after that.

**Comment by buchmiller** [comment]
Yes, it is working now. It just wasn't working right after the update.
