### ISSUE TITLE
Freeze when app asks for exit confirmation

### ISSUE THREAD

**Issue by jjhidalgar** [mzomparelli/zVirtualDesktop#84]
Hi, I found a little -bug- which may be a little bit annoying. When I close an app from the desktop view and this app asks for confirmation "are you sure you want to close bla bla you have pending work..." then it freezes, I can neither close desktop view nor see the message. zVirtualDesktop remains unresponsive until you close the message, and force closes if you click on any part of the desktop view. 

There is a trick to bypass which is closing desktop view from taskbar.

I'm not sure how can you fix this, maybe spawn a thread for each closed app, or make a thread for closing apps, or just close desktop view when this happens so that you can handle that app's  window.

**Comment by mzomparelli** [comment]
Thanks for the feedback. I'll look into this. One thing I know I can do differently is Post the message instead of sending it. I was surprised that I am using SendMessage actually. I'm going to look into other messages to send as well.

**Comment by mzomparelli** [comment]
Replacing `SendMessage` with  the asynchronous `PostMessage` fixes this issue, but the thumbnail is removed from DesktopView right away. It's ok though because if you cancel the closing then it'll be there when you open DesktopView again. I'll publish an update tonight. I'm going to see what else I can take care of.

**Comment by mzomparelli** [comment]
Fixed in version 1.0.63

**Comment by jjhidalgar** [comment]
Thanks! 
Can not test it but I'm sure it will work!
