### ISSUE TITLE
Windows key doesn't work on first press after using zVD hotkeys

### ISSUE THREAD

**Issue by mwalker212** [mzomparelli/zVirtualDesktop#86]
Hi, I noticed this a while ago, so it's not a new issue, but it seems the Windows key does not work first time after using any of the zVD hotkeys.
I use Alt-Dx for switching windows, CRTL+WIN+NumPadx for moving and same plus Alt for move and follow. After using any of those, if I then press the Windows key to get the start menu, nothing happens until I press it a second time.
Is this a common issue, or something odd with my setup?

**Comment by mzomparelli** [comment]
This is a known issue. I will looking into this further next week.

**Comment by mzomparelli** [comment]
I have identified why and where this is happening. You'll be thrilled to know that I am running a version that doesn't have this issue :P and I don't plan on releasing the update until next week for two reasons:

1.) I'm moving into my new house on Friday
2.) I have some work that is not finished and I need to finish it before I release.

**Comment by mwalker212** [comment]
Good stuff. No problem, I've lived with it up to now ;-)
Good luck with the move.

**Comment by mzomparelli** [comment]
This is fixed in version 1.0.64 which I plan on releasing this weekend.
