### ISSUE TITLE
Win menu pop up

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#87]
Hi, each time I move from one desktop to another (independent of whether I use just hot-keys or mouse scroll), the windows main menu always comes up (as it normally does when you just click the Win-Key), and I have to click it "away".
zVD didn't have that problem previously. I'm now on v1.0.63

**Comment by mzomparelli** [comment]
Is Win key part of your hotkey that is causing this?

**Comment by oywino** [comment]
Yes, (and it has always been). It was my impression that the combination Ctrl-Win +left/right or numpad was the default (?)

**Comment by oywino** [comment]
Sorry - didn't mean to close  :-)

**Comment by mzomparelli** [comment]
It is default. I was just checking. I will look into this, but I won't be releasing any updates until next week. Possibly this weekend. I'm moving into my new house tomorrow! :)

**Comment by oywino** [comment]
Is there an easy way to revert back to the previous version for me, as this bug is very annoying...?

**Comment by mzomparelli** [comment]
Nothing new has caused this. It's been a known issue. Sometimes it happens and sometimes it does not. The only way to ensure it doesn't happen is to not use the Win modifier in a hotkey. The reason is that the Win key is supposed to be strictly for Windows. 3rd party applications are not supposed to use it and this is why the WinAPI for RegisterHotkey does not allow you to register the Win key. The only reason I can do anything with the Win key is because I am using a keyboard hook. I will be looking for a way to handle this, but if it continues to bother you before I figure it out then simply stop using the Win key your hotkey combinations. I know it sucks, but it is what it is. I feel the pain too which is why I want to solve this issue. I'll figure something out.

**Comment by oywino** [comment]
I see, thanks for the explanation. Strange though that I have never experienced this before. Perhaps it has to do with a recent update of Windows 10 ?

**Comment by mzomparelli** [comment]
Win 10 update is a possibility. I'm using Win 10 and I haven't done updates in a while on my work machine and using Win in my combinations is working fine. The only way I can reproduce this is when I use the Win key without any other modifier keys. Even then it doesn't happen every time. It sucks and I'm sorry. I'll do my best to figure something out.

**Comment by oywino** [comment]
What I've noticed also now, is that the key-combinations that require use of the AltGr key (such as the @ sign on my keyboard where I have to press AltGr+2 to get) no longer works. 
I seem to recall this to have been a problem with a very early version of  zVD, which you did correct quickly (but I may be mistaken or mixing things up with some other SW)

**Comment by oywino** [comment]
I now installed 1.0.63 on another Windows 10 PC before updating Windows with the Cumulative update KB4025342, and it does not have a problem with the Win key (for what it is worth).

**Comment by mzomparelli** [comment]
Thanks for that info. Can you confirm if the AltGr works on that machine? I haven't changed anything that would cause this to stop working.

**Comment by oywino** [comment]
Yes, AltGr works on that machine - also after Windows 10 latest update.
So this seems to be a problem only with my main Windows10 Workstation. And I remember having had it one time earlier, but of course I can no longer remember exactly how it was resolved. I just assumed it was related to an upgrade you did. The funny thing now is that even if i exit zVD, the problem partly persists.  :-(
Meaning that the win menu popup is gone, but AltGr still doesn't work.

**Comment by oywino** [comment]
I also notice that when I change desktops (either using shortcut keys or the mouse), in addition to the already mentioned issues, now - all too often the background comes up only black. I have to switch back and forth between two desktops to make it appear again. I never had this problem before.
I hope you can find the time to fix these issues, cause it is somewhat frustrating...

**Comment by mzomparelli** [comment]
I will look into these issues.

**Comment by oywino** [comment]
Thanks, also for your information (if can be of any help) - the problem with the black background never happens if I use Move Window to Desktop & Follow.

**Comment by mzomparelli** [comment]
Thanks, that's helpful to know. I will be addressing these issues tonight and over the weekend.

**Comment by oywino** [comment]
Another piece of information; The issue with the the Windows main menu popping up also happens if I jump to a new desktop using your virtual desktop layout (with all the desktops laid out as vertical bars). So I don't even have to press the Win key to have that annoying effect....  
Any luck in hunting down this bug so far?

**Comment by mzomparelli** [comment]
There's no reason that DesktopView would make the Start Menu open. How are you accessing DesktopView? Anyway, I think I have this fixed and I plan on publishing an update later tonight.

**Comment by oywino** [comment]
I just click on the taskbar icon. That brings up the DesktopView and I use the mouse to select which desktop I want to change to (I have six active). Regardless of which one I chose, the Win menu always comes up when I get there.

**Comment by mzomparelli** [comment]
That's really weird. I pretty much only use DesktopView for moving and navigating and the Start Menu never pops up. I have DesktopView setup to open with CTRL+SHIFT+Z and that is tied to a mouse button. Can you grab a screen shot of your version like below? Open the run dialog and type WinVer

![image](https://user-images.githubusercontent.com/10564234/29618928-3f7edbb6-87df-11e7-917e-18a06cccad32.png)

**Comment by oywino** [comment]
I've changed the hotkeys from Ctrl+Win to Ctrl+Alt but that makes no difference. The Win Menu still pops up. Then I restored the original TaskView icon and noticed that if I use this to change from one desktop to another, then everything is ok.

**Comment by mzomparelli** [comment]
Test this version. I've been making changes, but since it's been a couple of weeks I'm not sure exactly what I changed. This is the most current compilation I have.

[zVirtualDesktop.zip](https://github.com/mzomparelli/zVirtualDesktop/files/1246787/zVirtualDesktop.zip)

**Comment by oywino** [comment]
Sorry, no difference at all....
The strange thing is that I never saw this problem before v1.0.63
Maybe I should revert back to an old version just to test?

**Comment by mzomparelli** [comment]
Send me your WinVer. This is very strange. It does not happen for me at all.

**Comment by oywino** [comment]
![image](https://user-images.githubusercontent.com/18447119/29635593-bd9be3a4-884d-11e7-939c-5c3df7ae7a97.png)

**Comment by mzomparelli** [comment]
We have the same version

**Comment by oywino** [comment]
I know.
Maybe if there is a way to wipe out all zVD config (settings) and revert back to the default (perhaps somehow a setting file got screwed up)?

**Comment by mzomparelli** [comment]
I highly doubt it has anything to do with the settings file. However, to test you can use this exe. On Settings/About there is a button that says Reset Settings. This will delete the file. Restart zVD and the file will be automatically created again.

If you don't think it is deleting the file then you can manually delete the file. Do a windows search for zVirtualDesktop9.bin and delete the file. It's in isolated storage so I can't give you an exact location for it, but my location looks like this...

C:\Users\mzomp\AppData\Local\IsolatedStorage\tcfpmngd.4xb\ix3y42ct.v00\Url.53zhdaemeedzykhjwy2modwo010ev5lj\AssemFiles

[zVirtualDesktop.zip](https://github.com/mzomparelli/zVirtualDesktop/files/1247264/zVirtualDesktop.zip)

**Comment by mzomparelli** [comment]
Which keyboards do you have active in Windows? I wonder if it has something to do with international keyboards.

**Comment by mzomparelli** [comment]
Also, try turning the mouse hook off and then using DesktopView by clicking the System Tray icon. See if that makes the Start Menu pop up. I wonder if this started when I added the mouse hook.

**Comment by oywino** [comment]
Well, I do not know how to disable the Mouse-Hook, so I just set it to something silly...  But it makes no difference...

**Comment by mzomparelli** [comment]
In Settings/About click on Stop Mouse Hook Button. If it says Start then leave it alone.

**Comment by oywino** [comment]
Well, Now I've stopped Mouse Hooks, as well as Keyboard Hooks, but the problem remains...  :-(
The only way now to switch between desktops using zVD is through the task icon, and the Win Menu pops up.  If I use the TaskViewer, everything is ok.

**Comment by mzomparelli** [comment]
This is very strange. There's no reason the Start Menu would be popping up. Have you tried restarting your PC? Are you using any keyboards that are not English - American? I wonder if it is a keyboard issue.

**Comment by oywino** [comment]
No, I have a regular Norwegian Keyboard - the same keyboard I've always used (Since I first began using zVD). Now That I've disable both the Mouse Hooks as well as the Keyboard Hooks, I can again use the default Windows Ctrl-Win + left/right arrows to move between desktops, and that works ok. No menu popup. But if I click the zVD taskbar icon and bring up the desktop view of zVD and clik on any one of the desktops, it jumps there and woops - the Win menu pops up....
(Of course I have rebooted my PC several times)

**Comment by mzomparelli** [comment]
I wonder if the Windows updates affected the Norwegian keyboard. I'll do some testing with other keyboards when I get home this evening.

**Comment by oywino** [comment]
I mentioned reverting back to an earlier version of zVD.. don't you thinkthat's worth a try?

**Comment by mzomparelli** [comment]
I don't retain previous versions, but if you have a previous version then you may use it. There is a certain version (I can't remember when I implemented it) that will prevent you from being 5 versions behind so that will eventually mess you because it will kill the app if you say no to an update.

While it's zVD that has the issue, I'm not convinced zVD is the cause. It doesn't appear that anyone else is having this particular issue because they would probably be replying here or creating a new issue. I'm leaning toward this being a keyboard issue due to recent Windows Updates. I'm going to mess around with keyboards to test so hopefully I can figure out a way to resolve this for you. Just for testing purposes, what happens if you remove your Norwegian keyboard and use only the US-American? I would never expect my users to do this as a fix. This is only to test.

**Comment by oywino** [comment]
Well, if I hit Win+Space I can change between the English keyboard and the Norwegian Keyboard (This is a standard Windows feature). I've always had that feature enabled.
But doing so, doesn't make any difference.
(I thought for a while you meant physically replacing the keyboard itself)

**Comment by mzomparelli** [comment]
I would try removing every keyboard except the standard US-American keyboard. That's the only keyboard I use and I'm not having this issue. I don't intend for you to remove it forever, just to test right now. Simply switching keyboards may not be enough.

**Comment by oywino** [comment]
So, I removed all other keyboards but the US, no luck.
When I open the help menu in zVD and tick off the keyboard hooks, everything works fine. I can use the default Windows 10 hot keys Ctrl+Win+left/right arrow. 
As soon as I activate the keyboard hooks in zVD again, the Win Menu pops up every time I change desktop.

**Comment by mzomparelli** [comment]
ok, I just want to confirm that the Start Menu is popping up when you switch desktops and you are not pressing the Win key at any time during this issue?

**Comment by oywino** [comment]
This is my current scenario:
I have disabled zVD keybord-hooks  as well as mouse-hooks.
I then click on the zVD icon in the taskbar to bring up the zvD desktop-grid, and then click on any of the desktops (or any running app) and the system jumps to that desktop - and immediately the Win menu pops up and remains up until I click anywhere on the desktop outside the menu.
This happens consistently no matter which desktop I jump to or which program (app) I select.
I never press the the WIn key or any other key. I just use the mouse.

However, if I use the default built-in keyboard shortcut combination Ctrl+Win+left/right key (remember that zVD keyboard hooks and mouse hook is turned off), then everything works ok. The Win menu does NOT pop up.

**Comment by mzomparelli** [comment]
And this issue occurs on any PC you try zVD on?

**Comment by oywino** [comment]
I tried it on another PC and it works OK there. So I started to hunt for differences between the two, and the only one of and relevance and significance I found, was an App named "StartIsBack".
Disabling this on my main PC made the problem disappear! :-)
However, I am just as dependent on StartIsBAck as I am on zVD.
They somehow used to co-exist just well some time ago, but no longer. I updated StartIsback to v2.5 today, but that did not help. I also tried to disable anything within its config that could have relations to the Win key or the Win menu, but to no avail.
So now, at least we seem to know which app is conflicting with zVD.
The strange thing is that changing the keyboard hooks shortcuts in zVD to someting not involving the use of the Win key, doesn't solve the problem.
I was hopig you could also install StartIsBack and check to see if you get the same problem.

**Comment by mzomparelli** [comment]
I will try this in a Virtual Machine this evening when I get home from work. I don't like installing software on  my main machines if I don't plan on using it or I know it will conflict with a program I do want to use.

**Comment by oywino** [comment]
Have you been able to replicate the problem?

**Comment by mzomparelli** [comment]
Yes I have been able to reproduce this issue, but I'm not further along in figuring out a solution. I'm going to test this with some other Win 10 Virtual Desktop apps. I'll report back soon.

**Comment by mzomparelli** [comment]
Try this version. This might be re-introducing a different bug. I'm still testing, but this should solve your issue for now. In my opinion, this is really a bug in StartIsBack. They should not be displaying the Start Menu when Show command is sent to the taskbar. 

[zVirtualDesktop.zip](https://github.com/mzomparelli/zVirtualDesktop/files/1265585/zVirtualDesktop.zip)

**Comment by oywino** [comment]
Yes, this solved the Win-Menu problem, but the background (Desktop Wallpaper) still occasionally comes up black. Then I have to jump back and forth again to restore it. (Regular desktop refresh, doesn't cut it)
But we are progressing now :-)

**Comment by mzomparelli** [comment]
Cool, I'll be looking into the wallpaper issue tonight.
