### ISSUE TITLE
Regain focus after switching

### ISSUE THREAD

**Issue by m0ngr31** [mzomparelli/zVirtualDesktop#88]
So after the fixes you made were programs no longer flash after moving around, it'd be great if you could remember which programs were in focus when you left a desktop so you could regain those after you come back. It's a little annoying to have to click on the window again to start working on something after I come back to a desktop.

**Comment by nicolasdejong** [comment]
As a workaround you can can press alt-tab after switching desktop. The correct window will gain focus then.

I think it is a Windows bug. A focused text-field can be visible with a blinking cursor, and still the window has no focus. Then you'll be typing in another window on another virtual desktop...

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Regain focus after switching](https://trello.com/c/gsZzh9W4/8-regain-focus-after-switching)

**Comment by mzomparelli** [comment]
I think I finally have this resolved. You can force an update now or wait until 1.0.78 is published.
