### ISSUE TITLE
Black background instead of image after switching desktop

### ISSUE THREAD

**Issue by nicolasdejong** [mzomparelli/zVirtualDesktop#89]
I always switch desktops using the ctrl-win+numpad. In many cases (20%ish, more often the lower numbers it looks like...) the configured background image updates to a black image. This does not seem to happen using the ctrl-win-cursor keys.

I'm using 4K images on a 4K screen so they may take a bit longer to load/set leading to timeouts perhaps. Generally the background image changes about two seconds after switching desktop. (faster would be nice, but its probably a Windows issue)

(On a 'pilot' for a newer W10 version in our company now so I can run zVirtualDesktop finally)

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Black background instead of image after switching desktop](https://trello.com/c/ZXog8am6/7-black-background-instead-of-image-after-switching-desktop)

**Comment by nicolasdejong** [comment]
What I noticed is the the 'TranscodedWallpaper' is empty when the screen is black.

![image](https://user-images.githubusercontent.com/12181216/31274117-da7af1e8-aa91-11e7-964a-4892738eed5b.png)

So there is at least a way to check if this happens.

(this is the only thing that bothers me a bit in zVirtualDesktop. Love it! Completely changed the way I work)

**Comment by mzomparelli** [comment]
Sorry, I had put this on the back burner for awhile. I know you guys like this feature so I'm going to deal with it this weekend.

**Comment by mzomparelli** [comment]
Try this and let me know if it resolves this issue.

https://zomp.co/files.aspx?id=zvd

**Comment by nicolasdejong** [comment]
Haven't seen a black background since the update. Great!

I've put up a short video on what it looks like on my machine: https://youtu.be/ozpG8phgMAA

There is still a bit of lag showing the image after switching to another desktop, but it works every time. (Perhaps converted screens can be cached? Large/complicated images seem to be slower, as can be seen in the video).

Thanks for the fix!

**Comment by mzomparelli** [comment]
I will see what I can do about the delay, but from what I can tell on my machine, the delay is very small.

**Comment by mzomparelli** [comment]
I'm going to open a new issue for the wallpaper delay.

**Comment by mzomparelli** [comment]
@nicolasdejong  what software do you use for screen recording? Would you be interested in publishing a tutorial video that I could share on sites like LinkedIn, Reddit, and Facebook?

**Comment by nicolasdejong** [comment]
I used OBS (Open Broadcaster Software). Search for it on youtube on how to create a screen video (that's how I learned (of) it).

It is quite easy to create a youtube (== Google) account. While I won't mind putting in on my channel, why not create your own?

**Comment by mzomparelli** [comment]
Thanks for the info. I just don't think I do a very good job at explaining things. I'm trying to get my son to make one for me.
