### ISSUE TITLE
Move, Navigate, and Follow with Left and Right Keys

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#9]
I will create these:

WIN+ALT+LEFT or RIGHT: Navigate left or right
CTRL+WIN+LEFT or RIGHT: Move window left or right
CTRL+WIN+ALT+LEFT or RIGHT: Move window left or right and follow to that desktop

**Comment by Kinmarui** [comment]
FYI win+ctrl+arrow is windows buildin function ;)

**Comment by mzomparelli** [comment]
I still might be able to override Windows with my implementation. Not sure if I want to though. I'm trying to keep the hotkeys similar so it's easy to use. Thanks for letting me know this. What is your preference? Do I override Windows, choose new hotkeys for the same action, or do we just use the Windows hotkeys only for left and right?

**Comment by Kinmarui** [comment]
I would leave default where possible it will help transition for new users

**Comment by mzomparelli** [comment]
ok, this is done and I'm making the release now. I changed my hotkeys to match the default Windows one.

Navigate:
CTRL+WIN+Arrow or NumPad

Move:
ALT+WIN+Arrow or NumPad

Move & Follow:
CTRL+WIN+ALT+Arrow or NumPad
