### ISSUE TITLE
cut'n'paste is misbehaving... 

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#90]
I noticed now after the most resent update that cut'n'paste between windows only works if the windows are on the same desktop... (!?)
Never noticed this as a problem before.
Any idea?

**Comment by mzomparelli** [comment]
What are you cut and pasting? I can't reproduce this on any of my machines. It works for text and files.

**Comment by oywino** [comment]
Plain text...

**Comment by mzomparelli** [comment]
I'm not sure zVD is causing this issue. I use copy/paste a lot on a daily basis and would have noticed this. I can't work without copy/paste.

**Comment by mzomparelli** [comment]
Is this still an issue for you? I can't reproduce it so maybe it's a software conflict. Are you using any clipboard apps?

**Comment by oywino** [comment]
No, but I'll check some more and let you know if it is.
