### ISSUE TITLE
Mouse hook

### ISSUE THREAD

**Issue by gabriele-v** [mzomparelli/zVirtualDesktop#92]
Good evening,
I have some problems with mouse hook: when enabled, mouse it's very slow to move and not precise (maintains some residual movement).
If I stop mouse hook it in about options, mouse returns to working normally.
I don't need mouse hook, so I could keep it stopped, problem it's that sometimes randomly it will re-start again.

Strange thing is that with touchpad, pointer becomes slow, instead with trackpoint it moves smoothly.

Machine it's a HP zBook 15 G3 with Windows 10 Pro (1607 build 14393.1480)

Thanks

**Comment by mzomparelli** [comment]
If you have the mouse hook turned off in settings then it will still come on when you press a modifier key and turn off when no modifier is pressed. I will consider adding the ability to turn it off completely, but having it only come on when a modifier is pressed should not pose significant issues unless you constantly have modifiers pressed and for an extended period of time.

Can you confirm it is only coming back on when a modifier key is pressed?

If not then it appears your settings are not saving properly. One reason for that could be you are running zVD from a different location every time. This will happen if you unzip it to run it every time. Instead, unzip it into your startup folder and let it run from there every time. The reason is, zVD uses Isolated Storage and it will create a different folder because it looks like a different app. This means you would have a brand new settings file.

**Comment by gabriele-v** [comment]
What do you mean for modifier key? For example the combination CTRL+WIN+ALT+RIGHT to move to next screen? 
If you refer to this, it could be that it's started after modifier key pressed but not stopped when modifier key released. 
For sure the only way to disable it it's going into options and press stop mouse hook.

EXE it's always in the same folder, so it's not highlighted problem.

If you could add an option to completely disable mouse hook, it will be fantastic! 

Thanks

**Comment by mzomparelli** [comment]
A modifier key is WIN, SHIFT, CTRL, or ALT. It will go off when none of those keys are pressed. I'm not aware of any cases where it does not turn off. I'd rather confirm if it is staying on for you and address that issue too.

What are the specs of your PC? Knowing your CPU, RAM, and type of hard drive could be useful. The slower your machine the more the mouse hook will give you issues.

Background processes can interfere with the mouse hook as well, but only if the mouse hook is on. This usually only happens with heavy lifting applications that are utilizing all of your processor cores. I found that certain Excel formulas would cause this on my machine and going into Excel's settings and telling it to use one less than the number of cores I have was enough to prevent it from happening.

**Comment by gabriele-v** [comment]
It's a mobile workstation with i7-6700HQ, 16GB RAM, Nvidia Quadro M1000 and NVME SSD so I don't think it's a performance problem :) 

It could be that I have really lots of applications open (including multiple video streaming and heavy real-time encoding) but it's completely random, not related to running software: for example yesterday it happened immediately at notebook unlocking.

**Comment by mzomparelli** [comment]
I agree that your PC is plenty powerful enough. It's likely all of the programs you have running. The reason this occurs is that I have to handle all mouse events in my app. If it is not a hotkey event then I allow the event to continue through to the programs. If it is a hotkey then I swallow the event and execute the action the user has setup for the hotkey. If you have a lot of programs running then it takes time for the processor to get back around to zVD. This delay will delay the mouse events as well which you'll notice as mouse lag. It should be turning off when a modifier is not pressed, but I will add to my list the ability to turn off the mouse hook completely.

**Comment by enumag** [comment]
I didn't read the whole issue but I'm also having issue with zVirtualDesktop interfering with the speed and accuracy of my cursor. Then I found this issue and stopping the mouse hook indeed solved the problem.

Not sure what the mouse hook is for. Can you explain the feature? I won't use it unless this is solved of course, I'm just curious. Also what is the "moddifier key" that triggers the mouse hook even if I turn it off?

**Comment by mzomparelli** [comment]
The mouse hook allows creating a hotkey involving the mouse. Even if you disable the mouse hook in the settings it will still be enable when you are pressing a modifier key. A modifier key is any of the following: ALT, CTRL, SHIFT, WIN

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow Permanent Mouse Hook Disable](https://trello.com/c/w4Se14Jy/10-allow-permanent-mouse-hook-disable)

**Comment by mzomparelli** [comment]
Mouse can be disabled permanently in 1.0.68
