### ISSUE TITLE
Feature request: virtual desktop naming

### ISSUE THREAD

**Issue by gabriele-v** [mzomparelli/zVirtualDesktop#93]
A helpful feature IMHO will be option to add a name to each virtual desktop and display it for a user definable time (milliseconds) as overlay after switching to that desktop (IE when I switch to next/previous screen I know where I am).

**Comment by mzomparelli** [comment]
This has been requested already. I haven't gotten around to implementing it yet, but I will add it to my priority list.

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Desktop Naming](https://trello.com/c/VCSHzycI/1-desktop-naming)

**Comment by mzomparelli** [comment]
Completed in version 1.0.65
