### ISSUE TITLE
Instant crash without error code - Software Conflict: Http File Server

### ISSUE THREAD

**Issue by istir** [mzomparelli/zVirtualDesktop#94]
I'm using newest version, but I checked basically every other version and it still didn't work. 
On startup I can see tray icon appearing and immediately [this](https://i.imgur.com/ppvu8hS.png) pops up. I searched for error codes but I couldn't find anything, where should I look for them?

Thanks for help.

EDIT:
So after some more searching and trying to solve this myself it looks just like issue #91 and it appears it's some problem with .NET framework 4

**Comment by mzomparelli** [comment]
Can you post the stack trace for your crash? You can find it in the Windows Logs and would looks like the stack trace in issue #91. It very well could show the same thing, but I would like to verify it.

Also, the specs of your machine and your Windows version which you can get by typing WinVer into the Run dialog.

**Comment by istir** [comment]
My Windows is Version 1607, Build 14393.1593 Enterprise LTSB, I thought this could be a problem but friend of mine has the same OS and this program works fine for him.

Actually I think it has something to do with NET Framework, because recently I had similar bug with Virtual Studio 2017

As for logs:
Application: zVirtualDesktop.exe Framework Version: v4.0.30319 Description: The  process was terminated due to an unhandled exception. Exception Info:  System.Runtime.InteropServices.SEHException at  System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter+PartInfo.ReadObject(System.Xml.XmlDictionaryReader,  System.Runtime.Serialization.XmlObjectSerializer) at  System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.DeserializeParameterPart(System.Xml.XmlDictionaryReader,  PartInfo, Boolean) at  System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.DeserializeParameter(System.Xml.XmlDictionaryReader,  PartInfo, Boolean) at  System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.DeserializeBody(System.Xml.XmlDictionaryReader,  System.ServiceModel.Channels.MessageVersion, System.String,  System.ServiceModel.Description.MessageDescription, System.Object[], Boolean) at  System.ServiceModel.Dispatcher.OperationFormatter.DeserializeBodyContents(System.ServiceModel.Channels.Message,  System.Object[], Boolean) at  System.ServiceModel.Dispatcher.OperationFormatter.DeserializeReply(System.ServiceModel.Channels.Message,  System.Object[]) at  System.ServiceModel.Dispatcher.ProxyOperationRuntime.AfterReply(System.ServiceModel.Dispatcher.ProxyRpc  ByRef) at  System.ServiceModel.Channels.ServiceChannel.HandleReply(System.ServiceModel.Dispatcher.ProxyOperationRuntime,  System.ServiceModel.Dispatcher.ProxyRpc ByRef) at  System.ServiceModel.Channels.ServiceChannel.Call(System.String, Boolean,  System.ServiceModel.Dispatcher.ProxyOperationRuntime, System.Object[],  System.Object[], System.TimeSpan) at  System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(System.Runtime.Remoting.Messaging.IMethodCallMessage,  System.ServiceModel.Dispatcher.ProxyOperationRuntime) at  System.ServiceModel.Channels.ServiceChannelProxy.Invoke(System.Runtime.Remoting.Messaging.IMessage)  at  System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(System.Runtime.Remoting.Proxies.MessageData  ByRef, Int32) at  zVirtualDesktop.Zomp.IService.AddEventToDatabase(zVirtualDesktop.Zomp.EventData)  at  zVirtualDesktop.Zomp.ServiceClient.AddEventToDatabase(zVirtualDesktop.Zomp.EventData)  at zVirtualDesktop.Log.AddEventToDatabase(System.Object) at  System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at  System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object, Boolean) at  System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object, Boolean) at  System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object) at  System.Threading.ThreadHelper.ThreadStart(System.Object)


And I think you would like to see this, it's from other error entry:
Windows cannot access the file C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Core\bdce5b59a15e777c84c2c588d93856b6\System.Core.ni.dll for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program zVirtualDesktop because of this error.

Program: zVirtualDesktop
File: C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Core\bdce5b59a15e777c84c2c588d93856b6\System.Core.ni.dll

**Comment by mzomparelli** [comment]
Looks like this error was generated on a thread used for logging. The error has something to do with serialization/deserialization of web service data. Some exceptions caught are not necessary for the user to see so they get logged to me for the purpose of improving zVD for everyone. The code that is causing your crash is not necessary for the functionality of the application and I'd like to test if the program runs without it.

While it might work, it's merely a band-aid for the real issue which I still have no idea yet. Not being able to reproduce it makes it that much more difficult to figure out. Now that you know it's specific to web service serialization maybe you can narrow your search and figure it out for us :)

Also, this is different than issue #91

**Comment by istir** [comment]
Wow, it's indeed problem with network! After disabling ethernet port it works, but well, I can't use my internet that way.
I think that could be something wrong with my router's firmware, as it's custom one.
However, even after blocking zVirtualDesktop in firewall for both input and output it still crashes. Honestly I have no idea what to do from here. Maybe it's something with Avast? Maybe I will try uninstalling it later.

**Comment by mzomparelli** [comment]
Blocking it in the firewall will prevent zVD from using the network, but it will not stop it from trying. This does seem like a hardware/software problem specific to your machine or network. Keep me posted if you figure it out.

**Comment by istir** [comment]
I decided to run in safe mode with networking, and it still wouldn't work until I disabled network connection, I tried disabling some network services with task manager but it didn't do anything. Soo I think I just have to keep on using Dexpot :(

**Comment by mzomparelli** [comment]
Dexpot sucks lol. Personally, I would try resetting my PC and if that failed I would look at router config. I backup everything so for me a full rest is no big deal. In fact, I just did it today after installing a new motherboard. Now it's like nothing changed except it's much faster.

I'd rather get to the bottom of this, but if you'd rather just use Dexpot, then that's fine with me too.

**Comment by istir** [comment]
Naah, maybe I will try resetting it, I planned to do it anyway, Dexpot is buggy as hell

**Comment by istir** [comment]
Aaand everything works as intended, thanks!

And while we're at it - is there any way to assign app to certain desktop? For example I would like if spotify launched on desktop 4. Currently I'm using simple ahk script to do that and it's okay.

Oh, and maybe you know if there a way to disable multitasking for other display?

**Comment by mzomparelli** [comment]
That's my intention for glued apps, but I haven't finished it yet.

Did you figure out what the issue was that was causing your crash? Did you have to reset you PC to get it to work?

What do you mean disable multitasking for the other display?

**Comment by istir** [comment]
So yes, I reset my PC and I got it to work, but after I installed [Http File Server](http://www.rejetto.com/hfs/) it started crashing again, I'm pretty confident that was the thing that caused it. At the moment I'm trying python approach to local http servers.

What do I mean by disabling multitasking for other display is something like macOS feature that every monitor has different spaces. I don't know how to explain it so I'll use example:
I have two monitors, the main one and one for multimedia. I want to use Chrome in fullscreen on second monitor while being able to switch between spaces (displays? I don't know anymore) on my main monitor without changing anything on second display. I know I can make chrome be available on all spaces, but it's not the same thing. 
I'm not native English speaker and I doubt you can understand what I meant, but I tried my best

**Comment by mzomparelli** [comment]
I know of that feature in Mac and I think it's silly. I would get confused if my monitors were displaying different virtual desktops. I pin my chrome window while it's playing video so that I can see it whenever I change desktops.

I don't think I could implement that feature anyway. It would have to part of Win 10 Virtual Desktop for me to work with it.

I think your English is great!

**Comment by istir** [comment]
On Macs as far as I know you can disable that. 

So, everything is solved, thanks for help!
