### ISSUE TITLE
1.0.65 appears to have lost all my settings

### ISSUE THREAD

**Issue by mwalker212** [mzomparelli/zVirtualDesktop#95]
Title says it all. Updated from .64 to .65 and all settings appear to have reset to defaults :(

**Comment by mzomparelli** [comment]
Yeah, sorry about that. I know it sucks and I'm working on a solution that will allow me to add new options to settings without it causing everyone to lose their current settings. It's not a big deal though, just an inconvenience and I am sorry about it. I'll use this issue that you opened to enhance my process so to avoid this in the future.

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Don't lose settings after updating to a new version that has enhanced settings](https://trello.com/c/Mi2xvScs/11-dont-lose-settings-after-updating-to-a-new-version-that-has-enhanced-settings)

**Comment by mzomparelli** [comment]
https://github.com/mzomparelli/zVirtualDesktop/issues/105

**Comment by mzomparelli** [comment]
No more lost settings for version 1.0.68 and up. If you lost your settings after upgrading to 1.0.68 then refer to issue #105 for help on restoring them.
