### ISSUE TITLE
UPDATE AVAILABLE ?

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#98]
Hi, Version 1.0.66 is running right now and it says (In bright yellow uppercase characters) that an update is available. But clicking on that menu item or anywhere else, does not initiate any update. 
What am I missing here?

**Comment by mzomparelli** [comment]
You aren't missing anything. There is a bug that when it can't connect to my server it says there is an update in yellow on that menu option. I will fix this in 1.0.67.

**Comment by mzomparelli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Available Bug on Menu Item](https://trello.com/c/XCdTCFWE/18-update-available-bug-on-menu-item)

**Comment by mzomparelli** [comment]
The server connections have been messed up because the server and the host OS are performing Windows updates. It will be back to normal soon. I will also fix this bug so that if a connection to my server can't be established it will not tell you there is an update.

**Comment by mzomparelli** [comment]
fixed in version 1.0.67. It will get released with other fixes later tonight or tomorrow.
