### ISSUE TITLE
Window overlap on 8 Desktops and horizontal scroll issue

### ISSUE THREAD

**Issue by gitty8** [mzomparelli/zVirtualDesktop#99]
One machine being used with 7+ Desktops:
https://i.imgur.com/3y3TmTZ.png
We have overlap between the desktops and on the bottom. And horizontal scroll not works.

**Comment by mzomparelli** [comment]
This is fixed in version 1.0.67 which will be released tonight.

**Comment by mzomparelli** [comment]
Just published v1.0.67. Re-open or create a new issue if you experience this issue again.
